package:
  name: acme.sh
  version: 3.0.7
  epoch: 1
  description: ACME Shell script, an acme client alternative to certbot
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - curl
      - openssl
      - socat

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/acmesh-official/acme.sh
      tag: ${{package.version}}
      expected-commit: 377a37e4c9c23bb6988fe5f8863f21b19d3e3a40

  - runs: |
      install -dm755 "${{targets.destdir}}"/usr/share/acme.sh/deploy
      install -dm755 "${{targets.destdir}}"/usr/share/acme.sh/dnsapi
      install -dm755 "${{targets.destdir}}"/usr/share/acme.sh/notify
      install -dm755 "${{targets.destdir}}"/usr/bin

      install -m755 acme.sh "${{targets.destdir}}"/usr/share/acme.sh/
      install -m755 deploy/*.sh "${{targets.destdir}}"/usr/share/acme.sh/deploy/
      install -m755 dnsapi/*.sh "${{targets.destdir}}"/usr/share/acme.sh/dnsapi/
      install -m755 notify/*.sh "${{targets.destdir}}"/usr/share/acme.sh/notify/

      ln -s /usr/share/acme.sh/acme.sh "${{targets.destdir}}"/usr/bin/acme.sh

update:
  enabled: true
  github:
    identifier: acmesh-official/acme.sh
    strip-prefix: v
