package:
  name: actions-runner-controller
  version: 0.9.0
  epoch: 1
  description: Kubernetes controller for GitHub Actions self-hosted runners
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/actions/actions-runner-controller
      tag: gha-runner-scale-set-${{package.version}}
      expected-commit: 4357525445b0b77388af4e1f171b5b7bd9b116a4

  # Ref: https://github.com/actions/actions-runner-controller/blob/gha-runner-scale-set-0.5.0/Dockerfile#L35
  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7

  - uses: go/build
    with:
      packages: .
      output: manager
      ldflags: -s -w

  - uses: go/build
    with:
      packages: ./cmd/githubrunnerscalesetlistener
      output: github-runnerscaleset-listener
      ldflags: -s -w -X 'github.com/actions/actions-runner-controller/build.Version=${{package.version}}'

  - uses: go/build
    with:
      packages: ./cmd/githubwebhookserver
      output: github-webhook-server
      ldflags: -s -w

  - uses: go/build
    with:
      packages: ./cmd/actionsmetricsserver
      output: actions-metrics-server
      ldflags: -s -w

  - uses: go/build
    with:
      packages: ./cmd/sleep
      output: sleep
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: actions/actions-runner-controller
    strip-prefix: gha-runner-scale-set-
    tag-filter: gha-runner-scale-set-
