package:
  name: apache2
  version: 2.4.58
  epoch: 0
  description: "A high performance Unix-based HTTP server"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - apr-util-dev
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - libapr-dev
      - libxml2-dev
      - lua5.4-dev
      - nghttp2-dev
      - openssl-dev
      - pcre2-dev
      - readline-dev
      - sed
      - tree
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://dlcdn.apache.org/httpd/httpd-${{package.version}}.tar.bz2
      expected-sha512: d6e73bf413a507ec16b621ff635e178206207a9e9810ce3944b3dc98d39cde8f225307110167fc9da5822175796c8cb66f98be5b9f0d8b76dcd83a401d39b2c1
      strip-components: 0

  - working-directory: /home/build/httpd-${{package.version}}
    uses: patch
    with:
      patches: /home/build/fix-xmlchar-error.patch

  - working-directory: /home/build/httpd-${{package.version}}
    runs: |
      ./configure \
        --prefix=/ \
        --enable-layout=Debian \
        --enable-so \
        --enable-suexec \
        --with-suexec-caller=apache \
        --with-suexec-docroot=/var/www \
        --with-suexec-logfile=/var/log/apache2/suexec.log \
        --with-suexec-bin=/usr/sbin/suexec \
        --with-suexec-uidmin=99 \
        --with-suexec-gidmin=99 \
        --with-apr=/usr/bin/apr-1-config \
        --with-apr-util=/usr/bin/apu-1-config \
        --with-pcre=/usr \
        --enable-mods-shared=all \
        --enable-mpms-shared=all \
        --with-mpm=prefork \
        --enable-ssl \
        --with-ssl \
        --enable-proxy \
        --enable-cache \
        --enable-disk-cache \
        --enable-mem-cache \
        --enable-file-cache \
        --enable-ldap \
        --enable-authnz-ldap \
        --enable-cgid \
        --enable-cgi \
        --enable-authn-anon \
        --enable-authn-alias \
        --disable-imagemap \
        --enable-proxy-connect \
        --enable-proxy-http \
        --enable-proxy-ftp \
        --enable-deflate \
        --enable-dbd \
        --enable-exception-hook \
        --enable-dav \
        --enable-dav-fs \
        --enable-dav-lock

  - working-directory: /home/build/httpd-${{package.version}}
    uses: autoconf/make

  - working-directory: /home/build/httpd-${{package.version}}
    uses: autoconf/make-install

  - working-directory: /home/build/httpd-${{package.version}}
    uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: "apache2 development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - perl
        - apr-util-dev

  - name: ${{package.name}}-doc
    description: "Apache2 documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/doc/apache2
          mv "${{targets.destdir}}"/usr/share/apache2/default-site/htdocs/manual "${{targets.contextdir}}"/usr/share/doc/apache2/manual

  - name: ${{package.name}}-icons
    description: "Apache Public Domain Icons"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/apache2
          mv "${{targets.destdir}}"/usr/share/apache2/icons "${{targets.contextdir}}"/usr/share/apache2/icons

  - name: ${{package.name}}-ctl
    description: "Apache control script"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/sbin/apachectl "${{targets.contextdir}}"/usr/bin

  - name: ${{package.name}}-error
    description: "Apache multi language custom error documents"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share/apache2
          mv "${{targets.destdir}}"/usr/share/apache2/error "${{targets.contextdir}}"/usr/share/apache2/error

  - name: ${{package.name}}-utils
    description: "Apache utility programs for webservers"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/sbin
          for i in checkgid htcacheclean rotatelogs envvars envvars-std; do
            mv "${{targets.destdir}}"/usr/sbin/$i "${{targets.contextdir}}"/usr/sbin
          done

  - name: ${{package.name}}-lua
    description: "Lua support for the Apache HTTP server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_lua.so "${{targets.contextdir}}"/usr/lib/apache2
    dependencies:
      runtime:
        - apache2

  - name: ${{package.name}}-proxy-html
    description: "HTML and XML content filters for the Apache HTTP Server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_proxy_html.so "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_xml2enc.so "${{targets.contextdir}}"/usr/lib/apache2
    dependencies:
      runtime:
        - apache2

  - name: ${{package.name}}-proxy
    description: "Proxy modules for the Apache HTTP Server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_lbmethod_*.so "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_proxy*.so "${{targets.contextdir}}"/usr/lib/apache2
    dependencies:
      runtime:
        - apache2

  - name: ${{package.name}}-brotli
    description: "Brotli content compression for the Apache HTTP Server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_brotli.so "${{targets.contextdir}}"/usr/lib/apache2
    dependencies:
      runtime:
        - apache2
        - libbrotlicommon1

  - name: ${{package.name}}-ldap
    description: "LDAP authentication/authorization module for the Apache HTTP Server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/apache2
          mv "${{targets.destdir}}"/usr/lib/apache2/modules/mod_*ldap.so "${{targets.contextdir}}"/usr/lib/apache2
    dependencies:
      runtime:
        - apache2

update:
  enabled: true
  release-monitor:
    identifier: 1335
