#nolint:valid-pipeline-git-checkout-commit,valid-pipeline-git-checkout-tag
package:
  name: argocd-extension-installer
  # This project doesn't do releases and everything is commit based.
  # This corresponds to commit 880f978f59bd6434202504355c62c12e251e327a
  version: 0.0_git20231025
  epoch: 1
  description: Install Argo CD extensions using init-containers
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - curl
      - file

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/argoproj-labs/argocd-extension-installer
      branch: main

  - runs: |
      # https://github.com/argoproj-labs/argocd-extension-installer/blob/880f978f59bd6434202504355c62c12e251e327a/Dockerfile#L14
      # we are going to call the script from /home/ext-installer to be able to use it as `./install.sh` in the entrypoint of the container image
      mkdir -p "${{targets.destdir}}"/home/ext-installer
      install -Dm755 install.sh "${{targets.destdir}}"/home/ext-installer/install.sh

# Upstream repo doesn't provide any tags or releases
update:
  enabled: false

# https://raw.githubusercontent.com/argoproj/argo-helm/main/charts/argo-cd/values.yaml
test:
  environment:
    environment:
      EXTENSION_URL: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
      EXTENSION_CHECKSUM_URL: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension_checksums.txt
  pipeline:
    - runs: |
        /home/ext-installer/install.sh
        # check if there is any extension installed in /tmp/extensions/resources/ folder
        # file `extension-Metrics.js` should be present in /tmp/extensions/resources/ folder
        if [ ! -f /tmp/extensions/resources/extension-Metrics.js/extensions-Metrics.js ]; then
          echo "extension-Metrics.js not found"
          exit 1
        fi
        echo "Extensions installed"
        find /tmp/extensions/resources/ -type f
