package:
  name: aws-cli
  version: 1.32.61
  epoch: 0
  description: "Universal Command Line Interface for Amazon Web Services"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - groff
      - py3-botocore
      - py3-colorama
      - py3-docutils
      - py3-jmespath
      - py3-rsa
      - py3-s3transfer
      - py3-setuptools
      - py3-yaml
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/aws/aws-cli/archive/${{package.version}}.tar.gz
      expected-sha256: fc902af5c7e8676b754de6bc4d69b5ee589ae6fec56ca34e4e0d7cba410ed1f2

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/aws-cli
    use-tag: true
    tag-filter: "1."
