package:
  name: aws-crt-cpp
  version: 0.26.6
  epoch: 0
  description: "C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport Protocols and SSL/TLS implementations for C++"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-auth-dev
      - aws-c-cal-dev
      - aws-c-common-dev
      - aws-c-compression-dev
      - aws-c-event-stream-dev
      - aws-c-http-dev
      - aws-c-io-dev
      - aws-c-mqtt-dev
      - aws-c-s3-dev
      - aws-c-sdkutils-dev
      - aws-checksums-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - s2n-tls-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/aws-crt-cpp
      tag: v${{package.version}}
      expected-commit: ea9efcb972c869c3d5dbad751f44e56f626ff75b

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_DEPS=OFF \
        -DBUILD_TESTING="OFF" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-crt-cpp-dev
    description: aws-crt-cpp dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-crt-cpp "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-crt-cpp
        - aws-c-auth-dev
        - aws-c-cal-dev
        - aws-c-common-dev
        - aws-c-compression-dev
        - aws-c-event-stream-dev
        - aws-c-http-dev
        - aws-c-io-dev
        - aws-c-mqtt-dev
        - aws-c-s3-dev
        - aws-c-sdkutils-dev
        - aws-checksums-dev
        - s2n-tls-dev

update:
  enabled: true
  github:
    identifier: awslabs/aws-crt-cpp
    strip-prefix: v
    use-tag: true
