package:
  name: aws-c-common
  version: 0.9.15
  epoch: 0
  description: Core c99 package for AWS SDK for C including cross-platform primitives, configuration, data structures, and error handling
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - python3-dev
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8f36c7a6a5d2e17365759d15591f800d3e76dcaa34a226389b92647cbd92393a
      uri: https://github.com/awslabs/aws-c-common/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-common-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-common "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-common
    description: aws-c-common dev

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-common
    strip-prefix: v
    use-tag: true
    # we got this weird version https://github.com/awslabs/aws-c-common/releases/tag/v08.14
    # so we use filter v0. for now
    tag-filter: v0.
