package:
  name: aws-c-cal
  version: 0.6.11
  epoch: 0
  description: "AWS Crypto Abstraction Layer: Cross-Platform, C99 wrapper for cryptography primitives"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-common-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssl-dev
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: e1b0af88c14300e125e86ee010d4c731292851fff16cfb67eb6ba6036df2d648
      uri: https://github.com/awslabs/aws-c-cal/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-cal-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-cal "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-cal
    description: aws-c-cal dev

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-cal
    strip-prefix: v
    use-tag: true
