package:
  name: bazel-5
  version: 5.3.2
  epoch: 0
  description: Bazel is an open-source build and test tool
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-11
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - zip
      - bash
      - openjdk-11
pipeline:
  - uses: fetch
    with:
      expected-sha256: 3880ad919592d1e3e40c506f13b32cd0a2e26f129d87cb6ba170f1801d7d7b82
      uri: https://github.com/bazelbuild/bazel/releases/download/${{package.version}}/bazel-${{package.version}}-dist.zip
      extract: false
  - runs: unzip bazel-${{package.version}}-dist.zip
  - uses: patch
    with:
      patches: 0002-Prefer-local_jdk-instead-of-remote_jdk11.patch
  - runs: |
      mkdir -p $HOME/.cache/bazel/_bazel_root
      export JAVA_HOME=/usr/lib/jvm/openjdk

      EMBED_LABEL=${{package.version}}-${{package.epoch}} \
        EXTRA_BAZEL_ARGS=--tool_java_runtime_version=local_jdk \
        ./compile.sh

      ./output/bazel clean --expunge

      mkdir -p ${{targets.destdir}}/usr/bin
      cp ./output/bazel ${{targets.destdir}}/usr/bin/
