package:
  name: bird
  version: 2.15.1
  epoch: 0
  description: BIRD Internet Routing Daemon
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libssh-dev
      - linux-headers
      - ncurses-dev
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 48e85c622de164756c132ea77ad1a8a95cc9fd0137ffd0d882746589ce75c75d
      uri: https://bird.network.cz/download/bird-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --runstatedir=/run \
        --enable-libssh

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 192
