package:
  name: bom
  version: 0.6.0
  epoch: 2
  description: A utility to generate SPDX-compliant Bill of Materials manifests
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - go

pipeline:
  - uses: go/install
    with:
      package: sigs.k8s.io/bom/cmd/bom@v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/bom
    strip-prefix: v
