package:
  name: boring-registry
  version: 0.13.2
  epoch: 4
  description: Terraform Provider and Module Registry
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 792c31acc3a117172a9911cea52df830cf9dd465
      repository: https://github.com/TierMobility/boring-registry
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/lestrrat-go/jwx@v1.2.29 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      ldflags: |
        -s -w
        -X github.com/TierMobility/boring-registry/version.Version="${{package.version}}"
        -X github.com/TierMobility/boring-registry/version.Commit="$(git rev-parse --verify HEAD --short)"
        -X github.com/TierMobility/boring-registry/version.Date="$(date -u +'%FT%T%z')"
      output: boring-registry
      packages: .

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: TierMobility/boring-registry
    strip-prefix: v
