package:
  name: btrfs-progs
  version: "6.8"
  epoch: 0
  description: BTRFS filesystem utilities
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - asciidoc
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - e2fsprogs-dev
      - eudev-dev
      - libgcrypt-dev
      - linux-headers
      - lzo-dev
      - pkgconf-dev
      - py3-babel
      - py3-docutils
      - py3-jinja2
      - py3-packaging
      - py3-pygments
      - py3-setuptools
      - py3-sphinx
      - python3-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v${{package.version}}.tar.xz
      expected-sha512: adce7c15ef5a19c4fc513f1743b4f65f2c72aa4490703d36c93230abb305c576bd69a32c4bcf19c2b58aee5b5755e0d54fb82fe649a5fe021366eb0d89af4261

  - uses: autoconf/configure
    with:
      opts: |
        --with-crypto=libgcrypt \
        --disable-backtrace \
        --disable-documentation # documentation requires a _ton_ of python3 dependencices that should be added to sphinx instead

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: btrfs-progs-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - btrfs-progs
    description: btrfs-progs dev

  - name: py3-btrfs-progs
    description: Python 3 bindings for btrfs-progs
    dependencies:
      runtime:
        - btrfs-progs
    pipeline:
      - runs: |
          make install_python DESTDIR="${{targets.subpkgdir}}"/usr/lib/python3 V=1

  - name: btrfs-progs-bash-completion
    description: btrfs-progs bash completion
    pipeline:
      - runs: |
          _out="${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          mkdir -p $_out
          install -Dm644 btrfs-completion $_out

update:
  enabled: true
  release-monitor:
    identifier: 227
