package:
  name: bubblewrap
  version: 0.9.0
  epoch: 0
  description: "Unprivileged sandboxing tool"
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-dev
      - meson

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/containers/bubblewrap/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: f434c7b6534445e3d39183d69460c274a23e33747204de3f27e89051208c4ef1

  - runs: |
      meson --prefix=/usr -Drequire_userns=true . output
      meson compile -C output
      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output

subpackages:
  - name: bubblewrap-bash-completion
    description: bash completion for bubblewrap
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/bash-completion/completions"
          mv "${{targets.destdir}}/usr/share/bash-completion/completions/bwrap" \
            "${{targets.subpkgdir}}/usr/share/bash-completion/completions/bwrap"
          rm -rf "${{targets.destdir}}/usr/share/bash-completion"
    dependencies:
      runtime:
        - bubblewrap

  - name: bubblewrap-zsh-completion
    description: zsh completion for bubblewrap
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/zsh/site-functions"
          mv "${{targets.destdir}}/usr/share/zsh/site-functions/_bwrap" \
            "${{targets.subpkgdir}}/usr/share/zsh/site-functions/_bwrap"
          rm -rf "${{targets.destdir}}/usr/share"
    dependencies:
      runtime:
        - bubblewrap

update:
  enabled: true
  release-monitor:
    identifier: 10937
