package:
  name: buf
  version: 1.30.1
  epoch: 0
  description: A new way of working with Protocol Buffers.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: go/install
    with:
      package: github.com/bufbuild/buf/cmd/buf@v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: bufbuild/buf
