package:
  name: caddy
  version: 2.7.6
  epoch: 6
  description: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6d9a83376b5e19b3c0368541ee46044ab284038b
      repository: https://github.com/caddyserver/caddy
      tag: v${{package.version}}

  - runs: |
      install -m644 -D "./Caddyfile" "${{targets.destdir}}/etc/caddy/Caddyfile"
      install -m755 -D "./index.html" "${{targets.destdir}}/usr/share/caddy/index.html"

  - uses: patch
    with:
      patches: quic-go.patch

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 github.com/quic-go/quic-go@v0.42.0 google.golang.org/protobuf@v1.33.0 github.com/jackc/pgx/v4@v4.18.2

  - uses: go/build
    with:
      ldflags: -s -w
      output: caddy
      packages: ./cmd/caddy

  - uses: strip

subpackages:
  - name: caddy-man
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          "${{targets.destdir}}"/usr/bin/caddy manpage --directory "${{targets.subpkgdir}}"/usr/share/
    description: caddy manpages

update:
  enabled: true
  manual: false
  github:
    identifier: caddyserver/caddy
    strip-prefix: v
    tag-filter: v
    use-tag: true
