package:
  name: cedar
  version: 3.1.2
  epoch: 0
  description: "Core implementation of the Cedar language"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cedar-policy/cedar
      expected-commit: 7f42da2fa311af51f7f0e7612f735d580e982ad7
      tag: v${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/cedar ${{targets.destdir}}/usr/bin/

  - name: Simple test
    runs: |
      cat <<EOF > sample.cedar
      permit (
        principal == User::"alice",
        action == Action::"view",
        resource in Album::"jane_vacation"
      );
      EOF
      RUST_BACKTRACE=full ${{targets.destdir}}/usr/bin/cedar check-parse --policies sample.cedar

  - uses: strip

update:
  enabled: true
  github:
    identifier: cedar-policy/cedar
    strip-prefix: v
