package:
  name: certificate-transparency
  version: 1.1.8
  epoch: 1
  description: Auditing for TLS certificates
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

data:
  - name: components
    items:
      # There are a lot of binaries we may want to build out of this
      # repo, but start with what we need for sigstore.
      trillian-ctserver: ./trillian/ctfe/ct_server

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/certificate-transparency-go
      tag: v${{package.version}}
      expected-commit: 59b9bd9468c53d0f59a583752d680d0d2958985a

subpackages:
  - range: components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o "${{range.key}}" ${{range.value}}
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{range.key}} ${{targets.subpkgdir}}/usr/bin/${{range.key}}
      - uses: strip

update:
  enabled: true
  github:
    identifier: google/certificate-transparency-go
    strip-prefix: v
