package:
  name: cfssl
  version: 1.6.5
  epoch: 2
  description: Cloudflare's PKI and TLS toolkit
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudflare/cfssl
      tag: v${{package.version}}
      expected-commit: 96259aa29c9cc9b2f4e04bad7d4bc152e5405dda

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make all

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin/
      install -Dm755 bin/cfssl "${{targets.destdir}}"/usr/bin/

  - uses: strip

data:
  - name: components
    items:
      bundle: cfssl-bundle
      certinfo: cfssl-certinfo
      newkey: cfssl-newkey
      scan: cfssl-scan
      json: cfssljson
      mkbundle: mkbundle
      multirootca: multirootca

subpackages:
  - range: components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin/
          install -Dm755 bin/${{range.value}} "${{targets.subpkgdir}}"/usr/bin/

update:
  enabled: true
  github:
    identifier: cloudflare/cfssl
    strip-prefix: v
