package:
  name: chezmoi
  version: 2.47.3
  epoch: 1
  description: Manage your dotfiles across multiple diverse machines, securely.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/twpayne/chezmoi
      tag: v${{package.version}}
      expected-commit: 4f76edb5295068569d7c6311020ac0094c77ef44

  - uses: go/build
    with:
      packages: .
      repository: https://github.com/twpayne/chezmoi
      ldflags: |
        -s -w
        -X main.version=${{package.version}}
        -X main.commit=$(git rev-parse HEAD)
        -X main.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        -X main.buildSource=wolfiRelease
      output: chezmoi

  - uses: strip

update:
  enabled: true
  github:
    identifier: twpayne/chezmoi
    strip-prefix: v

test:
  pipeline:
    - runs: |
        export HOME=$PWD
        chezmoi --version
