package:
  name: cloud-sql-proxy
  version: 2.10.1
  epoch: 1
  description: The Cloud SQL Auth Proxy is a utility for ensuring secure connections to your Cloud SQL instances
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/cloud-sql-proxy
      tag: v${{package.version}}
      expected-commit: fd5250320b3d99f66fbc97eed6b50ae45e437f7b

  - uses: go/build
    with:
      packages: .
      output: cloud-sql-proxy
      ldflags: -w -X github.com/GoogleCloudPlatform/cloud-sql-proxy/v2/cmd.metadataString=container

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility package to place binaries in the location expected by upstream helm charts
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/cloud-sql-proxy ${{targets.subpkgdir}}/cloud-sql-proxy
    dependencies:
      runtime:
        - cloud-sql-proxy

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/cloud-sql-proxy
    strip-prefix: v
    tag-filter: v2
