package:
  name: cluster-proportional-autoscaler
  version: 1.8.11
  epoch: 3
  description: Kubernetes Cluster Proportional Autoscaler Container
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cluster-proportional-autoscaler
      tag: v${{package.version}}
      expected-commit: 4162fb3a23917b918edc62d71b7da96c76a7377d

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/cluster-proportional-autoscaler
      output: cluster-proportional-autoscaler
      ldflags: -s -w -X github.com/kubernetes-sigs/cluster-proportional-autoscaler/pkg/version.VERSION=v${{package.version}}

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - working-directory: ${{targets.subpkgdir}}
        runs: |
          # The helm chart expects to be able to call "./cluster-proportional-autoscaler"
          ln -s /usr/bin/cluster-proportional-autoscaler "cluster-proportional-autoscaler"
    dependencies:
      runtime:
        - cluster-proportional-autoscaler

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-proportional-autoscaler
    strip-prefix: v
    use-tag: true
    tag-filter: v
