package:
  name: cmake
  version: 3.29.0
  epoch: 0
  description: "CMake is an open-source, cross-platform family of tools designed to build, test and package software"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - libarchive-dev
      - libuv-dev
      - ncurses-dev
      - nghttp2-dev
      - openssl-dev
      - rhash-dev
      - samurai
      - wolfi-base
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.cmake.org/files/v3.29/cmake-${{package.version}}.tar.gz
      expected-sha256: a0669630aae7baa4a8228048bf30b622f9e9fd8ee8cedb941754e9e38686c778

  # Depending on system cppdap, jsoncpp, and curl would create a circular
  # dependency; thus, we use bundled ones.
  - runs: |
      ./bootstrap \
        --prefix=/usr \
        --mandir=/share/man \
        --datadir=/share/cmake \
        --docdir=/share/doc/cmake \
        --system-libs \
        --no-system-cppdap \
        --no-system-jsoncpp \
        --no-system-curl \
        --generator=Ninja \
        --parallel=$(nproc)

  - runs: |
      ninja

  - runs: |
      DESTDIR="${{targets.destdir}}" ninja install

  - uses: strip

update:
  enabled: true
  manual: true # be careful upgrading cmake as it is a core package
  release-monitor:
    identifier: 306

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - make
        - gcc
        - autoconf
        - automake
        - build-base
  pipeline:
    - working-directory: wolfi-tests
      runs: |
        cmake --version
    - working-directory: wolfi-tests
      runs: |
        mkdir -p build
        cd build
        cmake ..
        make
        ./hello_wolfi
