package:
  name: confluent-common-docker
  version: 7.6.0
  epoch: 1
  description: Confluent Commons with support for building and testing Docker images.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1517960f490072414719d11cdb66e5a183ee45dc
      repository: https://github.com/confluentinc/common-docker
      tag: v${{package.version}}

  - runs: |
      # Add missing repository to pom.xml to resolve 'io.confluent:common:pom'.
      sed -i '/<\/project>/i \  <repositories>\n    <repository>\n      <id>confluent</id>\n      <url>https://packages.confluent.io/maven/</url>\n    </repository>\n  </repositories>' pom.xml
      mvn clean install -DskipTests -Dmaven.test.skip=true

subpackages:
  # https://github.com/confluentinc/common-docker/tree/master/base
  - name: ${{package.name}}-base
    description: "This repo provides build files for the Confluent Platform Docker images."
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc/confluent/docker
          cp -r base/include/etc/confluent/docker/* "${{targets.subpkgdir}}"/etc/confluent/docker/
          chmod -R 755 ${{targets.subpkgdir}}/etc/confluent/docker

  # https://github.com/confluentinc/common-docker/tree/master/base-lite/ub
  - name: ${{package.name}}-ub
    description: "ub tool for base-lite"
    pipeline:
      - uses: go/build
        with:
          modroot: ./base-lite/ub
          packages: .
          output: ub
          subpackage: "true"
          ldflags: "-s -w"
      - uses: strip

update:
  enabled: false # Upstream repo doesn't provide any jars/poms past 7.6.0: https://packages.confluent.io/maven/io/confluent/common/

test:
  environment:
    contents:
      packages:
        - confluent-common-docker-ub
  pipeline:
    - runs: |
        ub -h
