package:
  name: configmap-reload
  version: 0.12.0
  epoch: 6
  description: Simple binary to trigger a reload when a Kubernetes ConfigMap is updated
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jimmidyson/configmap-reload
      expected-commit: 1e1ad5a21b51eb134063f242f92f7f9c2d361ea3
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: configmap-reload.go
      output: configmap-reload
      ldflags: -s -w -extldflags '-static'

  - uses: strip

update:
  enabled: true
  github:
    identifier: jimmidyson/configmap-reload
    strip-prefix: v
    tag-filter: v
    use-tag: true
