package:
  name: coredns
  version: 1.11.1
  epoch: 13
  description: CoreDNS is a DNS server that chains plugins
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libcap-utils
      - make
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ae2bbc29be1aaae0b3ded5d188968a6c97bb3144
      repository: https://github.com/coredns/coredns
      tag: v${{package.version}}

  - runs: |
      # Ensures plugins get included
      make check

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.58.3 golang.org/x/crypto@v0.17.0 github.com/quic-go/quic-go@v0.42.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/coredns/coredns/coremain.GitCommit=v${{package.version}}
      output: coredns
      packages: .

  - uses: strip

  - runs: setcap cap_net_bind_service=+ep "${{targets.destdir}}/usr/bin/coredns"

update:
  enabled: true
  github:
    identifier: coredns/coredns
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bind-tools
  pipeline:
    - runs: |
        coredns -version
        coredns -plugins
    - runs: |
        cat > Corefile <<EOF
        .:1053 {
            file /home/build/db.wolfi.dev
            log
            errors
            cache
        }
        EOF

        cat > /home/build/db.wolfi.dev <<'EOF'
        $TTL 3600
        @    IN SOA ns1.wolfi.dev. admin.wolfi.dev. (
                  20240101   ; Serial
                  7200       ; Refresh
                  3600       ; Retry
                  1209600    ; Expire
                  3600 )     ; Negative Cache TTL
        ;
        @    IN NS  ns1.wolfi.dev.
        ;
        foo.wolfi.dev  IN TXT "hi"
        EOF

        coredns &
        sleep 2

        # validates intree plugins can be successfully loaded
        dig @localhost -p 1053 foo.wolfi.dev TXT +short | grep -q '"hi"'
