package:
  name: cosign
  version: 2.2.3
  epoch: 5
  description: Container Signing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2135a2e3c40c570dc99d5784e5482ab2df903136e48fa63d4a55ade3707cad09
      uri: https://github.com/sigstore/cosign/archive/v${{package.version}}/cosign-v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - uses: go/build
    with:
      ldflags: -s -w -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
      output: cosign
      packages: ./cmd/cosign

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/cosign
    strip-prefix: v
