package:
  name: cri-tools
  version: 1.29.0
  epoch: 7
  description: CLI and validation tools for Kubelet Container Runtime Interface (CRI) .
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 3b3a9479260a5d9926c596ae068e9c51110cf546
      repository: https://github.com/kubernetes-sigs/cri-tools
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.58.3 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/sdk@v1.20.0 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/kubernetes-sigs/cri-tools/pkg/version.VERSION=${{package.version}}
      output: crictl
      packages: ./cmd/crictl

  - runs: |
      make critest
      install -Dm755 build/bin/linux/**/critest "${{targets.destdir}}"/usr/bin/critest

  - uses: strip

subpackages:
  - name: "crictl"
    description: "CLI for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/crictl ${{targets.subpkgdir}}/usr/bin/crictl

  - name: "critest"
    description: "validation test suites for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/critest ${{targets.subpkgdir}}/usr/bin/critest

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cri-tools
    strip-prefix: v
