package:
  name: cronie
  version: 1.7.2
  epoch: 0
  description: Library for extensible, efficient structure packing
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 71894fee3c74f3787e77f21a24fbbe0dffb59e7f
      repository: https://github.com/cronie-crond/cronie
      tag: cronie-${{package.version}}

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: cronie-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: cronie-crond/cronie
    strip-prefix: cronie-
    tag-filter: cronie-
    use-tag: true
