package:
  name: crossplane
  version: 1.15.1
  epoch: 2
  description: Cloud Native Control Planes
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d03b6530169975069cdac5d0bd7371880620136c
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v25.0.5

  - uses: go/build
    with:
      ldflags: -w
      output: crossplane
      packages: ./cmd/crossplane

  - uses: strip

subpackages:
  - name: crossplane-crank
    pipeline:
      - uses: go/bump
        with:
          deps: github.com/go-git/go-git/v5@v5.11.0
      - uses: go/build
        with:
          ldflags: -w
          output: crank
          packages: ./cmd/crank
          subpackage: "true"
      - uses: strip

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v
