package:
  name: crossplane-provider-gcp
  version: 1.0.2
  epoch: 1
  description: Official GCP Provider for Crossplane by Upbound
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - terraform-provider-google

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - curl
      - go
      - gzip
      - kustomize
      - up
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/upbound/provider-gcp
      tag: v${{package.version}}
      expected-commit: e24d1b402e782aa54e284cc648f1a0d6f82f988e

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      # `make` downloads `up`, unless we move our prebuilt `up` to where it expects it.
      GOARCH=$(go env GOARCH)
      UP_VERSION=$(up version --client=true)
      UP_VERSION="${UP_VERSION#*: }"
      echo "Using up ${UP_VERSION}"

      # They use hostarch instead of goarch here which uses aarch64 instead of arm64
      hostarch=$(uname -m)
      mkdir -p ./.cache/tools/linux_${hostarch}

      cp $(which up) ./.cache/tools/linux_${hostarch}/up-${UP_VERSION}

      make UP_VERSION=${UP_VERSION}

      mkdir -p "${{targets.destdir}}"/usr/bin/
      cp ./_output/bin/linux_${GOARCH}/monolith "${{targets.destdir}}"/usr/bin/provider

  - uses: strip

data:
  - name: packages
    items:
      family: provider-family-gcp
      storage: provider-gcp-storage
      pubsub: provider-gcp-pubsub

subpackages:
  - name: crossplane-provider-gcp-${{range.key}}
    range: packages
    pipeline:
      - runs: |
          up xpkg xp-extract xpkg.upbound.io/upbound/${{range.value}}:v${{package.version}}
          mkdir -p "${{targets.subpkgdir}}"
          gunzip out.gz -c > "${{targets.subpkgdir}}"/package.yaml

update:
  enabled: true
  github:
    identifier: upbound/provider-gcp
    strip-prefix: v
