package:
  name: ctop
  version: 0.7.7
  epoch: 12
  description: Top-like interface for container metrics
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha512: 9924c4dc5da489f90b029bc8060e759edf02a170e17bbc9f9c29b6536e5bc3e5eec69af829c7662a1f69cd331fc24022cae8b30e865a07742fd7e3623bc7f33f
      uri: https://github.com/bcicen/ctop/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      make build
      install -Dm755 ctop "${{targets.destdir}}"/usr/bin/ctop

  - uses: strip

update:
  enabled: true
  github:
    identifier: bcicen/ctop
    strip-prefix: v
