package:
  name: cue
  version: 0.8.1
  epoch: 1
  description: The home of the CUE language! Validate and define text-based and dynamic configuration
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/cue-lang/cue/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 353277b82998482141f727effba8900fa4ccee81e20bfbe50a27563f6dee57ec

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/cue
      output: cue
      ldflags: -w -buildid= -X cuelang.org/go/cmd/cue/cmd.version=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: cue-lang/cue
    strip-prefix: v

subpackages:
  - name: cue-bash-completion
    description: bash completion for cue
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/bash-completion/completions"
          ${{targets.destdir}}/usr/bin/cue completion bash > ${{targets.subpkgdir}}/usr/share/bash-completion/completions/cue
    dependencies:
      runtime:
        - cue

  - name: cue-zsh-completion
    description: zsh completion for cue
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/zsh/site-functions"
          ${{targets.destdir}}/usr/bin/cue completion zsh > ${{targets.subpkgdir}}/usr/share/zsh/site-functions/_cue
    dependencies:
      runtime:
        - cue

  - name: cue-fish-completion
    description: fish completion for cue
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/fish/vendor_completions.d"
          ${{targets.destdir}}/usr/bin/cue completion fish > ${{targets.subpkgdir}}/usr/share/fish/vendor_completions.d/cue.fish
    dependencies:
      runtime:
        - cue
