package:
  name: cups
  version: 2.4.2
  epoch: 0
  description: The CUPS Printing System
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-2.0-only

secfixes:
  2.4.2-r0:
    - CVE-2022-26691

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - zlib-dev
      - libpaper-dev
      - dbus
      - dbus-dev
      - libusb-dev
      - libgcrypt-dev
      - openssl-dev

      # - poppler-utils TODO add for CUPS to be useful for printing.
      # - libjpeg-turbo-dev TODO add for CUPS to be useful for printing.
      # - avahi-dev TODO add for CUPS to be useful for printing.
      # - gnutls-dev TODO add for CUPS to be useful for printing.

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7095b2977bb728ded5566a5c802866062840d6541fd027836865949a407c3682
      uri: https://github.com/OpenPrinting/cups/archive/v${{package.version}}.tar.gz
  - uses: autoconf/configure
    with:
      opts: |
        --with-menudir=/usr/share/applications \
        --with-icondir=/usr/share/icons \
        --with-logdir=/var/log/cups \
        --with-docdir=/usr/share/cups \
        --with-rundir=/run/cups \
        --with-cupsd-file-perm=0755 \
        --with-cups-user=lp \
        --with-cups-group=lp \
        --with-system-groups=lpadmin \
        --with-domainsocket=/run/cups/cups.sock \
        --enable-libusb \
        --without-rcdir \
        --disable-pam \
        --enable-raw-printing \
        --enable-dbus \
        --with-dbusdir=/usr/share/dbus-1 \
        --enable-libpaper \
        --with-tls=openssl \
        --with-optim="$CFLAGS"

  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: cups-doc
    description: cups manpages
    pipeline:
      - uses: split/manpages

  - name: cups-libs
    description: CUPS libraries
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/*.so* ${{targets.subpkgdir}}/usr/lib

          mkdir -p ${{targets.subpkgdir}}/etc
          mv ${{targets.destdir}}/usr/etc/cups ${{targets.subpkgdir}}/etc

  - name: ipptool
    description: Perform internet printing protocol requests
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/ipptool ${{targets.subpkgdir}}/usr/bin

  - name: cups-client
    description: CUPS command-line client programs
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/cupsaccept ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/cupsctl ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/cupsdisable ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/cupsenable ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/lpadmin ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/lpc ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/lpinfo ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/sbin/lpmove ${{targets.subpkgdir}}/usr/bin

  - name: cups-dev
    description: cups dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - cups
        - libgcrypt-dev
        # - gnutls-dev
        - zlib-dev
