package:
  name: curl-rustls
  version: 8.6.0
  epoch: 1
  description: "URL retrieval utility and library"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - libcurl-rustls4
  checks:
    disabled:
      - empty # curl-rustls is expected to be empty, it brings in a runtime dep on libcurl-rustls4

environment:
  contents:
    packages:
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - libpsl-dev
      - nghttp2-dev
      - openssl-dev
      - perl
      - rustls-ffi
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://curl.se/download/curl-${{package.version}}.tar.xz
      expected-sha256: 3ccd55d91af9516539df80625f818c734dc6f2ecf9bada33c76765e99121db15

  - uses: patch
    with:
      patches: e3a4273c419b744316f0a7c97736408d5aa08a27.patch

  - uses: autoconf/configure
    with:
      opts: |
        --enable-ipv6 \
        --enable-unix-sockets \
        --without-openssl \
        --with-rustls \
        --with-nghttp2 \
        --with-pic \
        --disable-ldap \
        --without-libssh2

  - uses: autoconf/make

  - runs: |
      make install DESTDIR="/home/build/curl-rustls"

subpackages:
  - name: "libcurl-rustls4"
    description: "curl library (rustls backend)"
    dependencies:
      provider-priority: 10
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "/home/build/curl-rustls"/usr/lib/libcurl.so.* "${{targets.subpkgdir}}"/usr/lib/
          strip "${{targets.subpkgdir}}"/usr/lib/libcurl.so.*

update:
  enabled: true
  version-separator: _
  github:
    identifier: curl/curl
    strip-prefix: curl-
