package:
  name: cython
  version: 3.0.10
  epoch: 0
  description: Cython is an optimising static compiler for both the Python & the extended Cython programming languages.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - python3-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 00f97476cef9fcd9a89f9d2a49be3b518e1a74b91f377fe08c97fcb44bc0f7d7
      uri: https://github.com/cython/cython/archive/${{package.version}}.tar.gz

  - runs: |
      python setup.py build
      python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: cython/cython
