package:
  name: dask-gateway
  version: 2024.1.0
  epoch: 3
  description: "A multi-tenant server for securely deploying and managing Dask clusters."
  copyright:
    - license: BSD-3-Clause
  options:
    # We create a dependency on libpython even though we provide
    # libpython in the virtual environment. This prevents python
    # versions on the host from being swapped out. Enabling no-
    # depends works around this
    no-depends: true
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - py3-gpep517
      - py3-installer
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dask/dask-gateway
      tag: ${{package.version}}
      expected-commit: 52a523041a509dd4aae3ff831cc09dbaf95bd32c

  - runs: |
      cd ${{package.name}}

      # Build package
      python -m gpep517 build-wheel --wheel-dir dist --output-fd 1

      # Setup venv and install package
      python -m venv .venv --system-site-packages
      .venv/bin/pip install -I --no-compile dist/*.whl

      mkdir -p ${{targets.destdir}}/usr/share/${{package.name}}
      mv .venv ${{targets.destdir}}/usr/share/${{package.name}}/

      # Fix venv paths
      sed -i "s|/home/build|/usr/share|g" ${{targets.destdir}}/usr/share/${{package.name}}/.venv/bin/*

      # Include system site-packages
      sed -i "s|include-system-site-packages = false|include-system-site-packages = true|g" ${{targets.destdir}}/usr/share/${{package.name}}/.venv/pyvenv.cfg

      # Symlink scripts to PATH
      mkdir -p ${{targets.destdir}}/usr/bin/
      ln -s /usr/share/${{package.name}}/.venv/bin/dask ${{targets.destdir}}/usr/bin/dask
      ln -s /usr/share/${{package.name}}/.venv/bin/dask-scheduler ${{targets.destdir}}/usr/bin/dask-scheduler
      ln -s /usr/share/${{package.name}}/.venv/bin/dask-ssh ${{targets.destdir}}/usr/bin/dask-ssh
      ln -s /usr/share/${{package.name}}/.venv/bin/dask-worker ${{targets.destdir}}/usr/bin/dask-worker

subpackages:
  - name: dask-gateway-server
    description: A multi-tenant server for securely deploying and managing Dask clusters
    options:
      no-depends: true
    dependencies:
      runtime:
        - python3
    pipeline:
      - name: Python Build
        runs: |
          cd ${{package.name}}-server

          # Build package
          python -m gpep517 build-wheel --wheel-dir dist --output-fd 1

          # Setup venv and install package
          python -m venv .venv --system-site-packages
          .venv/bin/pip install -I --no-compile dist/*.whl

          # Install kubernetes asyncio, sqlalchemy, and typing extensions
          .venv/bin/pip install kubernetes-asyncio sqlalchemy typing_extensions --no-compile

          mkdir -p ${{targets.subpkgdir}}/usr/share/${{package.name}}-server
          mv .venv ${{targets.subpkgdir}}/usr/share/${{package.name}}-server/

          # Fix venv paths
          sed -i "s|/home/build|/usr/share|g" ${{targets.subpkgdir}}/usr/share/${{package.name}}-server/.venv/bin/*

          # Include system site-packages
          sed -i "s|include-system-site-packages = false|include-system-site-packages = true|g" ${{targets.subpkgdir}}/usr/share/${{package.name}}-server/.venv/pyvenv.cfg

          # Symlink scripts to PATH
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          ln -s /usr/share/${{package.name}}-server/.venv/bin/${{package.name}}-jobqueue-launcher ${{targets.subpkgdir}}/usr/bin/${{package.name}}-jobqueue-launcher
          ln -s /usr/share/${{package.name}}-server/.venv/bin/${{package.name}}-server ${{targets.subpkgdir}}/usr/bin/${{package.name}}-server
    test:
      environment:
        contents:
          packages:
            - wolfi-base
      pipeline:
        - runs: |
            # Version check, also ensures executable paths are correct
            dask-gateway-server --version

            # Test imports in virtual environment
            source /usr/share/${{package.name}}-server/.venv/bin/activate
            python -c "import dask_gateway_server"
            python -c "import kubernetes_asyncio"
            python -c "import sqlalchemy"
            python -c "import typing_extensions"

update:
  enabled: true
  github:
    identifier: dask/dask-gateway
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        # Version check, also ensures executable paths are correct
        dask --version
        dask-scheduler --version
        dask-ssh --version
        dask-worker --version

        # Test imports in virtual environment
        source /usr/share/${{package.name}}/.venv/bin/activate
        python -c "import dask_gateway"
        python -c "from dask_gateway import Gateway"
