package:
  name: dav1d
  version: 1.4.1
  epoch: 0
  description: small and fast AV1 Decoder
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson
      - nasm

pipeline:
  - uses: fetch
    with:
      expected-sha256: ab02c6c72c69b2b24726251f028b7cb57d5b3659eeec9f67f6cecb2322b127d8
      uri: https://code.videolan.org/videolan/dav1d/-/archive/${{package.version}}/dav1d-${{package.version}}.tar.bz2

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
            -Denable_tests=false \
            -Denable_tools=true \
            -Dfuzzing_engine=none \
            -Dtestdata_tests=false

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: dav1d-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - dav1d
    description: dav1d dev

  - name: libdav1d
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libdav1d.so* ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 18920
