package:
  name: dbus
  version: 1.14.4
  epoch: 0
  description: Freedesktop.org message bus system
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: AFL-2.1 OR GPL-2.0-or-later

secfixes:
  1.14.4-r0:
    - CVE-2022-42010
    - CVE-2022-42011
    - CVE-2022-42012

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - expat-dev
      - libsm-dev
      - libx11-dev
      - meson
      - xmlto
      - bash
      # - glib-dev # TODO needed by libdbus-glib
      # - util-linux-dev # TODO adding unit-linux at a later date
pipeline:
  - uses: fetch
    with:
      expected-sha256: 7c0f9b8e5ec0ff2479383e62c0084a3a29af99edf1514e9f659b81b30d4e353e
      uri: https://dbus.freedesktop.org/releases/dbus/dbus-${{package.version}}.tar.xz
  - uses: autoconf/configure
    with:
      opts: |
        --with-system-pid-file=/run/dbus/dbus.pid \
        --enable-xml-docs=false \
        --enable-doxygen-docs=false

  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: dbus-doc
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv ${{targets.destdir}}/usr/share/doc ${{targets.subpkgdir}}/usr/share
    description: dbus manpages
  - name: dbus-libs
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/lib*.so.* ${{targets.subpkgdir}}/usr/lib

    description: D-BUS access libraries
  - name: dbus-x11
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/dbus-launch ${{targets.subpkgdir}}/usr/bin/dbus-launch
    description: X11 add-ons for D-BUS
  - name: dbus-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - dbus
        # - util-linux-dev todo add when util-linux is packaged
    description: dbus dev
