package:
  name: delta
  version: 0.17.0
  epoch: 0
  description: Syntax-highlighting pager for git and diff output
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dandavison/delta
      tag: ${{package.version}}
      expected-commit: 13c8219799be3291ed592a9bd00e707577fbf6f6

  - runs: |
      cargo build --release
      install -Dm755 target/release/delta "${{targets.destdir}}"/usr/bin/delta

  - uses: strip

test:
  pipeline:
    - runs: |
        delta --version

update:
  enabled: true
  github:
    identifier: dandavison/delta
