package:
  name: delve
  version: 1.22.1
  epoch: 2
  description: Delve is a debugger for the Go programming language.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/go-delve/delve/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: fe6f0d97c233d4f0f1ed422c11508cc57c14e9e0915f9a258f1912c46824cbfb

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv dlv ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: go-delve/delve
    strip-prefix: v
