package:
  name: deno
  version: 1.42.1
  epoch: 0
  description: "A modern runtime for JavaScript and TypeScript."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - glibc-dev
      - libLLVM-16
      - posix-libc-utils
      - protobuf-dev
      - protoc
      - python3
      - rust
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/denoland/deno/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 3d10e8bd672418a940f18c8d6b84010579af14d25a61eecd716a4880e2d23733

  - name: Configure and build
    runs: |
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/deno ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: denoland/deno
    strip-prefix: v

test:
  pipeline:
    - runs: |
        deno --version
        echo 'console.log("Hello, World!");' > hello_world.js
        output=$(deno run hello_world.js)
        if [ "$output" = "Hello, World!" ]; then
          echo "Test passed!"
        else
          echo "Test failed!"
          exit 1
        fi
