package:
  name: difftastic
  version: 0.57.0
  epoch: 0
  description: "a structural diff that understands syntax"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Wilfred/difftastic
      tag: ${{package.version}}
      expected-commit: 00e837aeb1575762f571d47adfc81fb89621e387

  - runs: |
      cargo build --release
      install -Dm755 target/release/difft "${{targets.destdir}}"/usr/bin/difft

  - uses: strip

update:
  enabled: true
  github:
    identifier: Wilfred/difftastic
