package:
  name: docker-compose
  version: 2.26.1
  epoch: 1
  description: Define and run multi-container applications with Docker
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/compose
      tag: v${{package.version}}
      expected-commit: ff20b641c7f1cce588faea476fbd1a6fdd953b36

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      DESTDIR=${{targets.destdir}}/usr/bin/ make build

test:
  environment:
    contents:
      packages:
        - docker-cli
  pipeline:
    - runs: docker compose --help

update:
  enabled: true
  github:
    identifier: docker/compose
    strip-prefix: v
    tag-filter: v
