package:
  name: dockerize
  version: 0.7.0
  epoch: 6
  description: Utility to simplify running applications in docker containers
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jwilder/dockerize
      tag: v${{package.version}}
      expected-commit: c489c4f42d15df111d02d80fce5816bb024278f4

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 golang.org/x/crypto@v0.17.0

  - uses: go/build
    with:
      packages: .
      output: dockerize
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: jwilder/dockerize
    strip-prefix: v
    use-tag: true
    tag-filter: v
