package:
  name: docker-cli
  version: 24.0.6
  epoch: 3
  description: The Docker CLI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - btrfs-progs-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - containerd
      - coreutils
      - go
      - libseccomp-dev
      - libtool
      - linux-headers
      - lvm2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/docker/cli
      tag: v${{package.version}}
      expected-commit: ed223bc820ee9bb7005a333013b86203a9e1bc23

  - runs: |
      export DISABLE_WARN_OUTSIDE_CONTAINER=1

      mkdir -p "$GOPATH/src/github.com/docker/"
      ln -sf /home/build "$GOPATH"/src/github.com/docker/cli
      LDFLAGS="" make VERSION=${{package.version}} dynbinary

      install -Dm755 build/docker-linux-* ${{targets.destdir}}/usr/bin/docker

  - runs: |
      make manpages
      install -Dm644 man/man1/* -t ${{targets.destdir}}/usr/share/man/man1/

  # Docker is vehemenetly against stripping the resulting binary
  # Ref: https://github.com/moby/moby/blob/d8a51d2887cbc465ab8d76ed98f7a86996ab3c22/project/PACKAGERS.md#stripping-binaries
  # - uses: strip
  - runs: |
      # this exists to appease yam

subpackages:
  - name: "docker-cli-doc"
    description: "docker-cli documentation"
    pipeline:
      - uses: split/manpages

  # Ref: https://github.com/docker-library/docker/blob/master/Dockerfile-cli.template
  - name: docker-cli-compat
    dependencies:
      runtime:
        - docker-oci-entrypoint
        - docker-modprobe-compat

update:
  enabled: true
  github:
    identifier: docker/cli
    strip-prefix: v
    tag-filter: v
