package:
  name: dropbear
  version: "2024.84"
  epoch: 0
  description: "small SSH 2 client/server designed for small memory environments"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://matt.ucc.asn.au/dropbear/releases/dropbear-${{package.version}}.tar.bz2
      expected-sha512: 254daea819c5aeaa65bb43449386fb964f4aa13e3b3037fe11064120205c6e265925e7ef2d84f7ebe66c6a00cf0a22e6010314c065ed49a3815f47137b7aca44

  - uses: autoconf/configure
    with:
      opts: |
        --disable-utmp \
        --disable-wtmp \
        --disable-pututline \
        --disable-lastlog

  - uses: autoconf/make
    with:
      opts: |
        PROGRAMS="dropbear dropbearkey dbclient dropbearconvert scp"

  - uses: autoconf/make-install
    with:
      opts: |
        PROGRAMS="dropbear dropbearkey dbclient dropbearconvert scp"

  - uses: strip

subpackages:
  - name: dropbear-dbclient
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/dbclient "${{targets.subpkgdir}}"/usr/bin/

  - name: dropbear-convert
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/dropbearconvert "${{targets.subpkgdir}}"/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 466
