package:
  name: dumb-init
  version: 1.2.5
  epoch: 0
  description: "minimal init system for Linux containers"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
      
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/Yelp/dumb-init/archive/v${{package.version}}.tar.gz
      expected-sha256: 3eda470d8a4a89123f4516d26877a727c0945006c8830b7e3bad717a5f6efc4e
  - uses: autoconf/make
  - runs: |
      install -sD -m 755 dumb-init "${{targets.destdir}}"/usr/bin/dumb-init
  - uses: strip
