package:
  name: efs-utils
  version: 1.36.0
  epoch: 0
  description: Utilities for Amazon Elastic File System (EFS)
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - busybox
      # Ref: https://github.com/aws/efs-utils/blob/master/amazon-efs-utils.spec#L49-L58
      - nfs-utils
      - openssl
      - stunnel
      - systemd
      - util-linux

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - make
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/efs-utils
      tag: v${{package.version}}
      expected-commit: c87d19f3e1db26532f09a7fed338347aacb90e10

  # This looks a little funny, but it aims to be easier to maintain, so we just
  # copy from the upstream `build-deb.sh` script the bits we need.
  # Ref: https://github.com/aws/efs-utils/blob/master/build-deb.sh
  - runs: |
      export BUILD_ROOT="${{targets.destdir}}"
      mkdir -p ${BUILD_ROOT}

      echo 'Creating application directories'
      mkdir -p ${BUILD_ROOT}/etc/amazon/efs
      mkdir -p ${BUILD_ROOT}/etc/init/
      mkdir -p ${BUILD_ROOT}/etc/systemd/system
      mkdir -p ${BUILD_ROOT}/sbin
      mkdir -p ${BUILD_ROOT}/usr/bin
      mkdir -p ${BUILD_ROOT}/var/log/amazon/efs
      mkdir -p ${BUILD_ROOT}/usr/share/man/man8

      echo 'Copying application files'
      install -p -m 644 dist/amazon-efs-mount-watchdog.conf ${BUILD_ROOT}/etc/init
      install -p -m 644 dist/amazon-efs-mount-watchdog.service ${BUILD_ROOT}/etc/systemd/system
      install -p -m 444 dist/efs-utils.crt ${BUILD_ROOT}/etc/amazon/efs
      install -p -m 644 dist/efs-utils.conf ${BUILD_ROOT}/etc/amazon/efs
      install -p -m 755 src/mount_efs/__init__.py ${BUILD_ROOT}/sbin/mount.efs
      install -p -m 755 src/watchdog/__init__.py ${BUILD_ROOT}/usr/bin/amazon-efs-mount-watchdog

update:
  enabled: true
  github:
    identifier: aws/efs-utils
    strip-prefix: v
    use-tag: true
    tag-filter: v
