package:
  name: eksctl
  version: 0.175.0
  epoch: 1
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaveworks/eksctl
      expected-commit: 5b28c17948a1036f26becbbc02d23e61195e8a33
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - runs: |
      make binary
      mkdir -p ${{targets.destdir}}/usr/bin
      mv eksctl ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: weaveworks/eksctl
    strip-prefix: v
