package:
  name: encodings
  version: 1.0.6
  epoch: 0
  description: X.org font encoding files
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: custom
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - mkfontscale
      - util-macros
pipeline:
  - uses: fetch
    with:
      expected-sha256: 77e301de661f35a622b18f60b555a7e7d8c4d5f43ed41410e830d5ac9084fc26
      uri: https://www.x.org/releases/individual/font/encodings-${{package.version}}.tar.xz
  - uses: autoconf/configure
    with:
      opts: --with-encodingsdir=/usr/share/fonts/encodings
  - uses: autoconf/make
  - uses: autoconf/make-install
