package:
  name: esbuild
  version: 0.20.2
  epoch: 1
  description: An extremely fast bundler for the web
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/evanw/esbuild
      tag: v${{package.version}}
      expected-commit: 617eddaa32b7649ad23ddd15257816df3f0f544c

  - runs: |
      make esbuild
      mkdir -p ${{targets.destdir}}/usr/bin
      mv esbuild ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: evanw/esbuild
    strip-prefix: v
