package:
  name: exa
  version: 0.10.1
  epoch: 1
  description: "ls replacement written in Rust"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libgit2-dev
      - rust
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ogham/exa
      tag: v${{package.version}}
      expected-commit: 293372a613932a084a4b84218cc7cc374d15955e

  - runs: |
      cargo fetch
      cargo build --frozen --release

  - runs: |
      install -Dm755 target/release/exa "${{targets.destdir}}"/usr/bin/exa

  - uses: strip

update:
  enabled: true
  github:
    identifier: ogham/exa
    strip-prefix: v

test:
  pipeline:
    - runs: |
        exa --version
