package:
  name: exiftool
  version: 12.70
  epoch: 0
  description: ExifTool meta information reader/writer
  copyright:
    - license: GPL-3.0-only
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/exiftool/exiftool
      tag: ${{package.version}}
      expected-commit: bec8a1bff8a97ea8f2895e7e5c5e396e0e48d419

  - runs: |
      PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
      make
      make DESTDIR="${{targets.destdir}}" install

      # creates file collision among perl modules
      find "${{targets.destdir}}" -name perllocal.pod -delete
      find "${{targets.destdir}}" -name .packlist -delete

  - uses: strip

update:
  enabled: true
  github:
    identifier: exiftool/exiftool

test:
  pipeline:
    - runs: |
        exiftool --version
