package:
  name: external-secrets-operator
  version: 0.9.14
  epoch: 1
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - yq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: a14d49d288b041c9ba628ddef283dc90bdb9b593

  - runs: |
      make build-$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D bin/external-secrets-$(go env GOOS)-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/external-secrets

  - uses: strip

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
