package:
  name: ferretdb
  version: 1.21.0
  epoch: 1
  description: "A truly Open Source MongoDB alternative"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/FerretDB/FerretDB
      tag: v${{package.version}}
      expected-commit: a3fb274d25bac13aea594ec34d603338bc00bfc3

  - uses: go/build
    with:
      packages: ./cmd/ferretdb
      output: ferretdb
      tags: ferretdb_tigris
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: FerretDB/FerretDB
    strip-prefix: v
