package:
  name: flux-notification-controller
  version: 1.2.4
  epoch: 3
  description: The GitOps Toolkit event forwarded and notification dispatcher
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0768aa25556bc456a2e33be1554bb96bb3a68c3b
      repository: https://github.com/fluxcd/notification-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=0 go build \
        -trimpath -a -o "${{targets.destdir}}"/usr/bin/notification-controller .

  - uses: strip

update:
  enabled: true
  github:
    identifier: fluxcd/notification-controller
    strip-prefix: v
    tag-filter: v
