package:
  name: flux-source-controller
  version: 1.2.5
  epoch: 0
  description: The GitOps Toolkit source management component
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - clang-16
      - gcc
      - go
      - llvm-lld-16

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b104212a8bc2aba714b2b8f0e23a9cce69ed8c2a
      repository: https://github.com/fluxcd/source-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: helm.sh/helm/v3@v3.14.2 github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      CGO_ENABLED=1 CGO_LDFLAGS="-static -fuse-ld=lld" go build \
        -ldflags "-s -w" \
        -tags 'netgo,osusergo,static_build' \
        -trimpath -o "${{targets.destdir}}"/usr/bin/source-controller .

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - api/
  github:
    identifier: fluxcd/source-controller
    strip-prefix: v
    tag-filter: v
