package:
  name: flux-image-reflector-controller
  version: 0.31.2
  epoch: 4
  description: GitOps Toolkit controller that scans container registries
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fluxcd/image-reflector-controller
      tag: v${{package.version}}
      expected-commit: 91075515aba358e2a35dcaec91d8fa94d9c6a9ba

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - uses: go/build
    with:
      packages: .
      output: image-reflector-controller
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - api/
  github:
    identifier: fluxcd/image-reflector-controller
    strip-prefix: v
    use-tag: true
    tag-filter: v
