package:
  name: flux
  version: 2.2.3
  epoch: 4
  description: Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - go
      - kustomize

pipeline:
  - uses: fetch
    with:
      expected-sha256: bd7a284be9c7d16bc080ec9f559def1e3489bfa8fec49d7e95c352dc002b9724
      uri: https://github.com/fluxcd/flux2/archive/v${{package.version}}/v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: github.com/cloudflare/circl@v1.3.7 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      VERSION=${{package.version}} make build
      install -Dm755 bin/flux ${{targets.destdir}}/usr/bin/flux

  - runs: |
      ${{targets.destdir}}/usr/bin/flux version --client| grep "flux: v${{package.version}}"

  - uses: strip

subpackages:
  - name: "flux-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the flux binaries to be in /usr/local/bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/flux ${{targets.subpkgdir}}/usr/local/bin/flux

update:
  enabled: true
  github:
    identifier: fluxcd/flux2
    strip-prefix: v
