package:
  name: flux-kustomize-controller
  version: 1.2.2
  epoch: 4
  description: The GitOps Toolkit Kustomize reconciler
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - git
      - gnupg
      - gnupg-gpgconf
      - gnupg-utils
      - gnupg-wks-client
      - gpg
      - gpg-agent
      - gpg-wks-server
      - gpgsm
      - gpgv
      - openssh-client
      - tzdata

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7a5ae11e2da9c326350216f6783caa0a0214a322
      repository: https://github.com/fluxcd/kustomize-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      ldflags: -s -w
      output: kustomize-controller
      packages: .

  - uses: strip

update:
  ignore-regex-patterns:
    - api/
  enabled: true
  github:
    identifier: fluxcd/kustomize-controller
    strip-prefix: v
    tag-filter: v
    use-tag: true
