package:
  name: fmt
  version: 10.2.1
  epoch: 0
  description: Modern formatting library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e69e5f977d458f2650bb346dadf2ad30c5320281
      repository: https://github.com/fmtlib/fmt
      tag: ${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: fmtlib/fmt
