package:
  name: font-util
  version: 1.3.3
  epoch: 0
  description: X.org font utilities
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: custom
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - util-macros
      - perl
pipeline:
  - uses: fetch
    with:
      expected-sha256: e791c890779c40056ab63aaed5e031bb6e2890a98418ca09c534e6261a2eebd2
      uri: https://www.x.org/releases/individual/font/font-util-${{package.version}}.tar.xz
  - uses: autoconf/configure
    with:
      opts: |
        --mandir=/usr/share/man

  - uses: autoconf/make
  - uses: autoconf/make-install
subpackages:
  - name: font-util-dev
    pipeline:
      - uses: split/dev
  - name: font-util-doc
    pipeline:
      - uses: split/manpages
