package:
  name: fq
  version: 0.10.0
  epoch: 2
  description: "jq for binary formats - tool, language and decoders for working with binary and text formats"
  copyright:
    - license: MIT

pipeline:
  - uses: go/install
    with:
      package: github.com/wader/fq
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: wader/fq
    strip-prefix: v
