package:
  name: gdal-py3.10
  version: 3.8.5
  epoch: 0
  description: GDAL is an open source MIT licensed translator library for raster and vector geospatial data formats.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - armadillo-dev
      - arpack-dev
      - autoconf
      - automake
      - basisu-dev
      - bison
      - blosc-dev
      - brunsli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - expat-dev
      - geos-dev
      - glibc-iconv
      - lerc-dev
      - libdeflate-dev
      - libgeotiff-dev
      - libpng-dev
      - libtirpc-dev
      - libxml2-dev
      - mariadb-dev
      - nlohmann-json
      - odbc-cpp-wrapper-dev
      - openblas-dev
      - opencl-dev
      - openjpeg-dev
      - openssl-dev
      - pcre2-dev
      - proj-dev
      - py3.10-setuptools
      - python-3.10
      - python-3.10-dev
      - qhull-dev
      - sqlite-dev
      - swig
      - tiff-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 0c865c7931c7e9bb4832f50fb53aec8676cbbaccd6e55945011b737fb89a49c2
      uri: https://github.com/OSGeo/gdal/releases/download/v${{package.version}}/gdal-${{package.version}}.tar.gz

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: py3.10-gdal-dev
    pipeline:
      - uses: split/dev
    dependencies:
      provides:
        - py3-gdal-dev=${{package.full-version}}

  - name: py3.10-gdal
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv ${{targets.destdir}}/usr/lib/python3* ${{targets.subpkgdir}}/usr/lib/
    dependencies:
      provides:
        - py3-gdal=${{package.full-version}}

  - name: py3.10-gdal-tools
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/* ${{targets.subpkgdir}}/usr/bin/
          chmod a+x scripts/*
          mv scripts/* ${{targets.subpkgdir}}/usr/bin/
    dependencies:
      provides:
        - py3-gdal-tools=${{package.full-version}}

update:
  enabled: true
  release-monitor:
    identifier: 881

test:
  environment:
    contents:
      packages:
        - busybox
        - python-3.10
        - py3.10-gdal
  pipeline:
    - runs: |
        python -c '
        from osgeo import gdal

        # Create a GeoTIFF file
        driver = gdal.GetDriverByName("GTiff")
        dataset = driver.Create("checkerboard.tif", 50, 50, 1, gdal.GDT_Byte)
        band = dataset.GetRasterBand(1)

        # Fill the image with a checkerboard pattern
        for i in range(50):
          for j in range(50):
            if (i // 10 + j // 10) % 2 == 0:
              band.WriteRaster(j, i, 1, 1, bytes([255]))

        # Close the dataset to flush changes to disk
        dataset = None'
