package:
  name: gh
  version: 2.47.0
  epoch: 0
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9744489510054d021cc06595a0572d15b6135851
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        gh --version
