package:
  name: ghaudit
  version: 0.4.0
  epoch: 1
  description: Experimental tool for evaluating Chainguard's GitHub policies.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/chainguard-dev/ghaudit/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 157a6124c55963584ad1d3b62e769558def3a4f21c7a17076b7e3af70d7e70c6

  - uses: go/build
    with:
      packages: .
      ldflags: -s -w
      output: ghaudit

  - uses: strip

test:
  pipeline:
    - runs: |
        # This expects GH_TOKEN to be set and will error.
        if ghaudit --help; then
          echo "This should error without GH_TOKEN set."
          exit 1
        fi

        # This should print usage.
        GH_TOKEN=foo ghaudit --help

update:
  enabled: true
  github:
    identifier: chainguard-dev/ghaudit
    strip-prefix: v
