package:
  name: git-lfs
  version: 3.5.1
  epoch: 1
  description: "large file support for git"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - git

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/git-lfs/git-lfs
      tag: v${{package.version}}
      expected-commit: e237bb3a364603cbb92cabc34b8401d1ad5d795b

  - runs: |
      make EXTRA_GO_FLAGS="-v -tags netcgo" EXTRA_LD_FLAGS="-s -w -extldflags '${LDFLAGS}'" VERSION="v${{package.version}}"
      install -Dm755 bin/git-lfs "${{targets.destdir}}"/usr/bin/git-lfs

  - uses: strip

update:
  enabled: true
  github:
    identifier: git-lfs/git-lfs
    tag-filter: v
    strip-prefix: v
