package:
  name: gitlab-logger
  version: 3.0.0
  epoch: 5
  description: GitLab Logger provides a means of wrapping non-structured log files within structure JSON.
  copyright:
    - license: MIT

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      # https://gitlab.com/gitlab-org/cloud-native/gitlab-logger
      uri: https://gitlab.com/gitlab-org/cloud-native/gitlab-logger/-/archive/v${{package.version}}/gitlab-logger-v${{package.version}}.tar.gz
      expected-sha256: b6bca21e3eba525334f4b140d9d9405181a25821365ccd9065402fa050af78d5

  - uses: go/build
    with:
      packages: ./cmd/gitlab-logger
      output: gitlab-logger
      ldflags: -w

  - uses: strip

subpackages:
  - name: gitlab-logger-compat
    dependencies:
      runtime:
        - gitlab-logger
    pipeline:
      - runs: |
          # GitLab helm chart mostly hardcodes multiple executables path to /usr/local/bin/*
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/gitlab-logger "${{targets.subpkgdir}}"/usr/local/bin/gitlab-logger

update:
  enabled: false
