package:
  name: gitleaks
  version: 8.18.2
  epoch: 2
  description: SAST tool for detecting and preventing hardcoded secrets like passwords, api keys, and tokens in git repos
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gitleaks/gitleaks
      expected-commit: ac4b5146b0f112df989b4374abb2b12799e37cba
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/text@v0.3.8

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv gitleaks ${{targets.destdir}}/usr/bin/gitleaks

  - uses: strip

update:
  enabled: true
  github:
    identifier: gitleaks/gitleaks
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - runs: |
        gitleaks version
