# source is gitlab so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: gitlab-runner
  version: 16.8.0
  epoch: 3
  description: GitLab Runner is the open source project that is used to run your CI/CD jobs and send the results back to GitLab
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitlab-runner
      tag: v${{package.version}}
      expected-commit: c72a09b670c4370a9e57e4ed89697ff3ce3ab84f

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: gitlab-runner
      ldflags: -s -w -X gitlab.com/gitlab-org/gitlab-runner/common.NAME=${{package.name}} -X gitlab.com/gitlab-org/gitlab-runner/common.VERSION=v${{package.version}}

subpackages:
  - name: gitlab-runner-helper
    description: GitLab Runner Helper
    pipeline:
      - uses: go/build
        with:
          packages: ./apps/gitlab-runner-helper
          output: gitlab-runner-helper
          ldflags: -s -w -X gitlab.com/gitlab-org/gitlab-runner/common.NAME=${{package.name}} -X gitlab.com/gitlab-org/gitlab-runner/common.VERSION=v${{package.version}}

update:
  enabled: true
  release-monitor:
    identifier: 11337
