# Source is on gitlab so we can't use github for updates
#nolint:git-checkout-must-use-github-updates
package:
  name: gitlab-pages
  version: 16.9.2
  epoch: 2
  description: GitLab Pages daemon used to serve static websites for GitLab users.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - gitlab-cng-base
      - gitlab-cng-pages-scripts

environment:
  contents:
    packages:
      - gitlab-cng-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitlab-pages.git
      tag: v${{package.version}}
      expected-commit: 9c697eea965a1ab9f0816409b67583bf83fa1767

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make gitlab-pages "LAST_TAG=v${{package.version}}" "VERSION=v${{package.version}}"

  - runs: |
      mkdir -p ${{targets.destdir}}/bin
      install -m +x ./bin/gitlab-pages ${{targets.destdir}}/bin/gitlab-pages
      mkdir -p ${{targets.destdir}}/srv/gitlab-pages/
      mkdir -p ${{targets.destdir}}/var/log/gitlab

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 10037
