package:
  name: go-md2man
  version: 2.0.4
  epoch: 1
  description: Utility to convert markdown to man pages
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: b0a4c7c077ede56967deef6ab7e7696c0f46124b0b3360fd05564ec5a536f11f
      uri: https://github.com/cpuguy83/go-md2man/archive/v${{package.version}}.tar.gz

  - uses: go/build
    with:
      packages: .
      output: go-md2man
      ldflags: -s -w

  - runs: |
      ${{targets.destdir}}/usr/bin/go-md2man -in go-md2man.1.md -out go-md2man.1
      install -Dm644 go-md2man.1 "${{targets.destdir}}"/usr/share/man/man1/go-md2man.1

  - uses: strip

subpackages:
  - name: go-md2man-doc
    pipeline:
      - uses: split/manpages
    description: go-md2man manpages

update:
  enabled: true
  github:
    identifier: cpuguy83/go-md2man
    strip-prefix: v
