package:
  name: gobuster
  version: 3.6.0
  epoch: 6
  description: "a tool used to brute force attack for URIs, DNS, etc."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - go

pipeline:
  - uses: go/install
    with:
      package: github.com/OJ/gobuster/v3
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: OJ/gobuster
