package:
  name: golangci-lint
  version: 1.57.2
  epoch: 1
  description: Fast linters Runner for Go
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - diffutils

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/golangci/golangci-lint/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: 965e91f54c8fcdccea30630c175299322088804110319282fc87a629bcb02b08

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp ./golangci-lint ${{targets.destdir}}/usr/bin/golangci-lint

  - uses: strip

update:
  enabled: true
  github:
    identifier: golangci/golangci-lint
    strip-prefix: v
