package:
  name: google-cloud-sdk
  version: 469.0.0
  epoch: 0
  description: "Google Cloud Command Line Interface"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      # Required for cyclic redunancy check (gsutil help crcmod)
      - py3-crcmod
      - python-3.12

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - python-3.12
      - python-3.12-dev
      - wolfi-base

pipeline:
  - runs: |
      # This step is just here to make it easier to grab SHAs of the files, for adding to the steps below.
      echo "SHA256 of google-cloud-sdk-${{package.version}}-linux-x86_64.tar.gz"
      curl -sL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${{package.version}}-linux-x86_64.tar.gz | sha256sum -

      echo "SHA256 of google-cloud-sdk-${{package.version}}-linux-arm.tar.gz"
      curl -sL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${{package.version}}-linux-arm.tar.gz | sha256sum -

  - if: ${{build.arch}} == "x86_64"
    uses: fetch
    with:
      uri: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${{package.version}}-linux-x86_64.tar.gz
      expected-sha256: 896151e0ff30820c0e448bf5656be77d4888ced8edc1e9405fc21368f97dbea5
      strip-components: 0

  - if: ${{build.arch}} == "aarch64"
    uses: fetch
    with:
      uri: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${{package.version}}-linux-arm.tar.gz
      expected-sha256: 10d52ed535c5586fca51179637f0a3aa9cea184371183b9f531b416fcc95fb52
      strip-components: 0

  - runs: |
      ./google-cloud-sdk/install.sh -q
      mkdir -p ${{targets.destdir}}/usr/share/

      # Trim some extra stuff
      rm -rf google-cloud-sdk/platform/bundledpythonunix/
      rm -rf google-cloud-sdk/deb
      rm -rf google-cloud-sdk/rpm
      rm google-cloud-sdk/install.bat
      rm google-cloud-sdk/data/cli/gcloud.json

      # Remove any third party tests that bloat up the package
      find google-cloud-sdk -type d \( -name 'tests' -o -name 'test' \) -path '*/third_party/*' -exec rm -rf {} +

      # This is a large binary with vulnerabilities in it, users can add it back later.
      google-cloud-sdk/bin/gcloud components remove anthoscli

      # This is a large binary with vulnerabilities in it, users can add it back later.
      google-cloud-sdk/bin/gcloud components remove gcloud-crc32c

      # Running gcloud adds a bunch of pyc files, remove those
      find google-cloud-sdk/ -name "*.pyc" -exec rm -rf '{}' +
      rm -rf google-cloud-sdk/.install

      # gcloud expects to find a directory called ".install" in its "Installation Root" (as reported by "gcloud info").
      # Without this, "gcloud components" doesn't work.
      mkdir google-cloud-sdk/.install

      mv google-cloud-sdk ${{targets.destdir}}/usr/share/

      mkdir -p ${{targets.destdir}}/usr/bin
      for f in anthoscli bq docker-credential-gcloud gcloud gcloud-crc32c git-credential-gcloud.sh gsutil java_dev_appserver.sh; do
        ln -sf /usr/share/google-cloud-sdk/bin/$f ${{targets.destdir}}/usr/bin/$f
      done

  - uses: strip

test:
  pipeline:
    - runs: gcloud --version
    - runs: gsutil --version
    - runs: gcloud components list

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/cloud-sdk-docker
    strip-prefix: v
    use-tag: true
