package:
  name: goreleaser
  version: 1.25.1
  epoch: 0
  description: Deliver Go binaries as fast and easily as possible
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - git

pipeline:
  - uses: go/install
    with:
      package: github.com/goreleaser/goreleaser@v${{package.version}}

update:
  enabled: true
  github:
    identifier: goreleaser/goreleaser
    strip-prefix: v
