package:
  name: goreleaser-1.18
  version: 1.18.2
  epoch: 7
  description: Deliver Go binaries as fast and easily as possible
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - goreleaser=1.18.999 # This should be goreleaser=${{package.version}}-${{package.epoch}}

environment:
  contents:
    packages:
      - git

pipeline:
  - uses: go/install
    with:
      package: github.com/goreleaser/goreleaser@v${{package.version}}

update:
  enabled: true
  github:
    identifier: goreleaser/goreleaser
    strip-prefix: v
    tag-filter: v1.18
