package:
  name: govulncheck
  version: 1.0.2
  epoch: 3
  description: Go Vulnerability Management
  copyright:
    - license: BSD-3-Clause

pipeline:
  - uses: git-checkout
    with:
      repository: https://go.googlesource.com/vuln
      tag: v${{package.version}}
      expected-commit: e313109e39439a94eee0185a019b909e74ba6665

  - uses: go/build
    with:
      output: govulncheck
      packages: ./cmd/govulncheck

# This isn't on GitHub and it's not in release-monitor
update:
  enabled: false
