package:
  name: grafana-operator
  version: 5.7.0
  epoch: 0
  description: An operator for Grafana that installs and manages Grafana instances, Dashboards and Datasources through Kubernetes/OpenShift CRs
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana-operator/grafana-operator
      tag: v${{package.version}}
      expected-commit: ffccae108cdadf8ed8dc0db3b7574392c319dadd

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: grafana-operator

  - uses: strip

update:
  enabled: true
  github:
    identifier: grafana-operator/grafana-operator
    strip-prefix: v
