package:
  name: grafana-10.4
  version: 10.4.1
  epoch: 1
  description: The open and composable observability and data visualization platform.
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - bash
    provides:
      - grafana=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - findutils
      - go
      - nodejs-18
      - posix-libc-utils
      - py3-setuptools
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d3ce857c0eb86f571ffa993a9cd8493b6f47b630
      repository: https://github.com/grafana/grafana
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 google.golang.org/protobuf@v1.33.0

  - runs: |
      yarn install
      yarn run build
      yarn run plugins:build-bundled

      # Bump the version of wire used, the old version panics with new Go
      # https://github.com/google/wire/issues/400
      sed -i "s/v0.5.0/v0.6.0/g" .bingo/wire.mod

      make build

      mkdir -p ${{targets.destdir}}/usr/bin
      mv ./bin/linux-*/* ${{targets.destdir}}/usr/bin/

  - name: package
    runs: |
      mkdir -p ${{targets.destdir}}/usr/share/grafana/plugins-bundled
      mkdir -p ${{targets.destdir}}/usr/share/grafana/scripts
      mkdir -p ${{targets.destdir}}/usr/share/grafana/bin

      mv ./conf ${{targets.destdir}}/usr/share/grafana/
      mv ./plugins-bundled/internal ${{targets.destdir}}/usr/share/grafana/plugins-bundled/
      mv ./public ${{targets.destdir}}/usr/share/grafana/
      mv ./scripts/*.sh ${{targets.destdir}}/usr/share/grafana/scripts/

      mkdir -p ${{targets.destdir}}/etc/grafana/
      cp ${{targets.destdir}}/usr/share/grafana/conf/sample.ini ${{targets.destdir}}/etc/grafana/grafana.ini

subpackages:
  - name: grafana-oci-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/grafana
          mv ./packaging/docker/run.sh ${{targets.subpkgdir}}/opt/grafana/

update:
  enabled: true
  github:
    identifier: grafana/grafana
    strip-prefix: v
    tag-filter-prefix: v10.4.
