package:
  name: grep
  version: "3.11"
  epoch: 1
  description: "GNU grep implementation"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - pcre2-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/grep/grep-${{package.version}}.tar.gz
      expected-sha256: 1f31014953e71c3cddcedb97692ad7620cb9d6d04fbdc19e0d8dd836f87622bb

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1251

test:
  pipeline:
    - runs: |
        grep --version
