package:
  name: harbor-scanner-trivy
  version: 0.30.23
  epoch: 0
  description: Use Trivy as a plug-in vulnerability scanner in the Harbor registry
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b3f324e0b021a036b89f92331763add1080aa723
      repository: https://github.com/aquasecurity/harbor-scanner-trivy
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/scanner-trivy
      output: scanner-trivy

  - uses: strip

test:
  pipeline:
    - runs: |
        # No version or help info
        scanner-trivy & sleep 3; kill $!

update:
  enabled: true
  github:
    identifier: aquasecurity/harbor-scanner-trivy
    strip-prefix: v
