package:
  name: helix
  version: 24.03
  epoch: 0
  description: "A post-modern modal text editor."
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/helix-editor/helix
      expected-commit: 2cadec0b1182332338a5a1cc3062776f834d8835
      tag: ${{package.version}}

  - name: Configure and build
    runs: |
      cargo install --path helix-term --locked
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/hx ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: helix-editor/helix
