package:
  name: influxd
  version: 2.7.5
  epoch: 3
  description: Scalable datastore for metrics, events, and real-time analytics
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - curl
      - git
      - go
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influxdb
      tag: v${{package.version}}
      expected-commit: 09a9607fd9fe017cae589610364017b1939ae9a2
      destination: influxdb

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.58.3 golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0
      modroot: influxdb

  - runs: |
      cd influxdb
      unset LDFLAGS

      make generate-web-assets

      # There's currently a #![deny(warnings)] section in a crate that fails to build with Rust 1.72
      export RUSTFLAGS="$RUSTFLAGS --cap-lints=warn"
      make influxd
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/linux/influxd ${{targets.destdir}}/usr/bin

      mkdir -p ${{targets.destdir}}/etc/defaults/influxdb2/
      mv ../default-config.yml ${{targets.destdir}}/etc/defaults/influxdb2/config.yml

  - uses: strip

subpackages:
  - name: influxd-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
    dependencies:
      runtime:
        - busybox
        - bash
        - yq

update:
  enabled: true
  github:
    identifier: influxdata/influxdb
    strip-prefix: v
