package:
  name: influx
  version: 2.7.3
  epoch: 11
  description: CLI for managing resources in InfluxDB v2
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influx-cli
      tag: v${{package.version}}
      expected-commit: 8b962c7e750559f784dd2028633e5f324d4a8da2

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter
      unset LDFLAGS
      make
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/linux/$(go env GOARCH)/influx ${{targets.destdir}}/usr/bin/influx

  - uses: strip

update:
  enabled: true
  github:
    identifier: influxdata/influx-cli
    strip-prefix: v
