package:
  name: istio-cni-1.21
  version: 1.21.0
  epoch: 2
  description: Istio Container Network Interface
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-cni=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 2ca3e986a683fbdb82dffcd7b2e8d02076a42468

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 github.com/lestrrat-go/jwx@v1.2.29

  - uses: go/build
    with:
      packages: ./cni/cmd/istio-cni
      output: istio-cni

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # See https://github.com/istio/istio/blob/1.20.0/cni/deployments/kubernetes/Dockerfile.install-cni
          mkdir -p ${{targets.subpkgdir}}/opt/cni/bin
          ln -sf /usr/bin/istio-cni ${{targets.subpkgdir}}/opt/cni/bin/istio-cni
    dependencies:
      provides:
        - istio-cni-compat=${{package.full-version}}

  - name: istio-install-cni-1.21
    pipeline:
      - uses: go/build
        with:
          packages: ./cni/cmd/install-cni
          output: install-cni
      - uses: strip
    dependencies:
      provides:
        - istio-install-cni=${{package.full-version}}

  - name: istio-install-cni-1.21-compat
    pipeline:
      - runs: |
          # See https://github.com/istio/istio/blob/1.20.0/cni/deployments/kubernetes/Dockerfile.install-cni
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/install-cni ${{targets.subpkgdir}}/usr/local/bin/install-cni
    dependencies:
      provides:
        - istio-install-cni-compat=${{package.full-version}}

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.21.
    use-tag: true
