package:
  name: istio-operator-1.21
  version: 1.21.0
  epoch: 2
  description: Istio operator provides user friendly options to operate the Istio service mesh
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-operator=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 2ca3e986a683fbdb82dffcd7b2e8d02076a42468

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 github.com/lestrrat-go/jwx@v1.2.29

  - uses: go/build
    with:
      packages: ./operator/cmd/operator
      output: operator

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio
      mv manifests ${{targets.destdir}}/var/lib/istio/manifests

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '-rc'
    - '-beta'
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.21.
    use-tag: true
