package:
  name: istio-pilot-discovery-1.21
  version: 1.21.0
  epoch: 3
  description: Istio controller
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - istio-pilot-discovery=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/istio/istio
      tag: ${{package.version}}
      expected-commit: 2ca3e986a683fbdb82dffcd7b2e8d02076a42468

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 github.com/lestrrat-go/jwx@v1.2.29 github.com/docker/docker@v24.0.9

  - uses: go/build
    with:
      packages: ./pilot/cmd/pilot-discovery
      output: pilot-discovery
      # istio default ldflags: https://github.com/istio/istio/blob/master/Makefile.core.mk#L210
      ldflags: "-extldflags -static -s -w"
      # istio default stanard tags: https://github.com/istio/istio/blob/master/Makefile.core.mk#L242
      tags: "disable_pgv,vtprotobuf"

  - runs: |
      mkdir -p ${{targets.destdir}}/var/lib/istio/envoy
      cp ./tools/packaging/common/envoy_bootstrap.json \
        ${{targets.destdir}}/var/lib/istio/envoy/envoy_bootstrap_tmpl.json
      cp ./tools/packaging/common/gcp_envoy_bootstrap.json \
        ${{targets.destdir}}/var/lib/istio/envoy/gcp_envoy_bootstrap_tmpl.json

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # link /usr/local/bin/pilot-discovery -> /usr/bin/pilot-discovery to match
          # what the Istio Helm charts may expect.
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/pilot-discovery ${{targets.subpkgdir}}/usr/local/bin/pilot-discovery
    dependencies:
      provides:
        - istio-discovery-compat=${{package.full-version}}

update:
  enabled: true
  ignore-regex-patterns:
    - "-rc"
    - "-beta"
  github:
    identifier: istio/istio
    tag-filter-prefix: 1.21.
    use-tag: true
