package:
  name: jellyfin
  version: 10.8.13
  epoch: 0
  description: The Free Software Media System
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - aspnet-6-runtime
      - dotnet-6
      - ffmpeg

environment:
  contents:
    packages:
      - aspnet-6-runtime
      - busybox
      - dotnet-6-sdk
      - ffmpeg

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jellyfin/jellyfin
      tag: v${{package.version}}
      expected-commit: e93d03d8cbff2122d7296f477604146f64758a73

  - uses: patch
    with:
      patches: |
        GHSA-j7hp-h8jx-5ppr.patch \
        GHSA-qrmm-w75w-3wpx.patch

  - runs: |
      # Set runtime arch
      if [[ "${{build.arch}}" == "aarch64" ]]; then
        runtime_arch="arm64"
      elif [[ "${{build.arch}}" == "x86_64" ]]; then
        runtime_arch="x64"
      fi

      dotnet publish \
        --configuration Release Jellyfin.Server \
        --no-self-contained \
        --output publish \
        --runtime linux-$runtime_arch \
        -p:DebugSymbols=false \
        -p:DebugType=none

      mkdir -p "${{targets.destdir}}"/usr/lib
      cp -dr publish "${{targets.destdir}}"/usr/lib/jellyfin

      mkdir -p "${{targets.destdir}}"/usr/bin
      ln -s /usr/lib/jellyfin/jellyfin "${{targets.destdir}}"/usr/bin/jellyfin

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '.*alpha.*'
    - '.*beta.*'
    - '.*rc.*'
  github:
    identifier: jellyfin/jellyfin
    use-tag: true
    strip-prefix: v
