package:
  name: jenkins
  version: "2.449"
  epoch: 0
  description: Open-source CI/CD application.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      # Jenkins requires both bash and busybox.
      - bash
      - busybox
      - coreutils
      - glibc-locale-en
      # The entrypoint script is pulled from a separate repo, which we'e packaged.
      - jenkins-entrypoint
      - ttf-dejavu
      - tzdata

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - git
      - glibc-locale-en
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - openssh-client
      - patch
      - tini
      - ttf-dejavu
      - tzdata

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/jenkins
      tag: jenkins-${{package.version}}
      expected-commit: 8c5b7ec3e85512ac115e77bfedb6325e272ffbb7

  - uses: patch
    with:
      patches: ignoreArchiveNotReadableTest.patch

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      export LANG=en_US.UTF-8

      export MAVEN_OPTS="-DforkCount=2"

      # tests take ~1.5 hours to run and have passed 100% since the initial addition of Jenkins, let's skip them and save time + resources
      mvn install -DskipTests=true

      mkdir -p ${{targets.destdir}}/usr/share/java/jenkins
      mv war/target/jenkins.war ${{targets.destdir}}/usr/share/java/jenkins/

subpackages:
  # The Jenkins entrypoint script expects directories to exist, and the .war file
  # under a different location.
  - name: "jenkins-compat"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/var/jenkins_home
          mkdir -p "${{targets.subpkgdir}}"/usr/share/jenkins
          mkdir -p "${{targets.subpkgdir}}"/usr/share/jenkins/ref
          ln -s /usr/share/java/jenkins/jenkins.war "${{targets.subpkgdir}}"/usr/share/jenkins/jenkins.war

update:
  enabled: true
  github:
    identifier: jenkinsci/jenkins
    strip-prefix: jenkins-
  ignore-regex-patterns:
    - '.*-rc'

test:
  environment:
    contents:
      packages:
        - openjdk-17
        - openjdk-17-default-jvm
        - jenkins-compat
        - jenkins-entrypoint
  pipeline:
    - runs: |
        cleanup() {
          kill $JENKINS_PID
        }
        trap cleanup EXIT

        echo "Launching Jenkins and performing log validation..."
        jenkins.sh > jenkins.log 2>&1 &
        JENKINS_PID=$!
        TIMEOUT=60

        while ! grep -q "Jenkins is fully up and running" jenkins.log && [ $TIMEOUT -gt 0 ]; do
          sleep 5
          TIMEOUT=$((TIMEOUT-1))
        done

        if [ $TIMEOUT -eq 0 ]; then
          echo "Attempted to launch Jenkins in melange test, but log validation failed."
          exit 1
        fi

        if grep -Eq "FAIL|FAILURE|ERROR" jenkins.log; then
          echo "Successfully launched Jenkins, but errors where found in the logs."
          exit 1
        fi
