package:
  name: jitterentropy-rngd
  version: 1.2.8
  epoch: 0
  description: Jitterentropy RNGd
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smuellerDD/jitterentropy-rngd
      expected-commit: ade61a1548a2754d38f0c0c18f52b80d9a599420
      tag: v${{package.version}}

  - runs: |
      # jitterentropy must *not* be compiled with optimizations
      export CFLAGS="$CFLAGS -O0"
      export CPPFLAGS="$CPPFLAGS -O0"
      export CXXFLAGS="$CXXFLAGS -O0"
      make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: smuellerDD/jitterentropy-rngd
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        jitterentropy-rngd --version 2>&1 | grep ${{package.version}}
