package:
  name: k8sgpt
  version: 0.3.29
  epoch: 1
  description: Giving Kubernetes Superpowers to everyone
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8sgpt-ai/k8sgpt
      tag: v${{package.version}}
      expected-commit: 5db4bc28a7c3cc485865b17633e96f497c760f87

  - uses: go/bump
    with:
      deps: github.com/mittwald/go-helm-client@v0.12.7 helm.sh/helm/v3@v3.14.2 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - runs: |
      make tidy
      make build
      install -Dm755 ./bin/k8sgpt "${{targets.destdir}}/usr/bin/k8sgpt"

  - uses: strip

update:
  enabled: true
  github:
    identifier: k8sgpt-ai/k8sgpt
    strip-prefix: v
