package:
  name: k8ssandra-operator
  version: 1.14.0
  epoch: 0
  description: The Kubernetes operator for K8ssandra
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/k8ssandra-operator
      tag: v${{package.version}}
      expected-commit: ac9e5f19eb2c22bd6cf91a0f6411f2da6c6fd682

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.58.3 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: manager
      ldflags: |
        -X "main.version=${{package.version}}"
        -X "main.commit=$(git rev-parse HEAD)"
        -X "main.date=$(date +%FT%T)"

  - uses: strip

subpackages:
  - name: "${{package.name}}-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: k8ssandra/k8ssandra-operator
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - k8ssandra-operator-compat
  pipeline:
    - runs: |
        /manager --help
        /manager 2>&1 | grep -qi "try setting KUBERNETES_MASTER environment variable"
