package:
  name: kafka
  # When bumping check to see if the CVE mitigation can be removed.
  version: 3.7.0
  epoch: 2
  description: Apache Kafka is a distributed event streaming platformm
  copyright:
    - paths:
        - "*"
      attestation:
      license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-11-jre

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - gradle
      - openjdk-11
      - sbt

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/kafka
      tag: ${{package.version}}
      expected-commit: 2ae524ed625438c5fee89e78648bd73e64a3ada0

  - uses: patch
    with:
      patches: CVE-2024-23944.patch

  - runs: |
      export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

      gradle clean releaseTarGz

      tar -xf core/build/distributions/kafka_2.13-${{package.version}}.tgz

      mkdir -p ${{targets.destdir}}/usr/lib/kafka/logs

      mv kafka_2.13-${{package.version}}/bin ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/libs ${{targets.destdir}}/usr/lib/kafka
      mv kafka_2.13-${{package.version}}/config ${{targets.destdir}}/usr/lib/kafka

      # Clean up windows
      rm -rf ${{targets.destdir}}/usr/lib/kafka/bin/*.bat

subpackages:
  - name: kafka-bitnami-compat
    description: "compat package with bitnami/kafka image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: kafka
          version-path: 3.6/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/kafka/
          ln -s /usr/lib/kafka/bin ${{targets.subpkgdir}}/opt/bitnami/kafka/bin
          ln -s /usr/lib/kafka/libs ${{targets.subpkgdir}}/opt/bitnami/kafka/libs
          ln -s /usr/lib/kafka/config ${{targets.subpkgdir}}/opt/bitnami/kafka/config
          ln -s /usr/lib/kafka/logs ${{targets.subpkgdir}}/opt/bitnami/kafka/logs

update:
  enabled: true
  github:
    identifier: apache/kafka
    use-tag: true
