package:
  name: kargo
  version: 0.5.0
  epoch: 0
  description: Application lifecycle orchestration
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - node-gyp
      - nodejs
      - pnpm
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/akuity/kargo
      tag: v${{package.version}}
      expected-commit: 6d25124a261f957054045880e5c0f2a193b217f9

  - uses: go/build
    with:
      packages: ./cmd/controlplane
      output: kargo
      ldflags: "-w -s -X github.com/akuity/kargo/internal/version.version=${{package.version}} -X github.com/akuity/kargo/internal/version.gitCommit=$(git rev-parse HEAD)"

  - runs: |
      cd ui
      pnpm install
      NODE_ENV='production' pnpm run build

      mkdir -p ${{targets.destdir}}/usr/share/kargo/ui

      mv build ${{targets.destdir}}/usr/share/kargo/ui

  - uses: strip

subpackages:
  - name: kargo-oci-compat
    description: OCI compatibility layer
    dependencies:
      runtime:
        - kargo
        - grpc-health-probe
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/kargo ${{targets.subpkgdir}}/usr/local/bin/kargo
          ln -sf /usr/share/kargo/ui ${{targets.subpkgdir}}/
          ln -sf /usr/bin/grpc-health-probe ${{targets.subpkgdir}}/usr/local/bin/grpc_health_probe

update:
  enabled: true
  ignore-regex-patterns:
    - 'rc*'
    - 'alpha'
  github:
    identifier: akuity/kargo
    strip-prefix: v
    use-tag: true
    tag-filter: v
