package:
  name: keycloak
  version: 24.0.2
  epoch: 0
  description: Open Source Identity and Access Management For Modern Applications and Services
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash # Keycloak helper scripts require bash, aren't compatible with busybox.
      - openjdk-17-default-jvm

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - nodejs-18
      - openjdk-17
      - openjdk-17-default-jvm
      - wolfi-base
      - wolfi-baselayout
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/keycloak/keycloak
      tag: ${{package.version}}
      expected-commit: 6a5783e9d538a1e67512fe43abe7b15ca6eed5c2

  - runs: |
      # Keycloak installation. Note we use the maven wrapper as configured in
      # the source repo to build - ensures the correct maven version for
      # building the project, preventing issues such as CI hangs.

      # Build and install child module (keycloak-js-adapter-jar)
      ./mvnw clean install -Dnode.version=$(node --version) -f adapters/oidc/js/pom.xml -q

      # Build keycloak-server. Depends on `keycloak-js-adapter-jar`.
      ./mvnw clean install -DskipTests=true -Dnode.version=$(node --version) -Pdistribution -q

      mkdir -p ${{targets.destdir}}/usr/share/java
      unzip -d ${{targets.destdir}}/usr/share/java quarkus/dist/target/keycloak-*.zip
      mv ${{targets.destdir}}/usr/share/java/keycloak-* ${{targets.destdir}}/usr/share/java/keycloak

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in kc.sh kcadm.sh kcreg.sh; do
        ln -sf /usr/share/java/keycloak/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

update:
  # The upstream repos releases contains a 'nightly' release. Which we want to
  # exclude from discovery.
  ignore-regex-patterns:
    - '.*nightly.*'
  enabled: true
  github:
    identifier: keycloak/keycloak
