package:
  name: kind
  version: 0.22.0
  epoch: 3
  description: Kubernetes IN Docker - local clusters for testing Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/kind
      tag: v${{package.version}}
      expected-commit: 2b248e7df157d4f1a44ecea114be3d58c9232930

  - uses: go/bump
    with:
      deps: golang.org/x/sys@v0.0.0-20220412211240-33da011f77ad

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp ./bin/kind ${{targets.destdir}}/usr/bin/kind

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/kind
    strip-prefix: v
