package:
  name: kor
  version: 0.3.7
  epoch: 1
  description: A Golang Tool to discover unused Kubernetes Resources
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yonahd/kor
      tag: v${{package.version}}
      expected-commit: 06a2b4e5e0eed2065c2273fd90f4f434610f5fb3

  - uses: go/build
    with:
      modroot: .
      packages: .
      ldflags: -w
      output: kor

  - uses: strip

update:
  enabled: true
  github:
    identifier: yonahd/kor
    strip-prefix: v
