package:
  name: kubernetes-csi-node-driver-registrar-2.10
  version: 2.10.0
  epoch: 1
  description: Sidecar container that registers a CSI driver with the kubelet using the kubelet plugin registration mechanism.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-node-driver-registrar=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ed043c200fb29960df0586e55d3a166acb4f4977
      repository: https://github.com/kubernetes-csi/node-driver-registrar
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4

  - uses: go/build
    with:
      ldflags: -s -w -X main.version=v${{package.version}} -extldflags '-static'
      output: csi-node-driver-registrar
      packages: ./cmd/csi-node-driver-registrar
      vendor: "true"

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/csi-node-driver-registrar ${{targets.subpkgdir}}/csi-node-driver-registrar
    dependencies:
      provides:
        - kubernetes-csi-node-driver-registrar-compat=${{package.full-version}}
    description: Compatibility package to place binaries in the location expected by upstream helm charts

update:
  enabled: true
  github:
    identifier: kubernetes-csi/node-driver-registrar
    strip-prefix: v
    tag-filter: v2.10.
