package:
  name: kubeflow-pipelines-visualization-server
  version: 2.1.0
  epoch: 0
  description: Machine Learning Pipelines for Kubeflow
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64 # Since tensorflow-data-validation is not available for aaarch64 yet
  dependencies:
    runtime:
      - py3.10-google-cloud-sdk
      - python-3.10

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3.10-crcmod
      - py3.10-pip
      - python-3.10
      - python-3.10-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubeflow/pipelines
      tag: ${{package.version}}
      expected-commit: f328f0b588c35cdf1e5b31638fbe3596b2f38413

  - uses: patch
    with:
      patches: 0001-Bump-dependencies.patch

  - runs: |
      ln -sf /usr/bin/python3.10 /usr/bin/python3
      mkdir -p ${{targets.destdir}}/usr/share/app
      cp -r backend/src/apiserver/visualization/* ${{targets.destdir}}/usr/share/app/
      cd ${{targets.destdir}}/usr/share/app/

      sed -i 's/tensorflow==/#tensorflow==/g' requirements.txt

      pip install --root=${{targets.destdir}} --prefix=/usr -r requirements.txt
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

      # "collections" is deprecated in Python 3.10, use "collections.abc" instead
      sed -i 's/collections/collections.abc/g' ${{targets.destdir}}/usr/lib/python3.10/site-packages/gcsfs/mapping.py

      # CVE-2023-47248, GHSA-5wvp-7f3h-6wmm
      pip install pyarrow-hotfix
      sed -i '1 i\import pyarrow_hotfix' server.py

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk-'
  github:
    identifier: kubeflow/pipelines
