package:
  name: kubernetes-csi-external-resizer-1.10
  version: 1.10.1
  epoch: 2
  description: Sidecar container that watches Kubernetes PersistentVolumeClaims objects and triggers controller side expansion operation against a CSI endpoint
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - kubernetes-csi-external-resizer=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-resizer
      tag: v${{package.version}}
      expected-commit: be82396ea8ec3918feedd5b41d9b82904f1c71d7

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-resizer ${{targets.destdir}}/usr/bin/csi-resizer

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-resizer
    strip-prefix: v
    tag-filter: v1.10.

test:
  pipeline:
    - runs: csi-resizer --version
