package:
  name: kubewatch
  version: 2.5.0
  epoch: 12
  description: Watch k8s events and trigger Handlers
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7ba4d562b00738e060e895426b7c031aaffdba83
      repository: https://github.com/robusta-dev/kubewatch
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 gopkg.in/yaml.v3@v3.0.1 golang.org/x/net@v0.17.0 google.golang.org/protobuf@v1.33.0

  - runs: |
      make build
      install -Dm755 kubewatch "${{targets.destdir}}"/usr/bin/kubewatch

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: robusta-dev/kubewatch
    strip-prefix: v
