package:
  name: kubernetes-csi-external-snapshotter
  version: 7.0.1
  epoch: 3
  description: Sidecar container that watches Kubernetes Snapshot CRD objects and triggers CreateSnapshot/DeleteSnapshot against a CSI endpoint
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-snapshotter
      tag: v${{package.version}}
      expected-commit: 4be06ff1e2e23599db16cdc52b8fb0ba5e7ccc23

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/csi-snapshotter ${{targets.destdir}}/usr/bin/csi-snapshotter

  - uses: strip

subpackages:
  - name: kubernetes-csi-external-snapshot-controller
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/bin
          install -Dm755 ./bin/snapshot-controller ${{targets.subpkgdir}}/usr/bin/snapshot-controller

  - name: kubernetes-csi-external-snapshot-validation-webhook
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/bin
          install -Dm755 ./bin/snapshot-validation-webhook ${{targets.subpkgdir}}/usr/bin/snapshot-validation-webhook

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-snapshotter
    strip-prefix: v
    tag-filter: v
