package:
  name: kuberay-operator
  version: 1.0.0
  epoch: 4
  description: A toolkit to run Ray applications on Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1add258fcfd5c83319428355c0af4dde60ea9047
      repository: https://github.com/ray-project/kuberay.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: ray-operator

  - uses: go/build
    with:
      modroot: ray-operator
      packages: .
      output: manager
      ldflags: -X 'main._buildTime_=$(date "+%F %T")' -X 'main._commitId_=$(git rev-parse HEAD)'

  - uses: strip

subpackages:
  - name: kuberay-operator-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the kuberay-operator binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: ray-project/kuberay
    strip-prefix: v
    tag-filter: v1.0.0

test:
  pipeline:
    - runs: |
        /usr/bin/manager --version
