package:
  name: kubebuilder
  version: 3.14.1
  epoch: 1
  description: SDK for building Kubernetes APIs using CRDs
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/kubebuilder
      tag: v${{package.version}}
      expected-commit: cc338d729c2a578ae491860e3eb71e63864b1390

  - uses: go/build
    with:
      packages: ./cmd
      output: kubebuilder
      ldflags: |
        -s -w
        -X main.kubeBuilderVersion=$(git describe --tags --dirty --broken)
        -X main.goos=$(go env GOOS)
        -X main.goarch=$(go env GOARCH)
        -X main.gitCommit=$(git rev-parse HEAD)
        -X main.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - tools-*
    - release-*
  github:
    identifier: kubernetes-sigs/kubebuilder
    strip-prefix: v
    use-tag: true
