package:
  name: kustomize
  version: 5.4.1
  epoch: 0
  description: Customization of kubernetes YAML configurations
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/kubernetes-sigs/kustomize/archive/refs/tags/kustomize/v${{package.version}}.tar.gz
      expected-sha256: dfdab5d0a22cfb5825ecfeee8ca96816d55a2989f015354b970ada743956a023

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: kustomize

  - uses: go/build
    with:
      packages: ./kustomize
      output: kustomize
      ldflags: -s -w -X sigs.k8s.io/kustomize/api/provenance.version=kustomize/${{package.version}} -X 'sigs.k8s.io/kustomize/api/provenance.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')'

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/kustomize
    strip-prefix: kustomize/v
    tag-filter: kustomize/v
    use-tag: true
