package:
  name: kwok
  version: 0.5.1
  epoch: 2
  description: Kubernetes WithOut Kubelet - Simulates thousands of Nodes and Clusters.
  copyright:
    - license: BSD-3-Clause

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/kwok
      tag: v${{package.version}}
      expected-commit: b293e021941c8a6db3459d6da9741be2f44f274f

  - uses: go/build
    with:
      packages: ./cmd/kwok
      repository: https://github.com/kubernetes-sigs/kwok
      output: kwok

  - uses: strip

subpackages:
  - name: "kwokctl"
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/kwokctl
          repository: https://github.com/kubernetes-sigs/kwok
          output: kwokctl
      - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/kwok
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - kubectl-default
        - kwokctl
        - kubernetes
        - etcd
  pipeline:
    - runs: |
        #!/bin/sh

        # ensure we can create a cluster using our own components instead of
        # fetching from the internet
        kwokctl create cluster --runtime binary \
          --kube-apiserver-binary="/usr/bin/kube-apiserver" \
          --kube-controller-manager-binary="/usr/bin/kube-controller-manager" \
          --kube-scheduler-binary="/usr/bin/kube-scheduler" \
          --kwok-controller-binary="/usr/bin/kwok" \
          --etcd-binary="/usr/bin/etcd"

        kwokctl scale node --replicas 2

        # Basic check that we have nodes
        kubectl wait --for=condition=Ready nodes --all

        # Basic check that the deployment controller creates a pod
        kubectl create deploy foo --image=foo
        sleep 5
        kubectl wait --for=condition=Ready po --all

        kwokctl delete cluster
