package:
  name: kyverno-policy-reporter-ui
  version: 1.9.2
  epoch: 4
  description: Policy Reporter UI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - go
      - node-gyp
      - nodejs-18
      - npm
      - openssl
      - python-3.11
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kyverno/policy-reporter-ui
      tag: v${{package.version}}
      expected-commit: 5b03edd71958dca47dd13bca7de95294a332817c

  - runs: |
      export NODE_OPTIONS=--openssl-legacy-provider
      npm install
      npm run generate

      mkdir -p ${{targets.destdir}}/app
      cp -R ./dist ${{targets.destdir}}/app/dist

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: server

  - uses: go/build
    with:
      modroot: server
      packages: .
      # Mitigate CVE-2023-39325, CVE-2023-44487
      output: policyreporter-ui
      ldflags: -w

  - uses: strip

subpackages:
  - name: kyverno-policy-reporter-ui-compat
    description: compatibility symlinks package for policyreporter-ui Dockerfile
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /app/
          mkdir -p ${{targets.subpkgdir}}/app
          ln -sf /usr/bin/policyreporter-ui ${{targets.subpkgdir}}/app/policyreporter-ui

update:
  enabled: true
  # There are tags with alpha and helm charts that break our update block.
  ignore-regex-patterns:
    - 'alpha'
    - 'policy-reporter-ui-chart-'
  github:
    identifier: kyverno/policy-reporter-ui
    use-tag: true
    strip-prefix: v
