package:
  name: lazygit
  version: 0.41.0
  epoch: 1
  description: simple terminal UI for git commands
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jesseduffield/lazygit
      tag: v${{package.version}}
      expected-commit: 3675570a391b1a49ddd198b4c7e71e17701d4404

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 golang.org/x/crypto@v0.17.0

  - uses: go/build
    with:
      packages: .
      repository: https://github.com/jesseduffield/lazygit
      ldflags: |
        -s -w
        -X main.version=${{package.version}}
        -X main.commit=$(git rev-parse HEAD)
        -X main.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        -X main.buildSource=wolfiRelease
      output: lazygit

  - uses: strip

update:
  enabled: true
  github:
    identifier: jesseduffield/lazygit
    strip-prefix: v

test:
  pipeline:
    - runs: |
        lazygit --version
