package:
  name: lean4
  version: 4.7.0
  epoch: 0
  description: "Secure Reliable Transport (SRT)"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gmp-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/leanprover/lean4
      tag: v${{package.version}}
      expected-commit: 6fce8f7d5cd18a4419bca7fd51780c71c9b1cc5a

  - runs: |
      # This doesn't work with Ninja so we can't use our default pipelines.
      cmake -B build -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=MinSizeRel .
      make -j$(nproc) -C build
      DESTDIR=${{targets.destdir}} make install -C build

  - uses: strip

subpackages:
  - name: "lean4-static"
    description: "lean4 static libraries"
    pipeline:
      - uses: split/static

  - name: "lean4-dev"
    description: "lean4 development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: leanprover/lean4
    use-tag: true
    strip-prefix: v
    tag-filter: v
