package:
  name: libarchive
  version: 3.7.3
  epoch: 0
  description: "multi-format archive and compression library"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - acl-dev
      - attr-dev
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - lz4-dev
      - openssl-dev
      - wolfi-base
      - xz-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: http://libarchive.org/downloads/libarchive-${{package.version}}.tar.xz
      expected-sha256: 63e7a7174638fc7d6b79b4c8b0ad954e0f4f45abe7239c1ecb200232aa9a43d2

  - uses: autoconf/configure
    with:
      opts: --without-xml2

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libarchive-doc"
    description: "libarchive documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: "libarchive-dev"
    description: "libarchive development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - bzip2-dev
        - lz4-dev
        - xz-dev
        - zlib-dev
        - zstd-dev

  - name: "libarchive-tools"
    description: "bsdtar and bsdcpio programs from libarchive"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/bsd* "${{targets.subpkgdir}}"/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 1558
