package:
  name: libevent
  version: 2.1.12
  epoch: 0
  description: An event notification library
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - python3
      - python3-dev
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 92e6de1be9ec176428fd2367677e61ceffc2ee1cb119035037a27d346b0403bb
      uri: https://github.com/libevent/libevent/releases/download/release-${{package.version}}-stable/libevent-${{package.version}}-stable.tar.gz
  - runs: |
      sed -i '1s|^#!/usr/bin/env python$|#!/usr/bin/python3|' event_rpcgen.py
      # help provides tracing work out correctly
      sed -i -e "s/@VERSION@/${{package.version}}-r${{package.epoch}}/" *.pc.in

  - uses: autoconf/configure
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: libevent-static
    description: libevent static library
    pipeline:
      - uses: split/static
  - name: libevent-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libevent
        - python3
    description: libevent dev
