package:
  name: libgit2
  version: 1.8.0
  epoch: 0
  description: "A cross-platform, linkable library implementation of Git that you can use in your application."
  copyright:
    - license: GPL-2.0-only WITH GCC-exception-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - http-parser-dev
      - libssh2-dev
      - openssl-dev
      - pcre2-dev
      - pkgconf
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/libgit2/libgit2/archive/v${{package.version}}.tar.gz
      expected-sha256: 9e1d6a880d59026b675456fbb1593c724c68d73c34c0d214d6eb848e9bbd8ae4

  - name: Configure
    runs: |
      CC=gcc CXX=g++ cmake -B build-shared -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DUSE_HTTP_PARSER=system \
        -DUSE_HTTPS=OpenSSL \
        -DREGEX_BACKEND=pcre2 \
        -DUSE_BUNDLED_ZLIB=OFF \
        -DUSE_SSH=ON \
        -DBUILD_TESTS=OFF
      cmake --build build-shared
      DESTDIR=${{targets.destdir}} cmake --install build-shared

      CC=gcc CXX=g++ cmake -B build-static -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DUSE_HTTPS=OpenSSL \
        -DREGEX_BACKEND=pcre2 \
        -DUSE_BUNDLED_ZLIB=OFF \
        -DUSE_SSH=ON \
        -DBUILD_TESTS=OFF \
        -DBUILD_SHARED_LIBS=OFF
      cmake --build build-static
      DESTDIR=${{targets.destdir}} cmake --install build-static

subpackages:
  - name: "libgit2-dev"
    description: "headers for libgit2"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libgit2

  - name: "libgit2-static"
    description: "libgit2 static library"
    pipeline:
      - uses: split/static

update:
  enabled: true
  release-monitor:
    identifier: 1627
