package:
  name: libhtp
  version: 0.5.47
  epoch: 0
  description: LibHTP is a security-aware parser for the HTTP protocol and the related bits and pieces
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - glibc-iconv
      - libtool
      - m4
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9792ee19e06352f25204af06cd47b53818b572ef351665eb128259363d1a12fb
      uri: https://github.com/OISF/libhtp/archive/refs/tags/${{package.version}}.tar.gz

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libhtp-static
    pipeline:
      - uses: split/static
    description: libhtp static

  - name: libhtp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libhtp
    description: libhtp dev

  - name: libhtp-doc
    pipeline:
      - uses: split/manpages
    description: libhtp manpages

update:
  enabled: true
  release-monitor:
    identifier: 1632
