package:
  name: libusb
  version: 1.0.26
  epoch: 0
  description: Library that enables userspace access to USB devices
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: LGPL-2.0-or-later
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - linux-headers
      - libatomic
pipeline:
  - uses: fetch
    with:
      expected-sha256: 12ce7a61fc9854d1d2a1ffe095f7b5fac19ddba095c259e6067a46500381b5a5
      uri: https://github.com/libusb/libusb/releases/download/v${{package.version}}/libusb-${{package.version}}.tar.bz2
  - uses: autoconf/configure
    with:
      opts: |
        --disable-udev \
        --enable-static
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: libusb-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libusb
    description: libusb dev
