package:
  name: libxt
  version: 1.2.1
  epoch: 0
  description: X11 toolkit intrinsics library
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: custom
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libsm-dev
      - libice-dev
      - libx11-dev
      - util-macros
      - xorgproto
pipeline:
  - uses: fetch
    with:
      expected-sha256: 679cc08f1646dbd27f5e48ffe8dd49406102937109130caab02ca32c083a3d60
      uri: https://www.x.org/releases/individual/lib/libXt-${{package.version}}.tar.bz2
  - uses: autoconf/configure
    with:
      opts: --disable-static
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
subpackages:
  - name: libxt-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxt
        - libsm-dev
    description: libxt dev
  - name: libxt-doc
    pipeline:
      - uses: split/manpages
    description: libxt manpages
