package:
  name: libxmu
  version: 1.2.0
  epoch: 0
  description: X11 miscellaneous micro-utility library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libice-dev
      - libsm-dev
      - libx11-dev
      - libxext-dev
      - libxt-dev
      - util-linux-dev
      - util-macros
      - xmlto

pipeline:
  - uses: fetch
    with:
      expected-sha256: 072026fe305889538e5b0c5f9cbcd623d2c27d2b85dcd37ca369ab21590b6963
      uri: https://www.x.org/releases/individual/lib/libXmu-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --sysconfdir=/etc \
        --without-fop

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxmu-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxmu
        - libxt-dev
        - util-linux-dev
    description: libxmu dev

  - name: libxmu-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv ${{targets.destdir}}/usr/share/doc ${{targets.subpkgdir}}/usr/share/
    description: libxmu docs

update:
  enabled: true
  release-monitor:
    identifier: 1785
