package:
  name: libxml2
  version: 2.12.6
  epoch: 0
  description: XML parsing library, version 2
  copyright:
    - license: MIT

# creates a new var that contains only the major and minor version to be used in the fetch URL
# e.g. 2.10.1 will create a new var mangled-package-version=2.10
var-transforms:
  - from: ${{package.version}}
    match: (\d+\.\d+)\.\d+
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3-dev
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 889c593a881a3db5fdd96cc9318c87df34eb648edfc458272ad46fd607353fbb
      uri: https://download.gnome.org/sources/libxml2/${{vars.mangled-package-version}}/libxml2-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        PYTHON=/usr/bin/python3 \
        --with-lzma \
        --with-zlib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libxml2-doc
    pipeline:
      - uses: split/manpages
    description: libxml2 manpages

  - name: libxml2-py3
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/python3* ${{targets.subpkgdir}}/usr/lib
    description: libxml2 python3 bindings

  - name: libxml2-utils
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr
    description: libxml2 utils

  - name: libxml2-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxml2
        - zlib-dev
        - xz-dev
        - libxml2-utils
    description: libxml2 dev

update:
  enabled: true
  release-monitor:
    identifier: 1783
