package:
  name: local-path-provisioner
  version: 0.0.26
  epoch: 5
  description: Dynamically provisioning persistent local storage with Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/local-path-provisioner
      tag: v${{package.version}}
      expected-commit: cf3be50b7f49c0dc40e7b6e4ff3c2dbb4f4830f9

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: local-path-provisioner
      ldflags: -w -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: rancher/local-path-provisioner
    strip-prefix: v
