package:
  name: logstash-exporter
  version: 1.6.3
  epoch: 3
  description: Prometheus exporter for Logstash written in Go
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    GITHUB_REPO: "github.com/kuskoman/logstash-exporter"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 119ace0b38cd6b3a4662eb63a5d49143ef02699c
      repository: https://github.com/kuskoman/logstash-exporter
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/exporter/main.go
      ldflags: -s -w -X ${GITHUB_REPO}/config.Version="${{package.version}}" -X ${GITHUB_REPO}/config.GitCommit="$(git rev-parse --short HEAD)" -X ${GITHUB_REPO}/config.BuildDate="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      repository: https://github.com/kuskoman/logstash-exporter
      output: logstash-exporter

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - "-pre*"
  github:
    identifier: kuskoman/logstash-exporter
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        logstash-exporter -version
