package:
  name: management-api-for-apache-cassandra
  version: 0.1.74
  epoch: 1
  description: RESTful / Secure Management Sidecar for Apache Cassandra
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - procps

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-11
      - openjdk-11-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/management-api-for-apache-cassandra
      expected-commit: 8dec53e48b2fc88e4c8b46e741025d45344bd449
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: upgrade-deps.patch

  - runs: |
      MAAC_PATH="${{targets.contextdir}}"/opt/management-api
      mkdir -p "${{targets.contextdir}}"/usr/local/bin
      mkdir -p "${{targets.contextdir}}"/opt/management-api
      export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
      mvn -q -ff package -DskipTests -DskipOpenApi

      cp ./scripts/docker-entrypoint.sh "${{targets.contextdir}}"/usr/local/bin/
      find . -type f -name "datastax-*.jar" -exec mv -t $MAAC_PATH -i '{}' +
      chmod +x "${{targets.contextdir}}"/usr/local/bin/docker-entrypoint.sh

subpackages:
  - name: management-api-for-apache-cassandra-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/management-api
          mkdir -p ${{targets.contextdir}}/bin
          ln -s /opt/management-api/datastax-mgmtapi-agent-4.1.x-0.1.0-SNAPSHOT.jar ${{targets.contextdir}}/opt/management-api/datastax-mgmtapi-agent.jar
          ln -s /opt/management-api/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar ${{targets.contextdir}}/opt/management-api/datastax-mgmtapi-server.jar
          ln -sf /usr/local/bin/docker-entrypoint.sh ${{targets.contextdir}}/docker-entrypoint.sh

          # the reason why we need to do this is because the java code hard-codes /bin/ps
          ln -s /usr/bin/ps ${{targets.contextdir}}/bin/ps
          # the reason why we need to do this is because the java code hard-codes /bin/which
          ln -s /usr/bin/which ${{targets.contextdir}}/bin/which

update:
  enabled: true
  github:
    identifier: k8ssandra/management-api-for-apache-cassandra
    strip-prefix: v
