package:
  name: mariadb-10.6
  version: 10.6.17
  epoch: 1
  description: "The MariaDB open source relational database"
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - pwgen
    provides:
      - mariadb=10.6.999

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libaio-dev
      - libevent-dev
      - linux-pam-dev
      - ncurses-dev
      - openssl-dev
      - pcre2-dev
      - readline-dev
      - samurai
      - wolfi-baselayout
      - xz-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.osuosl.org/pub/mariadb/mariadb-${{package.version}}/source/mariadb-${{package.version}}.tar.gz
      expected-sha256: fb41b0702059c046832d60138733acb73e4c0e5a1a0681061709d25591e4b086

  - name: "Cmake"
    runs: |
      cmake . -G Ninja \
        -DBUILD_CONFIG=mysql_release \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSYSCONFDIR=/etc \
        -DSYSCONF2DIR=/etc/my.cnf.d \
        -DMYSQL_DATADIR=/var/lib/mysql \
        -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
        -DDEFAULT_CHARSET=utf8mb4 \
        -DDEFAULT_COLLATION=utf8mb4_general_ci \
        -DENABLED_LOCAL_INFILE=ON \
        -DINSTALL_INFODIR=share/info \
        -DINSTALL_MANDIR=share/man \
        -DINSTALL_PLUGINDIR=lib/${{package.name}}/plugin \
        -DINSTALL_SCRIPTDIR=bin \
        -DINSTALL_INCLUDEDIR=include/mysql \
        -DINSTALL_DOCREADMEDIR=share/doc/${{package.name}} \
        -DINSTALL_SUPPORTFILESDIR=share/${{package.name}} \
        -DINSTALL_MYSQLSHAREDIR=share/${{package.name}} \
        -DINSTALL_DOCDIR=share/doc/${{package.name}} \
        -DTMPDIR=/var/tmp \
        -DCONNECT_WITH_MYSQL=ON \
        -DCONNECT_WITH_LIBXML2=system \
        -DCONNECT_WITH_ODBC=NO \
        -DCONNECT_WITH_JDBC=NO \
        -DPLUGIN_ARCHIVE=YES \
        -DPLUGIN_ARIA=YES \
        -DPLUGIN_BLACKHOLE=YES \
        -DPLUGIN_CASSANDRA=NO \
        -DPLUGIN_CSV=YES \
        -DPLUGIN_MYISAM=YES \
        -DPLUGIN_MROONGA=NO \
        -DPLUGIN_OQGRAPH=NO \
        -DPLUGIN_PARTITION=YES \
        -DPLUGIN_ROCKSDB=NO \
        -DPLUGIN_SPHINX=NO \
        -DPLUGIN_TOKUDB=NO \
        -DPLUGIN_AUTH_GSSAPI=NO \
        -DPLUGIN_AUTH_GSSAPI_CLIENT=OFF \
        -DPLUGIN_CRACKLIB_PASSWORD_CHECK=NO \
        -DWITH_ASAN=OFF \
        -DWITH_EMBEDDED_SERVER=ON \
        -DWITH_EXTRA_CHARSETS=complex \
        -DWITH_INNODB_BZIP2=OFF \
        -DWITH_INNODB_LZ4=OFF \
        -DWITH_INNODB_LZMA=ON \
        -DWITH_INNODB_LZO=OFF \
        -DWITH_INNODB_SNAPPY=OFF \
        -DWITH_PIC=ON \
        -DWITH_ROCKSDB_BZIP2=OFF \
        -DWITH_ROCKSDB_JEMALLOC=OFF \
        -DWITH_ROCKSDB_LZ4=OFF \
        -DWITH_ROCKSDB_ZSTD=OFF \
        -DWITH_ROCKSDB_SNAPPY=OFF \
        -DWITH_JEMALLOC=NO \
        -DWITH_LIBARCHIVE=system \
        -DWITH_LIBNUMA=NO \
        -DWITH_LIBWRAP=OFF \
        -DWITH_LIBWSEP=OFF \
        -DWITH_MARIABACKUP=ON \
        -DWITH_PCRE=system \
        -DWITH_READLINE=ON \
        -DWITH_SYSTEMD=no \
        -DWITH_SSL=system \
        -DWITH_VALGRIND=OFF \
        -DWITH_ZLIB=system \
        -DSKIP_TESTS=ON

  - name: "Install"
    runs: |
      DESTDIR="${{targets.destdir}}" ninja install

  - name: "Remove extras"
    runs: |
      rm -rf "${{targets.destdir}}"/usr/local/mysql/sql-bench/
      rm -rf "${{targets.destdir}}"/usr/local/mysql/mysql-test/

      rm -rf "${{targets.destdir}}"/usr/bin/mariadb_config
      rm -rf "${{targets.destdir}}"/usr/bin/mysql_config
      rm -rf "${{targets.destdir}}"/usr/include/mysql/errmsg.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/ma_list.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/ma_pvio.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/ma_tls.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb/ma_io.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb_com.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb_ctype.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb_dyncol.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb_stmt.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mariadb_version.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysql.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysql/client_plugin.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysql/plugin_auth.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysql/plugin_auth_common.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysql_version.h
      rm -rf "${{targets.destdir}}"/usr/include/mysql/mysqld_error.h
      rm -rf "${{targets.destdir}}"/usr/lib/${{package.name}}/plugin/dialog.so
      rm -rf "${{targets.destdir}}"/usr/lib/${{package.name}}/plugin/mysql_clear_password.so
      rm -rf "${{targets.destdir}}"/usr/lib/${{package.name}}/plugin/sha256_password.so
      rm -rf "${{targets.destdir}}"/usr/lib/${{package.name}}/plugin/caching_sha2_password.so
      rm -rf "${{targets.destdir}}"/usr/lib/${{package.name}}/plugin/client_ed25519.so
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient.so
      rm -rf "${{targets.destdir}}"/usr/lib/libmysqlclient_r.so
      rm -rf "${{targets.destdir}}"/usr/lib/libmariadb.so*
      rm -rf "${{targets.destdir}}"/usr/lib/pkgconfig/libmariadb.pc

  - name: "make mysql data dir "
    runs: |
      mkdir -p "${{targets.destdir}}"/var/lib/mysql

subpackages:
  - name: "mariadb-10.6-dev"
    description: "headers for mariadb"
    pipeline:
      - uses: split/dev
    dependencies:
      provides:
        - mariadb-dev=10.6.999

  - name: "mariadb-10.6-doc"
    pipeline:
      - uses: split/manpages
    dependencies:
      provides:
        - mariadb-doc=10.6.999

  - name: "mariadb-10.6-test"
    dependencies:
      provides:
        - mariadb-test=10.6.999
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/mysql_client_test \
            "${{targets.destdir}}"/usr/bin/mysql_client_test_embedded \
            "${{targets.destdir}}"/usr/bin/mariadb-client-test \
            "${{targets.destdir}}"/usr/bin/mariadb-client-test-embedded \
            "${{targets.destdir}}"/usr/bin/mariadb-test \
            "${{targets.destdir}}"/usr/bin/mariadb-test-embedded \
            "${{targets.destdir}}"/usr/bin/mysqltest \
            "${{targets.destdir}}"/usr/bin/mysqltest_embedded \
            "${{targets.subpkgdir}}"/usr/bin/

          mv "${{targets.destdir}}"/usr/mysql-test \
            "${{targets.subpkgdir}}"/usr/

  - name: "mariadb-10.6-bench"
    dependencies:
      provides:
        - mariadb-bench=10.6.999
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/sql-bench "${{targets.subpkgdir}}"/usr/share

  - name: "mariadb-10.6-backup"
    dependencies:
      provides:
        - mariadb-backup=10.6.999
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/mariabackup \
            "${{targets.destdir}}"/usr/bin/mariadb-backup \
            "${{targets.destdir}}"/usr/bin/mbstream \
            "${{targets.subpkgdir}}"/usr/bin/

  - name: mariadb-10.6-oci-entrypoint
    description: Entrypoint for using HAProxy in OCI containers
    dependencies:
      provides:
        - mariadb-oci-entrypoint=10.6.999
      runtime:
        - bash
        - busybox
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin/
          cp docker-entrypoint.sh ${{targets.subpkgdir}}/usr/local/bin/
          chmod +x ${{targets.subpkgdir}}/usr/local/bin/docker-entrypoint.sh

  - name: mariadb-10.6-embedded
    dependencies:
      provides:
        - mariadb-embedded=10.6.999
    description: Emedded library for mariadb
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mv "${{targets.destdir}}"/usr/bin/mariadb-embedded  "${{targets.subpkgdir}}"/usr/bin

  - name: mariadb-10.6-test
    dependencies:
      provides:
        - mariadb-test=10.6.999
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv mysql-test "${{targets.subpkgdir}}"/usr/mariadb-test

update:
  enabled: true
  github:
    identifier: MariaDB/server
    strip-prefix: mariadb-
    use-tag: true
    tag-filter: mariadb-10.6.
