package:
  name: memcached
  version: 1.6.25
  epoch: 2
  description: "Distributed memory object caching system"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cyrus-sasl-dev
      - libevent-dev
      - libseccomp-dev
      - linux-headers
      # - bsd-compat-headers
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://www.memcached.org/files/memcached-${{package.version}}.tar.gz
      expected-sha512: 70b11244fdedbea29cceda0f6db94fcd3723f70643f614db1163bae90d9b9792fe247233aa08b894869252f7b8340e85e41213cd04195b5f4ba288901ede80f7

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --enable-sasl \
        --enable-sasl-pwdb \
        --enable-seccomp

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "memcached-dev"
    description: "headers for memcached"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - memcached

  - name: "memcached-doc"
    description: "memcached manpages"
    pipeline:
      - uses: split/manpages

  - name: memcached-bitnami-compat
    description: "compat package with bitnami/memcached image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: memcached
          version-path: 1/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/memcached/conf/sasl2
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/memcached/conf.default

update:
  enabled: true
  github:
    identifier: memcached/memcached
    use-tag: true
    tag-filter: 1.

test:
  environment:
    contents:
      packages:
        - memcached-bitnami-compat
    accounts:
      groups:
        - groupname: nonroot
          gid: 65532
      users:
        - username: nonroot
          gid: 65532
          uid: 65532
      run-as: 65532
  pipeline:
    # Check command can at least show version
    - runs: |
        /usr/bin/memcached --version
    # Check that command starts up and listens
    - runs: |
        /usr/bin/memcached -vvv > /tmp/output 2>&1 &
        PID=$!
        count=0
        # Retries for a minute
        while [ "$count" -lt 12 ]; do
          if cat /tmp/output | grep -qi "server listening"; then
            echo "started up successfully!"
            kill $PID
            exit 0
          else
            echo "waiting for service to start up..."
            sleep 5
          fi
          count=$((count+1))
        done
        exit 1
    # Check folder exists
    - runs: |
        stat /opt/bitnami/memcached/conf.default
