package:
  name: minio
  # minio uses strange versioning, the upstream version is RELEASE.2023-10-25T06-33-25Z
  # when bumping this, also bump the tag in git-checkout below
  version: 0.20231220.010002
  epoch: 5
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/minio
      tag: RELEASE.2023-12-20T01-00-02Z
      expected-commit: 7a311a3b666a0e5476fbde24d4413220876d9df2

  - uses: go/bump
    with:
      deps: github.com/lestrrat-go/jwx@v1.2.29 google.golang.org/protobuf@v1.33.0

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv minio ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: false # uses strange versioning
