package:
  name: mockery
  version: 2.42.2
  epoch: 0
  description: A mock code autogenerator for Go
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - go
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vektra/mockery
      expected-commit: dc8084519dca7164d033092f8022b5ef0e835abf
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      go build -v -o ${{targets.destdir}}/usr/bin/mockery -ldflags="-s -w -X github.com/vektra/mockery/v2/pkg/logging.SemVer=v${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: vektra/mockery
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - posix-libc-utils
  pipeline:
    - runs: |
        mockery --version
