package:
  name: mods
  version: 1.2.2
  epoch: 1
  description: AI on the command line!
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/charmbracelet/mods
      tag: v${{package.version}}
      expected-commit: 6258e8ccebb6f52fdfe896aab2622b58d8f6aad1

  - uses: go/build
    with:
      packages: .
      repository: https://github.com/charmbracelet/mods
      ldflags: |
        -s -w
        -X main.Version=${{package.version}}
        -X main.CommitSHA=$(git rev-parse HEAD)
        -X main.CommitDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      output: mods

  - uses: strip

update:
  enabled: true
  github:
    identifier: charmbracelet/mods
    strip-prefix: v

test:
  pipeline:
    - runs: |
        mods --version
