package:
  name: mongo-tools
  version: 100.9.4
  epoch: 3
  description: Tools for MongoDB
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - krb5-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mongodb/mongo-tools
      tag: ${{package.version}}
      expected-commit: ce6af0fefca324ad5d9cb689d335130f48c99699

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - uses: patch
    with:
      patches: release-platform.patch

  - runs: |
      ./make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/* ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: mongodb/mongo-tools
    strip-prefix: v
    use-tag: true
    tag-filter: "100"
