package:
  name: msgpack-c
  version: 6.0.1
  epoch: 0
  description: "An efficient object serialization library for C"
  copyright:
    - license: BSL-1.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gtest-dev
      - samurai
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/msgpack/${{package.name}}/releases/download/c-${{package.version}}/${{package.name}}-${{package.version}}.tar.gz
      expected-sha256: a349cd9af28add2334c7009e331335af4a5b97d8558b2e9804d05f3b33d97925

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DMSGPACK_ENABLE_STATIC=ON \
        -DMSGPACK_BUILD_EXAMPLES=OFF \
        -DMSGPACK_BUILD_TESTS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "${{package.name}}-static"
    description: "${{package.name}} static library"
    pipeline:
      - uses: split/static

  - name: "${{package.name}}-dev"
    description: "${{package.name}} development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 235285
