package:
  name: msgpack-cxx
  version: 6.1.1
  epoch: 0
  description: "An efficient object serialization library for C++"
  copyright:
    - license: BSL-1.0
  dependencies:
    provides:
      - msgpack

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/msgpack/msgpack-c/releases/download/cpp-${{package.version}}/${{package.name}}-${{package.version}}.tar.gz
      expected-sha256: 5fd555742e37bbd58d166199e669f01f743c7b3c6177191dd7b31fb0c37fa191

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DMSGPACK_BUILD_EXAMPLES=OFF \
        -DMSGPACK_BUILD_TESTS=OFF \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DMSGPACK_CXX17=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    description: "${{package.name}} development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 12278
