package:
  name: multus-cni
  version: 4.0.2
  epoch: 1
  description: A CNI meta-plugin for multi-homed pods in Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8snetworkplumbingwg/multus-cni
      tag: v${{package.version}}
      expected-commit: f03765681fe81ee1e0633ee1734bf48ab3bccf2b

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/multus
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus

  - uses: go/build
    with:
      packages: ./cmd/multus-daemon
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus-daemon

  - uses: go/build
    with:
      packages: ./cmd/multus-shim
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus-shim

  - uses: go/build
    with:
      packages: ./cmd/install_multus
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: install_multus

  - uses: go/build
    with:
      packages: ./cmd/thin_entrypoint
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: thin_entrypoint

  - uses: strip

update:
  enabled: true
  github:
    identifier: k8snetworkplumbingwg/multus-cni
    strip-prefix: v

test:
  pipeline:
    - runs: |
        multus -version
        multus-daemon -h
        multus-shim -h
