package:
  name: mycli
  version: 1.27.2
  epoch: 0
  description: "static code and composition analysis tool for IaC"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - py3-cli-helpers
      - py3-click
      - py3-configobj
      - py3-cryptography
      - py3-gpep517
      - py3-installer
      - py3-prompt-toolkit
      - py3-pyaes
      - py3-pygments
      - py3-pymysql
      - py3-pyperclip
      - py3-setuptools
      - py3-sqlglot
      - py3-sqlparse
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/m/mycli/mycli-${{package.version}}.tar.gz
      expected-sha256: d11da4e614640096ea8066443d75946f8f281714ca30a89065c91fdc5f950b72

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
      rm -rf "${{targets.destdir}}"/usr/lib/python3*/site-packages/test/

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 8755
