package:
  name: nasm
  version: 2.16.02
  epoch: 0
  description: 80x86 assembler designed for portability and modularity
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1e1b942ea88f22edae89659e15be26fa027eae0747f51413540f52d4eac4790d
      uri: https://www.nasm.us/pub/nasm/releasebuilds/${{package.version}}/nasm-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: nasm-doc
    pipeline:
      - uses: split/manpages
    description: nasm manpages

update:
  enabled: true
  github:
    identifier: netwide-assembler/nasm
    strip-prefix: nasm-
    use-tag: true
