package:
  name: neo4j
  version: 5.18.0
  epoch: 0
  description:
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - bash
      - openjdk-17-jre

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neo4j/neo4j
      tag: ${{package.version}}
      expected-commit: e464367926bc5d2e5db10b9ee6f743f128b14a93

  - uses: maven/configure-mirror

  - runs: |
      export LANG=en_US.UTF-8

      mvn package -DskipTests=true -T$(nproc)C -q
      mkdir -p ${{targets.destdir}}/usr/share/java/neo4j

      tar --strip-components=1 -xf packaging/standalone/target/neo4j-*.tar.gz -C ${{targets.destdir}}/usr/share/java/neo4j

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in neo4j neo4j-admin cypershell; do
        ln -sf /usr/share/java/neo4j/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

subpackages:
  - name: neo4j-oci-entrypoint
    description: OCI entrypoint for Neo4j
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv entrypoint.sh ${{targets.subpkgdir}}/usr/bin/entrypoint.sh

update:
  enabled: true
  github:
    identifier: neo4j/neo4j
    use-tag: true
