package:
  name: neuvector-prometheus-exporter
  version: 5.3.0
  epoch: 0
  description: Python client for the Prometheus monitoring system.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-prometheus-client
      - py3-requests
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c8616b8c85a141d25cdf254664fe48cb8c9cbedc
      repository: https://github.com/neuvector/prometheus-exporter.git
      tag: v${{package.version}}

  - runs: |
      install -Dm755 nv_exporter.py "${{targets.destdir}}"/usr/bin/nv_exporter.py

  - uses: strip

test:
  environment:
    contents:
      packages:
        - python3
        - py3-pip
  pipeline:
    # Test that all the runtime dependencies are importable
    - runs: |
        #!/bin/bash
        set -euo pipefail
        # List all the runtime required packages by removing the version constraints
        # Also replace '-' with '_' in package names, otherwise 'charset-normalizer' will fail
        pip freeze | cut -d"=" -f1 | awk '{print $1}' | tr '-' '_' > requirements.txt
        cat requirements.txt
        set -x
        while IFS= read -r pkg; do
          if [[ -n $pkg ]]; then
            python3 -c "import $pkg"
          fi
        done < requirements.txt
    # Test that the script can be run
    - runs: python3 /usr/bin/nv_exporter.py --help
    # Test that the entrypoint is working
    - runs: |
        export CTRL_API_SERVICE="dummy:7777"
        export EXPORTER_PORT=8068
        export CTRL_USERNAME=admin
        export CTRL_PASSWORD=admin
        python3 /usr/bin/nv_exporter.py | grep -q "Failed to resolve 'dummy'"

update:
  enabled: true
  github:
    identifier: neuvector/prometheus-exporter
    strip-prefix: v
    tag-filter: v
    use-tag: true
