package:
  name: newrelic-infra-operator
  version: 0.18.0
  epoch: 3
  description: Newrelic kubernetes operator of infrastructure
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-infra-operator
      tag: v${{package.version}}
      expected-commit: 576f50101ba2cafd4d41ca478d4e48bdc37fcfbf

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv newrelic-infra-operator ${{targets.destdir}}/usr/bin/newrelic-infra-operator

  - uses: strip

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-infra-operator
    strip-prefix: v
    tag-filter: v
    use-tag: true
