package:
  name: newrelic-fluent-bit-output
  version: 1.19.2
  epoch: 2
  description: A Fluent Bit output plugin that sends logs to New Relic
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/newrelic-fluent-bit-output
      tag: v${{package.version}}
      expected-commit: f8b9de892b03956735881f9c4e67f39a2eb8831c

  - uses: patch
    with:
      patches: fix-archs.patch

  - runs: |
      ARCH=$(go env GOARCH)
      make VERSION=v${{ package.version }} linux/${ARCH}
      mkdir -p ${{targets.destdir}}/fluent-bit/bin
      cp ./out_newrelic-linux-${ARCH}-v${{ package.version }}.so ${{targets.destdir}}/fluent-bit/bin/out_newrelic.so

  - uses: strip

subpackages:
  - name: newrelic-fluent-bit-output-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/fluent-bit/bin/
          # The upstream chart expects the fluent-bit binary to be in /fluent-bit/bin/fluent-bit
          ln -sf /usr/bin/fluent-bit ${{targets.subpkgdir}}/fluent-bit/bin/fluent-bit
    dependencies:
      runtime:
        - newrelic-fluent-bit-output

update:
  enabled: true
  github:
    identifier: newrelic/newrelic-fluent-bit-output
    strip-prefix: v
    use-tag: true
    tag-filter: v
