package:
  name: node-gyp
  version: 10.1.0
  epoch: 1
  description: "the npm package manager for javascript, mainline"
  copyright:
    - license: Artistic-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm

pipeline:
  - name: npm install
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.destdir}}/usr

update:
  enabled: true
  github:
    identifier: nodejs/node-gyp
    use-tag: true
    strip-prefix: v
