package:
  name: nri-elasticsearch
  version: 5.2.3
  epoch: 2
  description: New Relic Infrastructure Elasticsearch Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-elasticsearch
      expected-commit: 3d465692ee0bddd4968882c8a974376199889390
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-elasticsearch
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/elasticsearch-definition.yml ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/elasticsearch-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-elasticsearch
    strip-prefix: v
