package:
  name: nri-consul
  version: 2.7.8
  epoch: 1
  description: New Relic Infrastructure Consul Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-consul
      expected-commit: b0d80d6232f4d734384f2bad07a728f1eff5e239
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-consul
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/consul-definition.yml ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/consul-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-consul
    strip-prefix: v
