package:
  name: nri-redis
  version: 1.11.4
  epoch: 2
  description: New Relic Infrastructure Redis Integration
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-redis
      expected-commit: cc2fbf3e833231e5851af5a4ca557aae6b85772b
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-redis
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/redis-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/redis-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-redis
    strip-prefix: v
