package:
  name: nri-mysql
  version: 1.10.6
  epoch: 1
  description: New Relic Infrastructure MySQL Integration
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mysql
      expected-commit: 94d312c342da3b8e8a81f7100ab12166c3f2a402
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mysql
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/mysql-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/mysql-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-mysql
    strip-prefix: v
