package:
  name: nri-mongodb
  version: 2.8.1
  epoch: 6
  description: New Relic Infrastructure MongoDB Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mongodb
      expected-commit: 61cce55b7d7ecf223325602d5deaa3b83e37c776
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mongodb
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/mongodb-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/mongodb-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-mongodb
    strip-prefix: v
