package:
  name: nri-f5
  version: 2.7.3
  epoch: 2
  description: New Relic Infrastructure F5 Integration
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-f5
      expected-commit: bad8bb7b4f63d831193d0e9dd4559e403f316504
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-f5
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/f5-definition.yml ${{targets.contextdir}}/var/db/newrelic-infra/newrelic-integrations/f5-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-f5
    strip-prefix: v
