package:
  name: nri-kafka
  version: 3.7.1
  epoch: 2
  description: New Relic Infrastructure Kafka Integration
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nrjmx
      - openjdk-8-jre

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-kafka
      expected-commit: 501583e5405e136c4ff780a132d6f61a0471ee9e
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-kafka
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/kafka-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/kafka-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-kafka
    strip-prefix: v
