package:
  name: nsc
  version: 2.8.6
  epoch: 1
  description: Tool for creating nkey/jwt based configurations
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: go/install
    with:
      package: github.com/nats-io/nsc/v2@v${{package.version}}

update:
  enabled: true
  github:
    identifier: nats-io/nsc
    strip-prefix: v
