package:
  name: nsd
  version: 4.9.1
  epoch: 0
  description: "The NLnet Labs Name Server Daemon (NSD) is an authoritative, RFC compliant DNS nameserver."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libevent-dev
      - openssl-dev
      - wolfi-base

var-transforms:
  - from: ${{package.version}}_REL
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NLnetLabs/nsd
      expected-commit: 07119e953925c40454e583058fa5626754f02f0d
      tag: NSD_${{vars.mangled-package-version}}

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: CC=/usr/bin/gcc

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: nsd-doc
    description: nsd manpages
    pipeline:
      - uses: split/manpages

# tag/release names on github look like NSD_4_8_0_REL
update:
  enabled: true
  github:
    identifier: NLnetLabs/nsd
    use-tag: true
    strip-suffix: _REL
    strip-prefix: NSD_
    tag-filter: NSD_4
  version-separator: "_"
