package:
  name: nss
  version: "3.99"
  epoch: 0
  description: "Network Security Services (NSS) is a set of libraries designed to support cross-platform development of security-enabled client and server applications."
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - libnspr
      - libnspr-dev
      - mercurial
      - perl
      - py3-gyp-next
      - samurai
      - sqlite-dev
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: nss-package-version

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.mozilla.org/pub/security/nss/releases/NSS_${{vars.nss-package-version}}_RTM/src/nss-${{package.version}}.tar.gz
      expected-sha256: 5cd5c2c8406a376686e6fa4b9c2de38aa280bea07bf927c0d521ba07c88b09bd

  - runs: |
      cd nss
      ./build.sh -c --disable-tests --opt --system-nspr --system-sqlite

      mkdir -p "${{targets.destdir}}"/usr/lib
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/usr/include/nss

      mv ../dist/Release/lib/*.so "${{targets.destdir}}"/usr/lib
      mv ../dist/Release/bin/* "${{targets.destdir}}"/usr/bin
      mv ../dist/public/nss/* "${{targets.destdir}}"/usr/include/nss

      NSS_VMAJOR=`awk '/#define.*NSS_VMAJOR/ {print $3}' lib/nss/nss.h `
      NSS_VMINOR=`awk '/#define.*NSS_VMINOR/ {print $3}' lib/nss/nss.h`
      NSS_VPATCH=`awk '/#define.*NSS_VPATCH/ {print $3}' lib/nss/nss.h`

      # pkgconfig files
      mkdir -p ${{targets.destdir}}/usr/lib/pkgconfig
      sed ./pkg/pkg-config/nss.pc.in \
        -e "s,%libdir%,/usr/lib,g" \
        -e "s,%prefix%,/usr,g" \
        -e "s,%exec_prefix%,/usr/bin,g" \
        -e "s,%includedir%,/usr/include/nss,g" \
        -e "s,%NSPR_VERSION%,${{package.version}},g" \
        -e "s,%NSS_VERSION%,${{package.version}},g" \
        -e "s,%NSSUTIL_VERSION%,${{package.version}},g" \
        > "${{targets.destdir}}"/usr/lib/pkgconfig/nss.pc

  - uses: strip

subpackages:
  - name: libnss
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/*.so "${{targets.subpkgdir}}"/usr/lib
    dependencies:
      runtime:
        - libnspr

  - name: libnss-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libnss

  - name: libnss-tools
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/* "${{targets.subpkgdir}}"/usr/bin
    dependencies:
      runtime:
        - libnss

update:
  enabled: true
  release-monitor:
    identifier: 2503
