package:
  name: nuclei
  version: 3.2.3
  epoch: 0
  description: "yaml based vulnerability scanner"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - go
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9957003113218178489f304e488d6c6b90b87123
      repository: https://github.com/projectdiscovery/nuclei
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/quic-go/quic-go@v0.42.0

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      go mod edit -replace=github.com/mholt/archiver@v3.1.1+incompatible=github.com/mholt/archiver/v3@v3.3.2 # CVE-2019-10743 Fixed
      go mod tidy
      go build cmd/nuclei/main.go
      cp main "${{targets.destdir}}"/usr/bin/nuclei

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: projectdiscovery/nuclei
