package:
  name: ollama
  version: 0.1.30
  epoch: 1
  description: Get up and running with Llama 2 and other large language models locally
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jmorganca/ollama
      tag: v${{package.version}}
      expected-commit: 756c2575535641f1b96d94b4214941b90f4c30c7

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - runs: |
      go generate ./...
      CGO_ENABLED=1 go build -ldflags '-linkmode external -extldflags "-static"' .
      mkdir -p ${{targets.destdir}}/usr/bin
      mv ollama ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: jmorganca/ollama
    strip-prefix: v
