package:
  name: openscap
  version: 1.3.10
  epoch: 0
  description: NIST Certified SCAP 1.2 toolkit
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - acl-dev
      - asciidoc
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - dbus-dev
      - doxygen
      - glib-dev
      - graphviz
      - graphviz-dev
      - libbz2-1
      - libcap-dev
      - libgcrypt-dev
      - libnss-dev
      - libproc-2-0
      - libxml2-dev
      - libxslt-dev
      - openldap-dev
      - openssl-dev
      - perl-dev
      - perl-xml-parser
      - popt-dev
      - procps
      - py3-gv
      - py3-setuptools
      # TODO: Needed for rpm/apt scanning
      # - perl-xml-xpath
      # - opendbx-dev
      # - rpm-dev
      # - apt-dev
      # - libselinux
      - python3-dev
      - samurai
      - swig
      - systemd-dev
      - util-linux-dev
      - xmlsec-dev
      - xmlsec-openssl
      - yaml-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/OpenSCAP/openscap
      expected-commit: 6d008616978306ce5e68997dce554a1683064f8f
      tag: ${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=None \
        -DENABLE_PERL=OFF \
        -DENABLE_TESTS=OFF \
        -DWITH_PCRE2=True

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:

# TODO: Requires some additional graphviz/xml packages
# - name: ${{package.name}}-doc
#   description: "OpenSCAP documentation"
#   pipeline:
#     - uses: split/manpages
update:
  enabled: true
  github:
    identifier: OpenSCAP/openscap
