package:
  name: openjdk-11
  version: 11.0.17.8
  epoch: 1
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: GPL-2.0-only
  dependencies:
    runtime:
      - freetype
      - fontconfig

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - file
      - freetype-dev
      - cups-dev
      - libx11-dev
      - libxext-dev
      - libxrender-dev
      - libxrandr-dev
      - libxtst-dev
      - libxt-dev
      - alsa-lib-dev
      - libffi-dev
      - bash
      - zip
      - fontconfig-dev
      - libxi-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16.1_1.tar.gz
      expected-sha256: 5f6b513757d386352cf91514ed5859d1ab59364b4453e1f1c57152ba2039b8e2
      strip-components: 0
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.17%2B8/OpenJDK11U-jdk-sources_11.0.17_8.tar.gz
      expected-sha256: 0e403992d3ea664df8c10b4c3e5b71d6c02ee3dddd8b474b05bab3fb2c525cd5
  - runs: chmod +x configure
  - uses: autoconf/configure
    with:
      opts: |
        --with-boot-jdk=./jdk-11.0.16.1+1 \
        --with-vendor-name=wolfi \
        --with-vendor-url=https://wolfi.dev \
        --with-vendor-bug-url=https://github.com/wolfi-dev/os/issues \
        --with-version-opt="wolfi-r${{package.epoch}}" \
        --disable-warnings-as-errors \
        --disable-precompiled-headers \
        --enable-dtrace=no \
        --with-zlib=system \
        --with-native-debug-symbols=none \
        --with-jvm-variants=server \
        --with-debug-level=release \
        --with-jtreg=no  \
        --with-libpng=system \
        --with-jvm-variants=server \
        --with-debug-level=release
  # TODO revisit below args
  #         --with-libjpeg=system \
  #         --with-giflib=system \
  #         --with-lcms=system \
  - runs: make images
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/jvm/openjdk
      cp -r ./build/linux-*-server-release/images/jdk/* ${{targets.destdir}}/usr/lib/jvm/openjdk

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /usr/lib/jvm/openjdk/bin/java ${{targets.destdir}}/usr/bin/java
subpackages:
  - name: openjdk-11-jre

    pipeline:
      - runs: |
          # generate JRE via jlink

          mkdir -p ${{targets.subpkgdir}}/usr/lib/jvm
          ${{targets.destdir}}/usr/lib/jvm/openjdk/bin/jlink \
            --no-header-files \
            --no-man-pages \
            --compress=2 \
            --add-modules ALL-MODULE-PATH \
            --output ${{targets.subpkgdir}}/usr/lib/jvm/openjdk-jre

          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ln -sf /usr/lib/jvm/openjdk-jre/bin/java ${{targets.subpkgdir}}/usr/bin/java
    description: OpenJDK 11 (JRE)
    dependencies:
      runtime:
        - freetype
        - fontconfig

  - name: openjdk-11-jre-doc
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv  ${{targets.destdir}}/usr/lib/jvm/openjdk/man ${{targets.subpkgdir}}/usr/share
    description: OpenJDK 11 manpages
