package:
  name: openjdk-17
  version: 17.0.5.8
  epoch: 1
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: GPL-2.0-only
  dependencies:
    runtime:
      - freetype
      - fontconfig

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - file
      - freetype-dev
      - cups-dev
      - libx11-dev
      - libxext-dev
      - libxrender-dev
      - libxrandr-dev
      - libxtst-dev
      - libxt-dev
      - alsa-lib-dev
      - libffi-dev
      - bash
      - zip
      - fontconfig-dev
      - libxi-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
      expected-sha256: 323d6d7474a359a28eff7ddd0df8e65bd61554a8ed12ef42fd9365349e573c2c
      strip-components: 0
  - uses: fetch
    with:
      uri: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk-sources_17.0.5_8.tar.gz
      expected-sha256: d72b23fcd805a0bc56b113b658ede140be44ca19d1058704f6ac93d803663155
  - uses: fetch
    with:
      uri: https://github.com/google/googletest/archive/release-1.8.1.tar.gz
      expected-sha256: 9bf1fe5182a604b4135edc1a425ae356c9ad15e9b23f9f12a02e80184c3a249c
      strip-components: 0
  - runs: chmod +x configure
  - uses: autoconf/configure
    with:
      opts: |
        --with-boot-jdk=./jdk-16.0.2+7 \
        --with-vendor-name=wolfi \
        --with-vendor-url=https://wolfi.dev \
        --with-vendor-bug-url=https://github.com/wolfi-dev/os/issues \
        --with-version-opt="wolfi-r${{package.epoch}}" \
        --with-gtest=./googletest-release-1.8.1 \
        --disable-warnings-as-errors \
        --disable-precompiled-headers \
        --enable-dtrace=no \
        --with-zlib=system \
        --with-native-debug-symbols=none \
        --disable-warnings-as-errors \
        --disable-precompiled-headers \
        --with-jvm-variants=server \
        --with-debug-level=release \
        --with-jtreg=no  \
        --with-libpng=system
  # TODO revisit below args
  #         --with-libjpeg=system \
  #         --with-giflib=system \
  #         --with-lcms=system \
  - runs: make jdk-image
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/lib/jvm/openjdk
      cp -r ./build/linux-*-server-release/images/jdk/* ${{targets.destdir}}/usr/lib/jvm/openjdk

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /usr/lib/jvm/openjdk/bin/java ${{targets.destdir}}/usr/bin/java

subpackages:
  - name: openjdk-17-jre
    pipeline:
      - runs: |
          # generate JRE via jlink

          mkdir -p ${{targets.subpkgdir}}/usr/lib/jvm

          ${{targets.destdir}}/usr/lib/jvm/openjdk/bin/jlink \
            --no-header-files \
            --no-man-pages \
            --compress=2 \
            --add-modules ALL-MODULE-PATH \
            --output ${{targets.subpkgdir}}/usr/lib/jvm/openjdk-jre

          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ln -sf /usr/lib/jvm/openjdk-jre/bin/java ${{targets.subpkgdir}}/usr/bin/java
    description: OpenJDK 17 (JRE)
    dependencies:
      runtime:
        - freetype
        - fontconfig

  - name: openjdk-17-doc
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mv  ${{targets.destdir}}/usr/lib/jvm/openjdk/man ${{targets.subpkgdir}}/usr/share
    description: OpenJDK 17 manpages
