package:
  name: openssh
  version: 9.7_p1
  epoch: 0
  description: "the OpenBSD SSH implementation"
  copyright:
    - license: ISC
  dependencies:
    runtime:
      - openssh-client
      - openssh-server
      - openssh-sftp-server

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libedit-dev
      - openssl-dev
      - wolfi-baselayout
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.7p1.tar.gz
      expected-sha256: 490426f766d82a2763fcacd8d83ea3d70798750c7bd2aff2e57dc5660f773ffd

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share \
         --sysconfdir=/etc/ssh \
         --libexecdir=/usr/lib/ssh \
         --with-pid-dir=/run \
         --with-mantype=doc \
         --with-cflags="-O2 -D_FORTIFY_SOURCE=2 -Wall" \
         --disable-utmp \
         --disable-wtmp \
         --disable-lastlog \
         --disable-strip \
         --with-privsep-path=/var/empty \
         --with-xauth=/usr/bin/xauth \
         --with-default-path='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
         --with-privsep-user=sshd \
         --with-ssl-engine \
         --with-libedit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "openssh-doc"
    description: "OpenSSH documentation"
    pipeline:
      - uses: split/manpages

  - name: "openssh-keygen"
    description: "OpenSSH key generator"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ssh-keygen "${{targets.subpkgdir}}"/usr/bin/

  - name: "openssh-keyscan"
    description: "OpenSSH key scanner"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/ssh-keyscan "${{targets.subpkgdir}}"/usr/bin/

  - name: "openssh-keysign"
    description: "OpenSSH key signing tool"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-keysign "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-sftp-server"
    description: "OpenSSH SFTP server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/sftp-server "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-pkcs11-helper"
    description: "PKCS11 helper for OpenSSH"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-pkcs11-helper "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-sk-helper"
    description: "Security key helper for OpenSSH"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ssh
          mv "${{targets.destdir}}"/usr/lib/ssh/ssh-sk-helper "${{targets.subpkgdir}}"/usr/lib/ssh/

  - name: "openssh-client"
    description: "OpenSSH client"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv "${{targets.destdir}}"/usr/bin "${{targets.subpkgdir}}"/usr/

          mkdir -p "${{targets.subpkgdir}}"/etc/ssh
          mv "${{targets.destdir}}"/etc/ssh/moduli "${{targets.subpkgdir}}"/etc/ssh/
          mv "${{targets.destdir}}"/etc/ssh/ssh_config "${{targets.subpkgdir}}"/etc/ssh/

  - name: "openssh-server"
    description: "OpenSSH server"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mv "${{targets.destdir}}"/usr/sbin/sshd "${{targets.subpkgdir}}"/usr/sbin/
    dependencies:
      runtime:
        - openssh-keygen
        - openssh-server-config

  - name: "openssh-server-config"
    description: "OpenSSH server configuration"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/etc
          mv "${{targets.destdir}}"/etc/ssh "${{targets.subpkgdir}}"/etc/

update:
  manual: true # version in fetch url is different from package.version
  enabled: true
  release-monitor:
    identifier: 2565
