package:
  name: oras
  version: 1.1.0
  epoch: 6
  description: OCI registry client - managing content like artifacts, images, packages.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oras-project/oras
      tag: v${{package.version}}
      destination: oras
      expected-commit: 7079c468a06fb5815c99395eb4aaf46dd459d3fa

  - runs: |
      cd oras
      GOARCH=$(go env GOARCH)
      make build-linux-${GOARCH}
      install -m755 -D ./bin/linux/${GOARCH}/oras "${{targets.destdir}}"/usr/bin/oras

  - uses: strip

update:
  enabled: true
  github:
    identifier: oras-project/oras
    strip-prefix: v
