package:
  name: perl-html-parser
  version: "3.82"
  epoch: 0
  description: HTML parser class
  copyright:
    - license: GPL-1.0-or-later OR Artistic-1.0-Perl
  dependencies:
    runtime:
      - perl-html-tagset
      - perl-http-message
      - perl-uri

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl
      - perl-dev
      - perl-html-tagset
      - perl-http-message
      - perl-uri

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5b1f20dd0e471a049c13a53d0fcd0442f58518889180536c6f337112c9a430d8
      uri: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-${{package.version}}.tar.gz

  - uses: perl/make

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: perl/cleanup

subpackages:
  - name: perl-html-parser-doc
    pipeline:
      - uses: split/manpages
    description: perl-html-parser manpages

update:
  enabled: true
  release-monitor:
    identifier: 2967
