package:
  name: petname
  version: 2.11
  epoch: 5
  description: Generate pronouncable, perhaps even memorable, pet names
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dustinkirkland/golang-petname
      tag: ${{package.version}}
      expected-commit: 348648eed8164a867a6b78400cdf8e30dd84d1dd

  - uses: go/build
    with:
      packages: ./cmd/petname
      output: petname

  - uses: strip

update:
  enabled: true
  github:
    identifier: dustinkirkland/golang-petname
    use-tag: true
