# pgvector-16 is intended to support PostgreSQL 16.
# https://github.com/pgvector/pgvector#installation-notes
package:
  name: pgvector-16
  version: 0.6.2
  epoch: 0
  description: Open-source vector similarity search for PostgreSQL
  copyright:
    - license: PostgreSQL

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - postgresql-16-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pgvector/pgvector
      expected-commit: 96ff19be4487a843fa96f8801afcfdd49ac3eeac
      tag: v${{package.version}}

  - runs: |
      make OPTFLAGS=""
      make USE_PGXS=1 DESTDIR="${{targets.destdir}}" PG_CONFIG=/usr/bin/pg_config install

  - uses: strip

update:
  enabled: true
  github:
    identifier: pgvector/pgvector
    strip-prefix: v
    use-tag: true
