package:
  name: php-8.1-grpc
  version: 1.62.1
  epoch: 0
  description: "A PHP extension for gRPC"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - grpc
      - php-8.1
    provides:
      - php-grpc=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - grpc-dev
      - php-8.1
      - php-8.1-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc
      tag: "v${{package.version}}"
      expected-commit: 6d7a55890e076a3a8abc8185b6bf0153fcf9d179

  - name: Prepare build
    runs: cd src/php/ext/grpc && phpize

  - name: Configure
    runs: cd src/php/ext/grpc && ./configure

  - name: Make install
    runs: |
      cd src/php/ext/grpc
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-grpc-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=grpc.so" > "${{targets.subpkgdir}}/etc/php/conf.d/grpc.ini"

update:
  enabled: true
  github:
    identifier: grpc/grpc
    strip-prefix: v
    tag-filter: v
