package:
  name: php-8.1-memcached
  version: 3.2.0
  epoch: 0
  description: "A PHP extension for Memcached"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.1
    provides:
      - php-memcached=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - libmemcached-dev
      - php-8.1
      - php-8.1-dev
      - php-8.1-igbinary-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/php-memcached-dev/php-memcached
      tag: v${{package.version}}
      expected-commit: d1cb3ae87be5382444322118f87324f4044d13b0

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: ./configure

  - uses: autoconf/make

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-memcached-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=memcached.so" > "${{targets.subpkgdir}}/etc/php/conf.d/memcached.ini"

  - name: ${{package.name}}-dev
    description: PHP 8.1 memcached development headers
    dependencies:
      provides:
        - php-memcached-dev=${{package.full-version}}
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: php-memcached-dev/php-memcached
    strip-prefix: v
    tag-filter: v
