package:
  name: php-8.1-opentelemetry
  version: 1.0.1
  epoch: 0
  description: "OpenTelemetry PHP auto-instrumentation extension"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.1
    provides:
      - php-opentelemetry=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.1
      - php-8.1-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/open-telemetry/opentelemetry-php-instrumentation
      tag: ${{package.version}}
      expected-commit: 7010de909f8fa65ae83ffe3ffa815c82c71842c6

  - name: Prepare build
    runs: cd ext && phpize

  - name: Configure
    runs: |
      set -x
      cd ext
      ./configure

  - name: Make install
    runs: |
      set -x
      cd ext
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-opentelemetry-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=opentelemetry.so" > "${{targets.subpkgdir}}/etc/php/conf.d/opentelemetry.ini"

update:
  enabled: true
  github:
    identifier: open-telemetry/opentelemetry-php-instrumentation
