package:
  name: php-8.3-excimer
  version: 1.2.1
  epoch: 0
  description: "Excimer is a PHP extension that provides an interrupting timer and a low-overhead sampling profiler."
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - php-8.3
    provides:
      - php-excimer=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - php-8.3
      - php-8.3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wikimedia/mediawiki-php-excimer
      tag: "${{package.version}}"
      expected-commit: 986209d032a1cc53ac930e44f50acb74ecee8816

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: |
      set -x
      ./configure

  - uses: autoconf/make

  - name: Make install
    runs: |
      set -x
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-excimer-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=excimer.so" > "${{targets.subpkgdir}}/etc/php/conf.d/excimer.ini"

update:
  enabled: true
  github:
    identifier: wikimedia/mediawiki-php-excimer
    use-tag: true
