package:
  name: php-8.1-imagick
  version: 3.7.0
  epoch: 0
  description: "PHP extension for ImageMagick"
  copyright:
    - license: PHP-3.01
  dependencies:
    runtime:
      - ${{package.name}}-config
      - imagemagick
      - php-8.1
    provides:
      - php-imagick=${{package.full-version}}

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - imagemagick-dev
      - php-8.1
      - php-8.1-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Imagick/imagick
      tag: "${{package.version}}"
      expected-commit: 52ec37ff633de0e5cca159a6437b8c340afe7831

  - name: Prepare build
    runs: phpize

  - name: Configure
    runs: |
      set -x
      ./configure

  - name: Make install
    runs: |
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    dependencies:
      provides:
        - php-imagick-config=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=imagick.so" > "${{targets.subpkgdir}}/etc/php/conf.d/imagick.ini"

update:
  enabled: true
  github:
    identifier: Imagick/imagick
    use-tag: true
