package:
  name: policy-controller
  version: 0.8.4
  epoch: 5
  description: The policy admission controller used to enforce policy on a cluster on verifiable supply-chain metadata from cosign.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8596f22c6b18dc5784ded99dd3896d585b2deb29
      repository: https://github.com/sigstore/policy-controller
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 github.com/cloudflare/circl@v1.3.7 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      make policy-controller && mv policy-controller "${{targets.destdir}}/usr/bin/policy-controller"
      make policy-tester && mv policy-tester "${{targets.destdir}}/usr/bin/policy-tester"

  - uses: strip

subpackages:
  - name: policy-controller-tester
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/bin"
          mv "${{targets.destdir}}/usr/bin/policy-tester" "${{targets.subpkgdir}}/usr/bin/policy-tester"
    dependencies:
      runtime:
        - ca-certificates-bundle
    description: CLI for testing ClusterImagePolicy resources

update:
  enabled: true
  manual: false
  github:
    identifier: sigstore/policy-controller
    strip-prefix: v
