package:
  name: prometheus-alertmanager
  # When bumping this version you can remove the `go get` line in the build script
  version: 0.27.0
  epoch: 3
  description: Prometheus Alertmanager
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - nodejs
      - npm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/alertmanager
      tag: v${{package.version}}
      expected-commit: 0aa3c2aad14cff039931923ab16b26b7481783b5

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make build

  - runs: |
      install -Dm755 amtool "${{targets.destdir}}"/usr/bin/amtool
      install -Dm755 alertmanager "${{targets.destdir}}"/usr/bin/alertmanager
      install -Dm644 examples/ha/alertmanager.yml "${{targets.destdir}}"/etc/alertmanager/alertmanager.yml

  - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/alertmanager
    strip-prefix: v
