package:
  name: prometheus-blackbox-exporter
  version: 0.24.0
  epoch: 8
  description: Blackbox prober exporter
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/blackbox_exporter
      tag: v${{package.version}}
      expected-commit: 0b0467473916fd9e8526e2635c2a0b1c56011dff

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 golang.org/x/crypto@v0.17.0 google.golang.org/grpc@v1.56.3 google.golang.org/protobuf@v1.33.0

  - runs: |
      make common-build

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/etc/blackbox_exporter
      install -Dm755 blackbox_exporter "${{targets.destdir}}"/usr/bin/blackbox_exporter
      install -Dm644 blackbox.yml "${{targets.destdir}}"/etc/blackbox_exporter/config.yml

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by Dockerfile"
    pipeline:
      - runs: |
          # The Dockerfile expects the cass-operator binaries to be in /bin instead of /usr/bin
          # https://github.com/prometheus/blackbox_exporter/blob/220d785fb022088163456980110df58334e41db8/Dockerfile#L12
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/blackbox_exporter ${{targets.subpkgdir}}/bin/blackbox_exporter
      - uses: strip

update:
  enabled: true
  github:
    identifier: prometheus/blackbox_exporter
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - prometheus-blackbox-exporter-compat
  pipeline:
    - runs: |
        # run the blackbox_exporter in the background and test if there is any connection for :9115
        /bin/blackbox_exporter --config.file /etc/blackbox_exporter/config.yml &
        # find the PID
        PID=$!
        # wait for the blackbox_exporter to start
        sleep 5
        # check if the blackbox_exporter is running by checking :9115 connection
        netstat -tuln | grep 9115
        # kill the blackbox_exporter
        kill $PID
