package:
  name: prometheus-exporter-plugin-for-opensearch
  version: 2.13.0.0
  epoch: 0
  description: |
    Prometheus exporter plugin for OpenSearch & OpenSearch Mixin
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - glibc-locale-en
      - openjdk-17
      - openjdk-17-default-jdk
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch
      expected-commit: 9fff4ce68f8bf6d5e04da55cbe01b0c43e7c0e95
      tag: ${{package.version}}
      recurse-submodules: true

  - runs: |
      #ignoring test as it requires to run opensearch as non-root
      ./gradlew build test -x integTest -x yamlRestTest

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/opensearch/plugins/prometheus-exporter-plugin-for-opensearch
      unzip "build/distributions/prometheus-exporter-${{package.version}}.zip" -d "${{targets.destdir}}/usr/share/opensearch/plugins/prometheus-exporter-plugin-for-opensearch"

update:
  enabled: true
  github:
    identifier: Aiven-Open/prometheus-exporter-plugin-for-opensearch
