package:
  name: prometheus-operator
  version: 0.73.0
  epoch: 0
  description: Prometheus Operator creates/configures/manages Prometheus clusters atop Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - openssl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus-operator/prometheus-operator.git
      tag: v${{package.version}}
      expected-commit: d70313bd17cf2a4b911222062608f793be146548

  - uses: autoconf/make
    with:
      opts: operator

  - runs: |
      mkdir -p "${{targets.contextdir}}/usr/bin"
      cp ./operator "${{targets.contextdir}}/usr/bin"

  - runs: |
      # test uses the -race flag which is incompatible with -buildmode=pie
      unset GOFLAGS
      make test-unit

subpackages:
  - name: prometheus-config-reloader
    description: Prometheus Operator creates/configures/manages Prometheus clusters atop Kubernetes
    pipeline:
      - uses: autoconf/make
        with:
          opts: prometheus-config-reloader
      - runs: |
          mkdir -p "${{targets.contextdir}}/usr/bin"
          mv ./prometheus-config-reloader "${{targets.contextdir}}/usr/bin"

  - name: prometheus-config-reloader-oci-entrypoint-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/bin"
          ln -s /usr/bin/prometheus-config-reloader "${{targets.contextdir}}/bin/prometheus-config-reloader"

update:
  enabled: true
  github:
    identifier: prometheus-operator/prometheus-operator
    strip-prefix: v
