package:
  name: protoc-gen-go-grpc
  version: 1.3.0
  epoch: 9
  description: Go support for Google's protocol buffers services
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: go/install
    with:
      package: google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: grpc/grpc-go
    strip-prefix: cmd/protoc-gen-go-grpc/v
    tag-filter: cmd/protoc-gen-go-grpc/
    use-tag: true
