package:
  name: proxysql
  version: 2.6.2
  epoch: 0
  description: High-performance MySQL proxy with a GPL license
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - bzip2
      - cmake
      - gawk
      - git
      - gnutls-dev
      - grep
      - jemalloc-dev
      - libgcrypt-dev
      - libtool
      - openssl
      - openssl-dev
      - patch
      - perl
      - posix-libc-utils
      - python3
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sysown/proxysql
      tag: v${{package.version}}
      expected-commit: b368fc9b42cd8d8e1eeda6ee2cb96353ff2e544c
    pipeline:
      - runs: |
          # Our default LDFLAGS cause an issue with proxysql. We need to add -fPIC.
          export CFLAGS="${CFLAGS} -fPIC"
          export CPPFLAGS="$CFLAGS"
          export CXXFLAGS="$CFLAGS"
          make -j$(nproc) GIT_VERSION=${{package.version}}-r${{package.epoch}}
      - runs: |
          mkdir -p ${{targets.destdir}}/usr/bin
          mkdir -p ${{targets.destdir}}/etc
          install -m 0755 src/proxysql ${{targets.destdir}}/usr/bin
          install -m 0600 etc/proxysql.cnf ${{targets.destdir}}/etc
      - uses: strip

update:
  enabled: true
  github:
    identifier: sysown/proxysql
    strip-prefix: v
