package:
  name: pulumi-language-yaml
  version: 1.6.0
  epoch: 2
  description: Pulumi Language SDK for YAML
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      destination: ${{package.name}}
      expected-commit: f72e93927c6fe2f51c9d22d51b490d660c6ccea6
      repository: https://github.com/pulumi/pulumi-yaml.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0
      modroot: ${{package.name}}

  - pipeline:
      - runs: |
          set -x

          export CGO_ENABLED=0 GO111MODULE=on
          go build \
            -o "${{targets.destdir}}/usr/bin/pulumi-language-yaml" \
            -ldflags="-s -w -X github.com/pulumi/pulumi-yaml/pkg/version.Version=v${{package.version}}" \
            ./cmd/pulumi-language-yaml/
      - uses: strip
    working-directory: ${{package.name}}

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-yaml
    strip-prefix: v
