package:
  name: py3-pycosat
  version: 0.6.6
  epoch: 0
  description: Python bindings to picosat (a SAT solver)
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/pycosat
      tag: ${{package.version}}
      expected-commit: 38bbc0ed7b21bd3e43dfc4be735557f06f224290

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: conda/pycosat

test:
  pipeline:
    - runs: |
        python -c "import pycosat"
