package:
  name: py3-asgiref
  version: 3.8.1
  epoch: 0
  description: ASGI specs, helper code, and adapters
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/django/asgiref
      tag: ${{package.version}}
      expected-commit: e38d3c327c01aa82c0bf2726220700c1097ea6cc

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - (.*)(a|b|rc)(.*)
  github:
    identifier: django/asgiref
    use-tag: true

test:
  pipeline:
    - runs: |
        python3 ./test.py > output.out 2>&1
        grep -E "ERROR|None" output.out && exit 1
