package:
  name: py3-tkinter
  version: 3.11.9
  epoch: 0
  description: A graphical user interface for the Python programming language
  copyright:
    - license: PSF-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - libx11-dev
      - linux-headers
      - ncurses-dev
      - openssl-dev
      - python3
      - readline-dev
      - sqlite-dev
      - tcl-dev
      - tk-dev
      - wolfi-base
      - xz-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: 9b1e896523fc510691126c864406d9360a3d1e986acbda59cda57b5abda45b87

  - runs: |
      export CFLAGS="${CFLAGS/-Os/} -fno-semantic-interposition"
      export LDFLAGS="$LDFLAGS -fno-semantic-interposition"
      ./configure \
      	--build=$CBUILD \
      	--host=$CHOST \
      	--prefix=/usr \
      	--enable-ipv6 \
      	--enable-loadable-sqlite-extensions \
      	--enable-shared \
      	--with-computed-gotos \
      	--with-dbmliborder=gdbm:ndbm \
      	--with-system-expat \
      	--with-system-ffi

        make EXTRA_CFLAGS="$CFLAGS -DTHREAD_STACK_SIZE=0x100000"

  - runs: |
      pkgver=${{package.version}}
      _basever="${pkgver%.*}"
      make DESTDIR=./tmpinstall sharedinstall libinstall
      mkdir -p "${{targets.destdir}}"/usr/lib/python$_basever/lib-dynload \
      	"${{targets.destdir}}"/usr/bin
      for lib in idlelib tkinter; do
       mv ./tmpinstall/usr/lib/python$_basever/$lib \
      		"${{targets.destdir}}"/usr/lib/python$_basever/
      done

      mv ./tmpinstall/usr/lib/python$_basever/lib-dynload/_tkinter*.so \
      "${{targets.destdir}}"/usr/lib/python$_basever/lib-dynload/
      mv ./tmpinstall/usr/bin/idle* \
      	"${{targets.destdir}}"/usr/bin/

  - uses: strip

update:
  enabled: true
  shared: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.11
    use-tag: true
