package:
  name: py3-werkzeug
  version: 3.0.2
  epoch: 1
  description: The comprehensive WSGI web application library.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-markupsafe
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - py3-wheel
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pallets/werkzeug/
      tag: ${{package.version}}
      expected-commit: d70dcea305bf842c5a3b55265b5ffac2db012e23

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: pallets/werkzeug
    use-tag: true
