package:
  name: py3-kubernetes
  version: 29.0.0
  epoch: 1
  description: Kubernetes python client
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-certifi
      - py3-dateutil
      - py3-google-auth
      - py3-ipaddress
      - py3-oauthlib
      - py3-pyyaml
      - py3-requests
      - py3-requests-oauthlib
      - py3-six
      - py3-urllib3
      - py3-websocket-client
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-client/python
      tag: v${{package.version}}
      expected-commit: 01b1642b835f5195a8f81a788908f2cb3991c671

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-client/python
    strip-prefix: v
