package:
  name: py3-asn1-modules
  version: 0.4.0
  epoch: 0
  description: A collection of ASN.1-based protocols modules
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-asn1
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pyasn1/pyasn1-modules
      tag: v${{package.version}}
      expected-commit: 98b1e268a30be4b2d6efa5c69eae772edc442c7e

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: pyasn1/pyasn1-modules
    strip-prefix: v
