package:
  name: py3-networkx
  version: "3.3"
  epoch: 0
  description: Python package for creating and manipulating graphs and networks
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/networkx/networkx
      expected-commit: 7fdddfa2caa8275f7862c46524b803db99ff2cde
      tag: networkx-${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: networkx/networkx
    strip-prefix: networkx-
