package:
  name: py3-awscrt
  version: 0.20.6
  epoch: 0
  description: Python bindings for the AWS Common Runtime
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - aws-crt-cpp-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3-dev
      - samurai
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/awslabs/aws-crt-python
      tag: v${{package.version}}
      expected-commit: 9797a2fb077370340c202689ad3aed967116e8cb

  - runs: |
      # Allow linking to shared libraries
      sed -i '/:lib/d' setup.py

      export AWS_CRT_BUILD_USE_SYSTEM_LIBCRYPTO=1
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" \
      dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: awslabs/aws-crt-python
    use-tag: true
    strip-prefix: v
