package:
  name: py3-hatchling
  version: 1.22.5
  epoch: 0
  description: "Modern, extensible Python build backend"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-pathspec
      - py3-pluggy
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/h/hatchling/hatchling-${{package.version}}-py3-none-any.whl
      expected-sha512: d0969cabce858348ca01e3446bc76e6045d4b012c8f5a86c88cb6d71c168f1d23e83227b894d358474b39581fbea6c636932adc51b529b56444b19ed9714c007
      extract: false
      delete: false

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" ./hatchling-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 185085
