package:
  name: py3-threadpoolctl
  version: 3.4.0
  epoch: 0
  description: Python helpers to limit the number of threads used in native libraries
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/joblib/threadpoolctl
      expected-commit: 81f70f01e830ecb56ed584263ed9d8e3bf86845e
      tag: ${{package.version}}

  - name: Python Build
    runs: |
      python3 -m gpep517 build-wheel \
      --wheel-dir .dist \
      --output-fd 3 3>&1 >&2

  - name: Python Install
    runs: |
      python3 -m installer -d "${{targets.destdir}}" \
      .dist/threadpoolctl*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: joblib/threadpoolctl
