package:
  name: py3-traitlets
  version: 5.14.2
  epoch: 0
  description: Traitlets Python configuration system
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ipython/traitlets
      expected-commit: cb672eb5ba235fdfee6407bd7f1b1985de934e7c
      tag: v${{package.version}}

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/traitlets*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: ipython/traitlets
    strip-prefix: v
