package:
  name: py3-matplotlib
  version: 3.8.4
  epoch: 0
  description: Python plotting package
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - numpy
      - py3-cairo
      - py3-certifi
      - py3-contourpy
      - py3-cycler
      - py3-dateutil
      - py3-fonttools
      - py3-kiwisolver
      - py3-packaging
      - py3-parsing
      - py3-pillow
      - py3-pybind11-dev
      - py3-setuptools
      - py3-tkinter
      - py3-tz
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/matplotlib/matplotlib
      expected-commit: 8fb842c78f1b57b13a3d0fe63e83f3d31694f887
      tag: v${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: matplotlib/matplotlib
    strip-prefix: v
