package:
  name: py3-requests-oauthlib
  version: 2.0.0
  epoch: 0
  description: OAuthlib authentication support for Requests.
  copyright:
    - license: ISC
  dependencies:
    runtime:
      - py3-oauthlib
      - py3-requests
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-oauthlib
      - py3-requests
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/requests/requests-oauthlib
      tag: v${{package.version}}
      expected-commit: 7af9125a4fb3a21fbff4b829449a090469cf32b4

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: requests/requests-oauthlib
    strip-prefix: v
