package:
  name: py3-contourpy
  version: 1.2.1
  epoch: 0
  description: Python library for calculating contours of 2D quadrilateral grids
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-pip
      - py3-pybind11-dev
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/contourpy/contourpy
      expected-commit: bc805ed85d711873232873af8a47a8effd224fa3
      tag: v${{package.version}}

  - name: Python Build
    runs: |
      python3 -m build

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: contourpy/contourpy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        LIBRARY="contourpy"
        IMPORT_STATEMENT="import contourpy"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
