package:
  name: py3-pyyaml
  version: 6.0.1
  epoch: 4
  description: "Python3 bindings for YAML"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cython
      - py3-setuptools
      - python3
      - python3-dev
      - wolfi-base
      - yaml-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yaml/pyyaml
      tag: ${{package.version}}
      expected-commit: c42fa3bff1eabdb64763bb1526d9ea1ccb708479

  # from: https://github.com/yaml/pyyaml/issues/601#issuecomment-1740811121
  - uses: patch
    with:
      patches: pyyaml-cython3.patch

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - dec-*
  github:
    identifier: yaml/pyyaml
    use-tag: true
