package:
  name: py3-s3transfer
  version: 0.10.1
  epoch: 0
  description: "Amazon S3 Transfer Manager for Python"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-botocore
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/boto/s3transfer/archive/${{package.version}}.tar.gz
      expected-sha256: b6d42d2c81791486166a7b5fc4b4159e7b7ca6c6242d01310eebf546e16382eb

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: boto/s3transfer
    use-tag: true
