package:
  name: py3-build
  version: 1.2.1
  epoch: 0
  description: A simple, correct Python build frontend
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-packaging
      - py3-pyproject-hooks
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/build
      tag: ${{package.version}}
      expected-commit: 1e67c062e9d1b1a6d5ffed621f4b29902bb764e5

  - runs: |
      python3 -m gpep517 build-wheel --wheel-dir dist --output-fd 1
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: pypa/build
    use-tag: true
    strip-suffix: .post1

test:
  pipeline:
    - runs: |
        LIBRARY="build"
        IMPORT_STATEMENT="import build"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
