package:
  name: py3-optuna
  version: 3.6.1
  epoch: 0
  description: A hyperparameter optimization framework
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-alembic
      - py3-cmaes
      - py3-colorlog
      - py3-packaging
      - py3-pyyaml
      - py3-sqlalchemy
      - py3-tqdm
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-installer
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/optuna/optuna
      expected-commit: 39f83f7eda0979af27d5e9dd6acc7a08fa1c63ec
      tag: v${{package.version}}

  - name: Python Build
    runs: |
      python3 -m gpep517 build-wheel \
      --wheel-dir .dist \
      --output-fd 3 3>&1 >&2

  - name: Python Install
    runs: python3 -m installer --destdir="${{targets.destdir}}" .dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: optuna/optuna
    strip-prefix: v
