package:
  name: py3-conda-libmamba-solver
  version: 24.1.0
  epoch: 1
  description: The libmamba based solver for conda.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-boltons
      - py3-libmambapy
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3
      - wolfi-base
  environment:
    # This is needed to work around the error "ValueError: ZIP does not support timestamps before 1980"
    SOURCE_DATE_EPOCH: 315532800

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda-libmamba-solver
      tag: ${{package.version}}
      expected-commit: 2fe2bb50f535066dac959ba4ee8022f9c1058392

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: conda/conda-libmamba-solver

test:
  environment:
    contents:
      packages:
        - python3
        - conda # this should be a runtime dependency, but it's not because that causes a cycle (conda depends on this, and this depends on conda)
  pipeline:
    - runs: |
        python3 -c "import conda_libmamba_solver"
