package:
  name: py3-conda-package-handling
  version: 2.2.0
  epoch: 3
  description: Create and extract conda packages of various formats
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda-package-handling
      tag: ${{package.version}}
      expected-commit: 7dbe812e964743a3a62b5a307f3d10ce70435885

  - name: Python Build
    runs: python -m build

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: conda/conda-package-handling

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - runs: |
        python3 -c "import conda_package_handling"
