package:
  name: py3-pybind11
  version: 2.12.0
  epoch: 1
  description: Seamless operability between C++11 and Python
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pybind/pybind11
      tag: v${{package.version}}
      expected-commit: 3e9dfa2866941655c56877882565e7577de6fc7b

  - name: Python Build
    runs: python setup.py build

  - uses: cmake/configure
    with:
      opts: |
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DUSE_PYTHON_INCLUDE_DIR=FALSE

  - uses: cmake/build

  - name: Python Install
    runs: |
      python -m gpep517 build-wheel \
        --wheel-dir .dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer -d "${{targets.destdir}}" .dist/*.whl

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: py3-pybind11-dev
    description: pybind11 development headers
    dependencies:
      runtime:
        - py3-pybind11
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib/cmake
          mv "${{targets.destdir}}"/usr/share/cmake/pybind11 "${{targets.contextdir}}"/usr/lib/cmake
          mv "${{targets.destdir}}"/usr/share "${{targets.contextdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/lib/python3.12/site-packages/pybind11/share "${{targets.contextdir}}"/usr/lib/python3.12/site-packages/pybind11/share

update:
  enabled: true
  github:
    identifier: pybind/pybind11
    strip-prefix: v
