package:
  name: py3-maturin
  version: 1.5.1
  epoch: 0
  description: Build and publish crates with pyo3, rust-cpython and cffi bindings as well as rust binaries as python packages
  copyright:
    - license: MIT OR Apache-2.0
  dependencies:
    runtime:
      - py3-tomli
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7d711f0c4a7c052608dc2e16d5c6721b9666d076
      repository: https://github.com/pyo3/maturin
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'beta'
  github:
    identifier: pyo3/maturin
    strip-prefix: v
