package:
  name: py3-awslambdaric
  version: 2.0.11
  epoch: 0
  description: AWS Lambda Runtime Interface Client for Python
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python-3.12

environment:
  contents:
    packages:
      - aws-crt-cpp-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - make
      - openssl-dev
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/aws-lambda-python-runtime-interface-client
      tag: ${{package.version}}
      expected-commit: 03ba270ce0ce2cb86ca1574544390f88725941c1

  - name: make build
    runs: make build

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/aws-lambda-python-runtime-interface-client
    strip-prefix: v
