package:
  name: py3-fonttools
  version: 4.51.0
  epoch: 0
  description: Tools to manipulate font files
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/fonttools/fonttools
      expected-commit: a1a5af2f1ff320a422c7a6c7c11983903bb3bd4a
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: fonttools/fonttools
