package:
  name: py3-markdown
  version: "3.6"
  epoch: 0
  description: Python implementation of John Gruber's Markdown.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-importlib-metadata
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Python-Markdown/markdown
      tag: ${{package.version}}
      expected-commit: e524b8fe938738cb4492411a34cce89051cb9695

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - ^\d+\.\d+\.final$
    - ^\d+\.\d+.\d+\.final$
  github:
    identifier: Python-Markdown/markdown
    use-tag: true
