package:
  name: py3.11-setuptools
  version: 69.2.0 # When bumping this, also bump the provides below!
  epoch: 0
  description: Easily download, build, install, upgrade, and uninstall Python packages
  copyright:
    - license: "MIT"
  dependencies:
    provides:
      - py3-setuptools=69.0.0 # force the provides version lower than the py3.12-setuptools provides, so that the apk resolver favours py3.12-setuptools
    runtime:
      - python-3.11

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python-3.11
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: 0ff4183f8f42cd8fa3acea16c45205521a4ef28f73c6391d8a25e92893134f2e
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 4021
