package:
  name: py3.10-tensorflow-core
  description: Framework for data-graph oriented computing (core libraries, oneDNN build)
  version: 2.16.1
  epoch: 0
  copyright:
    - license: Apache-2.0
  options:
    no-provides: true
    no-depends: true
  dependencies:
    runtime:
      - python-3.10

environment:
  contents:
    packages:
      - bash
      - bazelisk
      - bazelisk-default
      - build-base
      - c-ares-dev
      - clang-16
      - clang-16-dev
      - coreutils
      - curl-dev
      - gcc-12-default
      - giflib-dev
      - icu-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libstdc++-12
      - libstdc++-12-dev
      - llvm-lld-16-dev
      - llvm16
      - llvm16-dev
      - openjdk-11-default-jdk
      - openssl-dev
      - patchelf
      - perl
      - py3.10-installer
      - py3.10-pip
      - python-3.10
      - python-3.10-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tensorflow
      expected-commit: 5bc9d26649cca274750ad3625bd93422617eed4b
      tag: v${{package.version}}

  - runs: |
      export PYTHON_BIN_PATH=/usr/bin/python
      export TF_PYTHON_VERSION=3.10
      export USE_DEFAULT_PYTHON_LIB_PATH=1
      export TF_NEED_JEMALLOC=1
      export TF_NEED_KAFKA=1
      export TF_NEED_OPENCL_SYCL=0
      export TF_NEED_AWS=1
      export TF_NEED_GCP=1
      export TF_NEED_HDFS=1
      export TF_NEED_S3=1
      export TF_ENABLE_XLA=1
      export TF_NEED_GDR=0
      export TF_NEED_VERBS=0
      export TF_NEED_OPENCL=0
      export TF_NEED_MPI=0
      export TF_NEED_TENSORRT=0
      export TF_NEED_NGRAPH=0
      export TF_NEED_IGNITE=0
      export TF_NEED_ROCM=0
      # Add cython back here when TF is on 3.12
      export TF_SYSTEM_LIBS="boringssl,curl,gif,icu,libjpeg_turbo,nasm,png,zlib"
      export TF_SET_ANDROID_WORKSPACE=0
      export TF_DOWNLOAD_CLANG=0
      export TF_NEED_CUDA=0
      export TF_CUDA_CLANG=0
      export CLANG_CUDA_COMPILER_PATH=/usr/bin/clang
      export CC_OPT_FLAGS="$CFLAGS -O3"

      ./configure

      bazel --bazelrc=.tf_configure.bazelrc build --config=mkl_threadpool --config=opt //tensorflow/tools/pip_package:build_pip_package
      bazel-bin/tensorflow/tools/pip_package/build_pip_package /home/build/pip-pkg-tmp

  - runs: |
      WHEEL_PACKAGE=$(find /home/build/pip-pkg-tmp -name "tensor*.whl")
      pip install --no-cache-dir --root="${{targets.destdir}}" --prefix=/usr $WHEEL_PACKAGE
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

update:
  enabled: true
  github:
    identifier: tensorflow/tensorflow
    strip-prefix: v
    tag-filter: v
