package:
  name: python-3.12
  version: 3.12.2
  epoch: 5
  description: "the Python programming language"
  copyright:
    - license: PSF-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - ca-certificates-bundle
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev

# creates helpfull python3.M and 3.M variables
var-transforms:
  - from: ${{package.name}}
    match: '-'
    replace: ''
    to: python
  - from: ${{package.version}}
    match: (\d).(\d+).(\d+)
    replace: '$1.$2'
    to: pyversion

pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: be28112dac813d2053545c14bf13a16401a21877f1a69eb6ea5d84c4a0f3d870

  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*

  - uses: patch
    with:
      patches: CVE-2023-27043.patch

  - uses: patch
    with:
      patches: CVE-2023-27043-enable-disable.patch

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --with-lto

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +

      cd ${{targets.destdir}}/usr/bin
      rm -f python3 pydoc3 idle3* 2to3*
      rm ${{targets.destdir}}/usr/lib/libpython3.so

      # Drop site-packages README.txt to avoid SCA dep on python3~3.M
      cd ${{targets.destdir}}/usr/lib/${{vars.python}}
      rm site-packages/README.txt
      rmdir site-packages

  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +

      export LD_LIBRARY_PATH="${{targets.destdir}}/usr/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
      ${{targets.destdir}}/usr/bin/${{vars.python}} -m compileall --invalidation-mode=unchecked-hash \
          -r100 ${{targets.destdir}}/usr/lib/

  - uses: strip

test:
  pipeline:
    - runs: |
        ${{vars.python}} CVE-2023-27043-unittest.py

subpackages:
  - name: "${{package.name}}-default"
    description: "${{package.name}} as /usr/bin/python3"
    dependencies:
      provides:
        - python3=${{package.full-version}}
        - python-3=${{package.full-version}}
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ln -sf ${{vars.python}} "${{targets.subpkgdir}}"/usr/bin/python3
          ln -sf pydoc${{vars.pyversion}} "${{targets.subpkgdir}}"/usr/bin/pydoc3
          ln -sf python3 "${{targets.subpkgdir}}"/usr/bin/python

  - name: "${{package.name}}-doc"
    description: "python3 documentation"
    pipeline:
      - uses: split/manpages

  - name: "${{package.name}}-dev"
    description: "python3 development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          # pyconfig.h is needed at runtime... ugh.
          mkdir -p "${{targets.destdir}}"/usr/include/${{vars.python}}
          mv "${{targets.subpkgdir}}"/usr/include/${{vars.python}}/pyconfig.h "${{targets.destdir}}"/usr/include/${{vars.python}}

  - name: "${{package.name}}-dev-default"
    description: "python3 by default with development headers"
    dependencies:
      runtime:
        - ${{package.name}}-dev
        - ${{package.name}}-default
      provides:
        - python3-dev=${{package.full-version}}
        - python-3-dev=${{package.full-version}}

update:
  enabled: true
  shared: true
  github:
    identifier: python/cpython
    strip-prefix: v
    tag-filter: v3.12
    use-tag: true
