package:
  name: R-classInt
  version: 0.4.10
  epoch: 0
  description: Choose Univariate Class Intervals
  copyright:
    - license: GPL-2.0-only OR GPL-3.0-only
  dependencies:
    runtime:
      - R
      - R-e1071

environment:
  contents:
    packages:
      - R
      - R-dev
      - R-e1071
      - busybox

var-transforms:
  - from: ${{package.version}}
    match: ^(.+)\.(\d+)$
    replace: $1-$2
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/classInt
      tag: ${{vars.mangled-package-version}}
      expected-commit: ce973878e5f1d689a2ff6ffcdf8b6cc55d6165e0

  - uses: R/build
    with:
      package: classInt
      version: ${{vars.mangled-package-version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(classInt)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2
  github:
    identifier: cran/classInt
    use-tag: true
