package:
  name: R-DBI
  version: 1.2.2
  epoch: 0
  description: A database interface (DBI) definition for communication between R and RDBMSs
  copyright:
    - license: LGPL-2.1-only
  dependencies:
    runtime:
      - R

environment:
  contents:
    packages:
      - R
      - R-dev
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/DBI
      tag: ${{package.version}}
      expected-commit: a7fd36c9b488f7e6017ce432570cbc58b3f85328

  - uses: R/build
    with:
      package: DBI
      version: ${{package.version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(DBI)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  github:
    identifier: cran/DBI
    use-tag: true
