package:
  name: R-s2
  version: 1.1.6
  epoch: 0
  description: Spherical Geometry Operators Using the S2 Geometry Library
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - R
      - R-wk
      - Rcpp
      - openssl

environment:
  contents:
    packages:
      - R
      - R-dev
      - R-wk
      - Rcpp
      - busybox
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/s2
      tag: ${{package.version}}
      expected-commit: 9b6850b4b7b00b6b1f156904db555c4c3e2a4fc6

  - uses: R/build
    with:
      package: s2
      version: ${{package.version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(s2)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  github:
    identifier: cran/s2
    use-tag: true
