package:
  name: rabbitmq-messaging-topology-operator
  version: 1.13.0
  epoch: 4
  description: Open source RabbitMQ cluster operator. Kubernetes operator to deploy and manage RabbitMQ clusters.
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go
  environment:
    CGO_ENABLED: "0"
    GO111MODULE: "on"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fbe1ad115c96a6818f08415eaa59d6cea9311637
      repository: https://github.com/rabbitmq/messaging-topology-operator
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      output: manager
      packages: .
      tags: timetzdata

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # link /usr/bin/manager to /manager due to hardcoded command
          # See https://github.com/rabbitmq/messaging-topology-operator/blob/main/config/manager/manager.yaml#L24-L25
          mkdir -p ${{targets.subpkgdir}}/
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: rabbitmq/messaging-topology-operator
    strip-prefix: v
