package:
  name: rabbitmq-c
  version: 0.14.0
  epoch: 0
  description: "RabbitMQ C client"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - openssl

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/alanxz/rabbitmq-c
      tag: v${{package.version}}
      expected-commit: 124722b5045baa41a24ce2e2d7c52a47467e7ac0

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: rabbitmq-c-dev
    description: RabbitMQ C client development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: alanxz/rabbitmq-c
    strip-prefix: v
    tag-filter: v
