package:
  name: Rcpp
  version: 1.0.12
  epoch: 0
  description: Seamless R and C++ Integration
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - R

environment:
  contents:
    packages:
      - R
      - R-dev
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/Rcpp
      tag: ${{package.version}}
      expected-commit: 5bbe8d5257d5a9c9479d46752e3d01bd475fd424

  - uses: R/build
    with:
      package: Rcpp
      version: ${{package.version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(Rcpp)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  github:
    identifier: cran/Rcpp
    use-tag: true
