package:
  name: rdfind
  version: "1.6.0"
  epoch: 0
  description: a redundant file finder
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nettle-dev
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7a406e8ef1886a5869655604618dd98f672f12c6a6be4926d053be65070f3279
      uri: "https://rdfind.pauldreik.se/rdfind-${{package.version}}.tar.gz"

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 231641
