package:
  name: redis-7.2
  version: 7.2.4
  epoch: 2
  description: Advanced key-value store
  copyright:
    - license: BSD-3-Clause
  dependencies:
    provides:
      - redis=${{package.full-version}}
    runtime:
      - posix-libc-utils # `getent` is required on startup in ha mode for ip introspection cluster formation

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8d104c26a154b29fd67d6568b4f375212212ad41e0c2caa3d66480e78dbd3b59
      uri: https://download.redis.io/releases/redis-${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 0000-Disable-protected-mode.patch

  - runs: |
      export CFLAGS="$CFLAGS -DUSE_MALLOC_USABLE_SIZE"
        make USE_JEMALLOC=no \
        MALLOC=libc \
        BUILD_TLS=yes \
        all -j$(nproc)
      make install PREFIX=/usr INSTALL_BIN="${{targets.destdir}}/usr/bin"

  - uses: strip

subpackages:
  - name: redis-cli-7.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-cli "${{targets.subpkgdir}}"/usr/bin/redis-cli
    description: redis-cli is the command line interface utility to talk with Redis.
    dependencies:
      provides:
        - redis-cli=${{package.full-version}}

  - name: redis-benchmark-7.2
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/redis-benchmark "${{targets.subpkgdir}}"/usr/bin/redis-benchmark
    description: redis-benchmark utility that simulates running commands done by N clients while at the same time sending M total queries.
    dependencies:
      provides:
        - redis-benchmark=${{package.full-version}}

  - name: redis-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-bitnami-compat=${{package.full-version}}
      runtime:
        - libxcrypt
        - redis
        # Required by startup scripts
        - busybox
        - bash
        - coreutils
        - openssl
        - redis-cli
        - wait-for-port
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis
          version-path: 7.2/debian-12
      - runs: |
          # Bitnami startup scripts _require_ the redis-default.conf to exist
          mkdir -p "${{targets.subpkgdir}}"/opt/bitnami/redis/etc
          cp redis.conf ${{targets.subpkgdir}}/opt/bitnami/redis/etc/redis-default.conf

          ln -s /opt/bitnami/scripts/redis/entrypoint.sh ${{targets.subpkgdir}}/entrypoint.sh
          ln -s /opt/bitnami/scripts/redis/run.sh ${{targets.subpkgdir}}/run.sh

  # redis-sentinel is a symlink to redis-server, but paired with differently named startup scripts in bitnami
  - name: redis-sentinel-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-sentinel-bitnami-compat=${{package.full-version}}
      runtime:
        - redis
        - libxcrypt
        # Required by startup scripts
        - busybox
        - bash
        - coreutils
        - openssl
        - redis-cli
        - wait-for-port
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-sentinel
          version-path: 7.2/debian-12
      - runs: |
          # Bitnami startup scripts _require_ the redis-default.conf to exist
          mkdir -p "${{targets.subpkgdir}}"/opt/bitnami/redis-sentinel/etc
          cp redis.conf ${{targets.subpkgdir}}/opt/bitnami/redis-sentinel/etc/redis-default.conf

  # in bitnami, redis-cluster is redis-server paired with different startup to support cluster mode
  # keep this as a subpackage in redis to avoid confusion
  - name: redis-cluster-7.2-bitnami-compat
    dependencies:
      provides:
        - redis-cluster-bitnami-compat=${{package.full-version}}
      runtime:
        - libxcrypt
        - redis
        # Required by startup scripts
        - busybox
        - bash
        - coreutils
        - openssl
        - redis-cli
        - wait-for-port
    pipeline:
      - uses: bitnami/compat
        with:
          image: redis-cluster
          version-path: 7.2/debian-12
      - runs: |
          # Bitnami startup scripts _require_ the redis-default.conf to exist
          mkdir -p "${{targets.subpkgdir}}"/opt/bitnami/redis-cluster/etc
          cp redis.conf ${{targets.subpkgdir}}/opt/bitnami/redis-cluster/etc/redis-default.conf

update:
  enabled: true
  github:
    identifier: redis/redis

test:
  environment:
    contents:
      packages:
        - redis-cli
  pipeline:
    - runs: |
        cat <<EOF >> /tmp/redis.conf
        dbfilename dump.rdb
        pidfile /tmp/redis_6379.pid
        dir /tmp/
        EOF

        redis-server /tmp/redis.conf &
        sleep 2 # wait for redis to start
        redis-cli SET bike:1 "Process 134" || exit 1
        redis-cli GET bike:1 | grep 'Process 134' || exit 1
        redis-cli exists bike:1 | grep 1 || exit 1
        redis-cli exists bike:2 | grep 0 || exit 1
