package:
  name: restic
  version: 0.16.4
  epoch: 4
  description: restic is a backup program which allows saving multiple revisions of files and directories in an encrypted repository stored on different backends
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/restic/restic/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: d736a57972bb7ee3398cf6b45f30e5455d51266f5305987534b45a4ef505f965

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/restic
      output: restic
      ldflags: "-s -w -X main.version=${{package.version}} -extldflags '-static'"

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/restic ${{targets.subpkgdir}}/restic

update:
  enabled: true
  github:
    identifier: restic/restic
    strip-prefix: v

test:
  pipeline:
    - runs: |
        restic version
