package:
  name: ruby3.2-console
  version: 1.23.6
  epoch: 0
  description: Beautiful logging for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-fiber-local

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: console

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4c9b72ac223db56f455ab27e2eb536bc858cb37a98a3ad5f5e4109b42d343730
      uri: https://github.com/socketry/console/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/console
    strip-prefix: v
    use-tag: true
