package:
  name: ruby3.2-protocol-hpack
  version: 1.4.3
  epoch: 0
  description: A compresssor and decompressor for HTTP 2.0 HPACK.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: protocol-hpack
  # NOTE: http-hpack is required for the gemspec name. It has since been
  # updated to match the standard naming scheme, however it is not in this tag
  gemspec: protocol-hpack

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: dcf0674ccfd82a0aead1a8d55512787d7939b716
      repository: https://github.com/socketry/http-hpack.git
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: patch
        with:
          patches: ../001-remove-signing-key.patch
      - uses: ruby/build
        with:
          # NOTE: See vars.gemspec comment for details
          gem: ${{vars.gemspec}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/http-hpack
    strip-prefix: v
    use-tag: true
