package:
  # fluentd supported versions: https://github.com/fluent/fluentd/blob/master/SECURITY.md
  name: ruby3.2-fluentd-1.16
  version: 1.16.5
  epoch: 0
  description: Fluentd is an open source data collector designed to scale and simplify log management. It can collect, process and ship many kinds of data in near real-time.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-bundler
      - ruby3.2-cool.io
      - ruby3.2-http_parser.rb
      - ruby3.2-msgpack
      - ruby3.2-serverengine
      - ruby3.2-sigdump
      - ruby3.2-strptime
      - ruby3.2-tzinfo
      - ruby3.2-tzinfo-data
      - ruby3.2-webrick
      - ruby3.2-yajl-ruby
    provides:
      - ruby3.2-fluentd=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fluentd

pipeline:
  # This package makes use of `git ls-files` in its gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: 95d130aaa44fc09b14a4e9686ee8018253185fc5
      repository: https://github.com/fluent/fluentd.git
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}

  - uses: ruby/clean

  - runs: |-
      GEM_DIR=${{targets.destdir}}$(ruby -e 'puts Gem.default_dir')/gems/${{vars.gem}}-${{package.version}}
      rm -rf ${GEM_DIR}/test \
             ${GEM_DIR}/docs \
             ${GEM_DIR}/*.md \
             ${GEM_DIR}/.github

subpackages:
  - name: ${{package.name}}-logging-operator-compat
    description: Entrypoint used by the logging operator image
    dependencies:
      runtime:
        - busybox
    pipeline:
      - runs: |
          git clone https://github.com/kube-logging/fluentd-images.git
          cd fluentd-images
          git checkout 773503fd12bcdb75f042ea3deb712ccb86a31d61
          install -Dm755 ./v1.16/entrypoint.sh "${{targets.subpkgdir}}/bin/entrypoint.sh"
          install -Dm755 ./v1.16/healthy.sh "${{targets.subpkgdir}}/bin/healthy.sh"
          install -Dm644 ./v1.16/fluent.conf "${{targets.subpkgdir}}/fluentd/etc/fluent.conf"

update:
  enabled: true
  github:
    identifier: fluent/fluentd
    strip-prefix: v
    tag-filter: v1.16.
