package:
  name: ruby3.2-elasticsearch-api
  version: 8.13.0
  epoch: 0
  description: |
    Ruby API for Elasticsearch. See the `elasticsearch` gem for full integration.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-multi_json

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: elasticsearch-api

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/elasticsearch-ruby.git
      tag: v${{package.version}}
      expected-commit: 3a11380b4f0ad7023e5a18e0f6617aba497c839d

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: elastic/elasticsearch-ruby
    strip-prefix: v
    use-tag: true
    tag-filter: v
