package:
  name: ruby3.2-protocol-http1
  version: 0.19.0
  epoch: 0
  description: A low level implementation of the HTTP/1 protocol.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-protocol-http

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: protocol-http1

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9bb20c9113945097bcad2a8048aa49e43c3d3d350b228cd061a521b16a6da5a5
      uri: https://github.com/socketry/protocol-http1/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/protocol-http1
    strip-prefix: v
    use-tag: true
