package:
  name: ruby3.2-async
  version: 2.10.1
  epoch: 0
  description: A concurrency framework for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-console
      - ruby3.2-io-event
      - ruby3.2-timers

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9d80e9069dfd0e085d2817560c7dee8938943172783cc5a832db89dcb4de3323
      uri: https://github.com/socketry/async/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async
    strip-prefix: v
