package:
  name: rustls-ffi
  version: 0.13.0
  epoch: 0
  description: "C-to-rustls bindings"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rustls/rustls-ffi
      tag: v${{package.version}}
      expected-commit: 5700454570cb1641c18d6f9663086671dc695487

  - runs: |
      # gcc 13 throws extra error, suppress them
      sed -i "s/CFLAGS := -Werror/CFLAGS := -Werror -Wno-maybe-uninitialized/" Makefile

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: rustls/rustls-ffi
    strip-prefix: v
    use-tag: true
