package:
  name: s2n-tls
  version: 1.4.9
  epoch: 0
  description: AWS C99 implementation of the TLS/SSL protocols
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssl-dev
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 08b1318beaf92d933c65ae63d16a584d5d6be85b8324bff6718d71cc6ca79862
      uri: https://github.com/aws/s2n-tls/archive/refs/tags/v${{package.version}}.tar.gz

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        -DUNSAFE_TREAT_WARNINGS_AS_ERRORS=OFF \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: s2n-tls-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/s2n "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - openssl-dev
        - s2n-tls
    description: s2n-tls dev

update:
  enabled: true
  github:
    identifier: aws/s2n-tls
    strip-prefix: v
    use-tag: true
    tag-filter: v
