package:
  name: sbomqs
  version: 0.0.30
  epoch: 2
  description: SBOM quality score - Quality metrics for your sboms
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: go/install
    with:
      package: github.com/interlynk-io/sbomqs
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: interlynk-io/sbomqs
    tag-filter: v
    strip-prefix: v
