package:
  name: scap-security-guide
  version: 0.1.72
  epoch: 1
  description: Security automation content in SCAP, Bash, Ansible, and other formats
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - libxml2-dev
      - openscap
      - pcre2-dev
      - py3-jinja2
      - py3-lxml
      - py3-pandas
      - py3-pyyaml
      - py3-setuptools
      - py3-sphinx
      - python-3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ComplianceAsCode/content
      expected-commit: 7fb44f78bf33232aad587e87a799afcf576f9b47
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      # TODO: RHEL# product suite is not compiling
      opts: |
        -DSSG_ANSIBLE_PLAYBOOKS_ENABLED=False \
        -DSSG_SHELLCHECK_BASH_FIXES_VALIDATION_ENABLED=False \
        -DSSG_BASH_SCRIPTS_ENABLED=False \
        -DSSG_BATS_TESTS_ENABLED=False \
        -DSSG_PRODUCT_RHEL7=False \
        -DSSG_PRODUCT_RHEL8=False \
        -DSSG_PRODUCT_RHEL9=False

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: ComplianceAsCode/content
    strip-prefix: v
