package:
  name: scons
  version: 4.7.0
  epoch: 0
  description: Software construction system
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SCons/scons
      expected-commit: 05f2992377844bbfec9bcd4a9c7f5479c634b91b
      tag: ${{package.version}}

  - uses: fetch
    with:
      uri: https://downloads.sourceforge.net/project/scons/scons/${{package.version}}/SCons-${{package.version}}.tar.gz
      expected-sha256: d9fcd831700ce373ecd30ac55e9d7eff20754215cff5967c4972237d614a326e
      strip-components: 0
      extract: false

  - uses: patch
    with:
      patches: dont-install-manpages.patch

  - runs: |
      tar -xzf SCons-${{package.version}}.tar.gz

      python3 -m gpep517 build-wheel --wheel-dir .dist --output-fd 3 3>&1 >&2
      install -vDm 644 ./SCons-${{package.version}}/*.1 -t "${{targets.destdir}}/usr/share/man/man1/"

      python3 -m installer -d "${{targets.destdir}}" .dist/*.whl
      # remove docbook dirs
      find "${{targets.destdir}}" -name 'docbook' -type d -exec rm -rf {} +

  - uses: strip

subpackages:
  - name: scons-doc
    pipeline:
      - uses: split/manpages
    description: scons manpages

update:
  enabled: true
  github:
    identifier: SCons/scons
