package:
  name: scorecard
  version: 4.13.1
  epoch: 3
  description: OpenSSF Scorecard - Security health metrics for Open Source
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/ossf/scorecard/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: 03e86871efd505247b05a577539ef6f6ce572a99bc89d6921272e6e293dbe94f

  - runs: |
      make build-scorecard
      install -Dm755 ./scorecard "${{targets.destdir}}/usr/bin/scorecard"

  - uses: strip

update:
  enabled: true
  github:
    identifier: ossf/scorecard
    strip-prefix: v
