package:
  name: secrets-store-csi-driver-provider-azure
  version: 1.5.1
  epoch: 3
  description: Azure Key Vault provider for Secret Store CSI driver
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/secrets-store-csi-driver-provider-azure
      tag: v${{package.version}}
      expected-commit: 8d7adb7b4d8c28fdbc10e93fabeb30939e7c8e51

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      unset LDFLAGS
      make build ARCH=$(go env GOARCH)

  - runs: |
      install -Dm755 _output/*/secrets-store-csi-driver-provider-azure "${{targets.destdir}}"/usr/bin/secrets-store-csi-driver-provider-azure

  - uses: strip

update:
  enabled: true
  github:
    identifier: Azure/secrets-store-csi-driver-provider-azure
    strip-prefix: v
    tag-filter: v
