package:
  name: selenium
  version: 4.19.0
  epoch: 0
  description: A browser automation framework and ecosystem.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-11-default-jvm

environment:
  contents:
    packages:
      - bash
      - bazelisk
      - bazelisk-default
      - binutils
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - gnutar
      - openjdk-11
      - openjdk-11-default-jvm
      - python3
      - ruby-3.3
      - tzdata
      - wolfi-baselayout
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SeleniumHQ/selenium
      tag: selenium-${{package.version}}
      expected-commit: 5f9cec8963b33a7708619d666a5ce0b2f6542c7d

  - runs: |
      bazel build grid
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/usr/share/java/${{package.name}}/bin
      install -Dm755 bazel-bin/java/src/org/openqa/selenium/grid/selenium "${{targets.destdir}}"/usr/share/java/${{package.name}}/bin/selenium
      ln -sf /usr/share/java/${{package.name}}/bin/selenium "${{targets.destdir}}"/usr/bin/selenium

  - uses: strip

subpackages:
  - name: selenium-server-standalone
    description: The Selenium Server is needed in order to run Remote Selenium WebDriver (Grid).
    dependencies:
      runtime:
        - openjdk-11-default-jvm
    pipeline:
      - runs: |
          bazel build //java/src/org/openqa/selenium/grid:executable-grid
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/share/java/${{package.name}}/bin
          install -Dm755 bazel-bin/java/src/org/openqa/selenium/grid/selenium "${{targets.subpkgdir}}"/usr/share/java/${{package.name}}/bin/selenium-server-standalone
          ln -sf /usr/share/java/${{package.name}}/bin/selenium-server-standalone "${{targets.subpkgdir}}"/usr/bin/selenium-server-standalone
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - wolfi-base
            - openjdk-11-default-jvm
      pipeline:
        - runs: |
            selenium-server-standalone info

  - name: selenium-server
    description: The Selenium Server is needed in order to run Remote Selenium WebDriver (Grid).
    dependencies:
      runtime:
        - openjdk-11-default-jvm
    pipeline:
      - runs: |
          bazel build //java/src/org/openqa/selenium/grid:selenium_server_deploy.jar
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/share/java/${{package.name}}/bin
          install -Dm755 bazel-bin/java/src/org/openqa/selenium/grid/selenium_server_deploy.jar "${{targets.subpkgdir}}"/usr/share/java/${{package.name}}/bin/selenium_server_deploy.jar
          ln -sf /usr/share/java/${{package.name}}/bin/selenium_server_deploy.jar "${{targets.subpkgdir}}"/usr/bin/selenium-server
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - wolfi-base
            - openjdk-11-default-jvm
      pipeline:
        - runs: |
            java -jar /usr/bin/selenium-server

  - name: selenium-server-compat
    description: "Compatibility package to place binaries in the location expected by docker-selenium"
    dependencies:
      runtime:
        - selenium-server
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opt/selenium
          ln -sf /usr/share/java/${{package.name}}/bin/selenium_server_deploy.jar "${{targets.subpkgdir}}"/opt/selenium/selenium-server.jar
      - uses: strip

test:
  environment:
    contents:
      packages:
        - openjdk-11-default-jvm
  pipeline:
    - runs: |
        selenium info

update:
  enabled: true
  ignore-regex-patterns:
    - -ruby
    - -dotnet
    - -python
    - -java
    - -javascript
    - nightly
  github:
    identifier: SeleniumHQ/selenium
    use-tag: true
    strip-prefix: selenium-
