package:
  name: shadowsocks-rust
  version: 1.18.2
  epoch: 3
  description: A Rust port of shadowsocks
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - glibc-dev
      - rust
      - rustup

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/shadowsocks/shadowsocks-rust
      tag: v${{package.version}}
      expected-commit: dcdeca032cad409d1ad133abeafa0270bb32a945

  - name: Configure
    runs: |
      rustup override set stable
      rustup target add "${{host.triplet.rust}}"

  - runs: |
      cargo build --target "${{host.triplet.rust}}" --release --features "local-tun local-redir stream-cipher aead-cipher-2022"
      install -Dm644 examples/config.json "${{targets.destdir}}"/etc/shadowsocks-rust/config.json
      install -Dm755 docker/docker-entrypoint.sh "${{targets.destdir}}"/usr/bin/docker-entrypoint.sh

  - uses: strip

data:
  - name: components
    items:
      sslocal: sslocal
      ssmanager: ssmanager
      ssserver: ssserver
      ssservice: ssservice
      ssurl: ssurl

subpackages:
  - range: components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/bin/
          install -Dm755 target/${{host.triplet.rust}}/release/${{range.key}} "${{targets.contextdir}}"/usr/bin/
    dependencies:
      runtime:
        - shadowsocks-rust
        - busybox # The entrypoint script uses `#!/bin/sh`
    test:
      pipeline:
        - runs: ${{range.key}} --version

test:
  environment:
    contents:
      packages:
        - shadowsocks-rust-sslocal
        - shadowsocks-rust-ssserver
  pipeline:
    - runs: |
        for bin in sslocal ssserver; do
          echo "Starting $bin"
          nohup $bin > $bin.out 2> $bin.err < /dev/null &
          pid=$!
          sleep 3

          if ! (cat $bin.out $bin.err | grep "listening on"); then
            echo "Could not find expected 'listening on' log message in '$bin' output!"
            cat $bin.out
            cat $bin.err
            exit 1
          fi

          echo "Stopping $bin"
          kill $pid
          sleep 3
        done

update:
  enabled: true
  github:
    identifier: shadowsocks/shadowsocks-rust
    strip-prefix: v
