package:
  name: skopeo
  version: 1.15.0
  epoch: 2
  description: Work with remote images registries - retrieving information, images, signing content
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      expected-sha256: f219d31e5f3742b08a6e7327d84fd84cdcf8e5a297914bb6e19a96fef1b19b76
      uri: https://github.com/containers/skopeo/archive/v${{package.version}}/v${{package.version}}.tar.gz

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v25.0.5

  - runs: |
      CGO_ENABLED=0 go build -mod=vendor \
        -tags "exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp" \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/skopeo" ./cmd/skopeo

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 9216
