package:
  name: slsa-verifier
  version: 2.5.1
  epoch: 1
  description: Verify provenance from SLSA compliant builders
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: go/install
    with:
      package: github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v${{package.version}}

update:
  enabled: true
  github:
    identifier: slsa-framework/slsa-verifier
    strip-prefix: v
