package:
  name: snappy
  version: 1.2.0
  epoch: 0
  description: Fast compression and decompression library
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/google/snappy/archive/${{package.version}}.tar.gz
      expected-sha256: 9b8f10fbb5e3bc112f2e5e64f813cb73faea42ec9c533a5023b5ae08aedef42e

  - uses: patch
    with:
      patches: cmakelists.patch rtti.patch

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_STATIC_LIBS=ON \
        -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
        -DCMAKE_C_FLAGS="$CFLAGS" \
        -DSNAPPY_BUILD_BENCHMARKS=OFF \
        -DSNAPPY_BUILD_TESTS=OFF
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

      for file in AUTHORS CONTRIBUTING.md COPYING NEWS README.md \
        format_description.txt framing_format.txt; do
        install -m644 -D $file "${{targets.destdir}}"/usr/share/doc/snappy/$file
      done

  - uses: strip

subpackages:
  - name: snappy-static
    pipeline:
      - uses: split/static
    description: snappy static

  - name: snappy-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - snappy
    description: snappy dev

  - name: "snappy-doc"
    description: "snappy documentation"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/snappy

          for file in AUTHORS CONTRIBUTING.md COPYING NEWS README.md \
            format_description.txt framing_format.txt; do
            mv "${{targets.destdir}}"/usr/share/doc/snappy/$file "${{targets.subpkgdir}}"/usr/share/doc/snappy/$file
          done

update:
  enabled: true
  github:
    identifier: google/snappy
    strip-prefix: v
