package:
  name: spark-operator
  version: 1.1.27
  epoch: 21
  description: Kubernetes operator for managing the lifecycle of Apache Spark applications on Kubernetes.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - procps

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - tini

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator
      tag: spark-operator-chart-${{package.version}}
      expected-commit: bd2eda216b79733c992861f257b28dad36bb4c62

  - runs: |
      # Remediate GHSA-8mjg-8c8g-6h85 drop v1.19.5 to upgrade kubernetes version accordingly.
      go mod edit -dropreplace k8s.io/kubernetes

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 golang.org/x/crypto@v0.17.0 k8s.io/kubernetes@v1.25.16 google.golang.org/protobuf@v1.33.0
      replaces: golang.org/x/crypto=golang.org/x/crypto@v0.17.0
      show-diff: true

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      go build -trimpath -ldflags "-w" -o ${{targets.destdir}}/usr/bin/spark-operator .

  - uses: strip

subpackages:
  - name: "sparkctl"
    pipeline:
      - runs: |
          cd sparkctl
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          go build -trimpath -ldflags "-w" -buildvcs=false -o ${{targets.subpkgdir}}/usr/bin/sparkctl .
      - uses: strip

  - name: spark-operator-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          cp hack/gencerts.sh  ${{targets.subpkgdir}}/usr/bin/
          chmod 0755 ${{targets.subpkgdir}}/usr/bin/gencerts.sh
          cp entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
          chmod 0755 ${{targets.subpkgdir}}/usr/bin/entrypoint.sh
          # entrypoints expects tini to be on /sbin/tini
          # https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/entrypoint.sh#LL27C5-L27C19
          ln -s /sbin/tini ${{targets.subpkgdir}}/usr/bin/tini
    dependencies:
      runtime:
        - openssl
        - tini
        - posix-libc-utils
        - coreutils

update:
  enabled: true
  github:
    identifier: GoogleCloudPlatform/spark-on-k8s-operator
    strip-prefix: spark-operator-chart-
    use-tag: true
    tag-filter: "spark-operator-chart-"
