package:
  name: speedtest-go
  version: 1.6.10
  epoch: 2
  description: CLI and Go API to Test Internet Speed using speedtest.net
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/showwin/speedtest-go
      expected-commit: d89d3069c6fa6c6c8e993321f9786b851a772635
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: speedtest-go
      ldflags: -s -w

test:
  pipeline:
    - runs: speedtest-go

update:
  enabled: true
  github:
    identifier: showwin/speedtest-go
    strip-prefix: v
    tag-filter: v
