package:
  name: src
  version: 5.3.0
  epoch: 3
  description: Sourcegraph CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sourcegraph/src-cli
      expected-commit: 180d4e089567537abee759780ab9978f821fbbdb
      tag: ${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/jackc/pgproto3/v2@v2.3.3 google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4 github.com/jackc/pgconn@v1.14.3

  - uses: go/build
    with:
      packages: ./cmd/src
      output: src
      ldflags: "-s -w -X github.com/sourcegraph/src-cli/internal/version.BuildTag=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: sourcegraph/src-cli
