package:
  name: stakater-reloader
  version: 1.0.76
  epoch: 0
  description: A Kubernetes controller to watch changes in ConfigMap and Secrets and do rolling upgrades on Pods
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stakater/Reloader
      tag: v${{package.version}}
      expected-commit: 9e7fca4c29b5f65bbdffa89fb313cb3170dc618c

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: manager
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: stakater-reloader-compat
    description: compatibility symlinks package for stakater-reloader helm charts
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p ${{targets.subpkgdir}}
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: stakater/Reloader
    strip-prefix: v
    use-tag: true
