package:
  name: step-kms-plugin
  version: 0.11.0
  epoch: 1
  description: step plugin to manage keys and certificates on a cloud KMSs and HSMs
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "1"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/step-kms-plugin
      tag: v${{package.version}}
      expected-commit: 8a8df7d6db18e8e09a92e3767220e519690f5f1f

  - uses: go/build
    with:
      packages: ./cmd
      output: step-kms-plugin
      ldflags: -w -X "main.Version=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: smallstep/step-kms-plugin
    strip-prefix: v
