package:
  name: step-ca
  version: 0.26.0
  epoch: 1
  description: A private certificate authority (X.509 & SSH) & ACME server for secure automated certificate management, so you can use TLS everywhere & SSO for SSH.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/certificates
      tag: v${{package.version}}
      expected-commit: 395a3eeb93e312cf00f8149f7c5ee55e2cfa6e4a

  - runs: |
      CGO_ENABLED=0 go build -v \
        -ldflags='-w -X "main.Version=${{package.version}}"' \
        -o "${{targets.destdir}}/usr/bin/step-ca" ./cmd/step-ca

  - uses: strip

update:
  enabled: true
  github:
    identifier: smallstep/certificates
    strip-prefix: v
