package:
  name: step
  version: 0.26.0
  epoch: 1
  description: A zero trust swiss army knife for working with X509, OAuth, JWT, OATH OTP, etc.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/smallstep/cli
      tag: v${{package.version}}
      expected-commit: 05f95e5b1e9110ea0235dbd4346329fc5aa57eff

  - uses: go/build
    with:
      packages: ./cmd/step
      output: step
      ldflags: -s -w -X main.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: smallstep/cli
    strip-prefix: v
