package:
  name: stern
  version: 1.28.0
  epoch: 0
  description: Multi pod and container log tailing for Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stern/stern
      tag: v${{package.version}}
      expected-commit: 9763d953d86d8f60cf9a5e5da3531e6a1aa47c5c

  - uses: go/bump
    with:
      # Mitigates GHSA-8r3f-844c-mc37
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: stern
      ldflags: -s -w -X github.com/stern/stern/cmd.version=v${{package.version}} -X github.com/stern/stern/cmd.commit=$(git rev-parse HEAD) -X github.com/stern/stern/cmd.date=$(date +%F-%T)

  - uses: strip

update:
  enabled: true
  github:
    identifier: stern/stern
    strip-prefix: v

test:
  pipeline:
    - runs: |
        stern --version
