package:
  name: strace
  version: "6.8"
  epoch: 0
  description: Diagnostic, debugging and instructional userspace tracer
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binutils-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      # - elfutils-dev TODO
      - gawk

pipeline:
  - uses: fetch
    with:
      expected-sha256: ba6950a96824cdf93a584fa04f0a733896d2a6bc5f0ad9ffe505d9b41e970149
      uri: https://github.com/strace/strace/releases/download/v${{package.version}}/strace-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --enable-mpers=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: strace-doc
    pipeline:
      - uses: split/manpages
    description: strace manpages

update:
  enabled: true
  github:
    identifier: strace/strace
    strip-prefix: v
