package:
  name: supercronic
  version: 0.2.29
  epoch: 2
  description: Cron for containers
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - go

pipeline:
  - uses: go/install
    with:
      package: github.com/aptible/supercronic@v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: aptible/supercronic
    strip-prefix: v
