package:
  name: surrealdb
  version: 1.3.1
  epoch: 0
  description: "A scalable, distributed, collaborative, document-graph database, for the realtime web"
  copyright:
    - license: BUSL-1.1

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - clang-17-dev
      - patch
      - rust
      - rustup
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/surrealdb/surrealdb
      tag: v${{package.version}}
      expected-commit: c065ee38b542f53c1addef0543c7fc01670dd3fa

  - name: Configure and build
    runs: |
      rustup install stable
      rustup target add x86_64-unknown-linux-gnu
      rustup target add aarch64-unknown-linux-gnu

      # This is a bit of a hack, but it's the easiest way to get the right version of rustc and cargo in the path.
      export PATH="$HOME/.rustup/toolchains/stable-${{host.triplet.rust}}/bin:$PATH"

      if [ "${{build.arch}}" = "aarch64" ]; then
          echo '[build]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+fp16"]' >> .cargo/config
      fi

      cargo build --release

      install -Dm755 target/release/surreal ${{targets.destdir}}/usr/bin/surreal

  - uses: strip

update:
  enabled: true
  github:
    identifier: surrealdb/surrealdb
    strip-prefix: v

test:
  pipeline:
    - name: Verify SurrealDB binary presence
      runs: |
        surreal --version
    - name: Start SurrealDB server
      runs: |
        surreal start memory &
    - name: Basic CRUD operations
      runs: |
        echo "CREATE person SET name = 'John Doe', age = 30;" | surreal sql --namespace testns --database testdb
        echo "SELECT * FROM person;" | surreal sql --namespace testns --database testdb | grep -qi "John Doe"
        echo "UPDATE person SET age = 31 WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb
        echo "SELECT * FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb | grep -qi "31"
        echo "DELETE FROM person WHERE name = 'John Doe';" | surreal sql --namespace testns --database testdb
