package:
  name: swagger
  version: 0.30.5
  epoch: 1
  description: Swagger 2.0 implementation for go
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/go-swagger/go-swagger
      tag: v${{package.version}}
      expected-commit: ab6a7885723430004f1d7db6395369b6e7f3370b

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - uses: go/build
    with:
      packages: ./cmd/swagger
      output: swagger

  - uses: strip

update:
  enabled: true
  github:
    identifier: go-swagger/go-swagger
    strip-prefix: v

test:
  pipeline:
    - runs: |
        swagger version
