package:
  name: tailscale
  version: 1.62.1
  epoch: 1
  description: The easiest, most secure way to use WireGuard and 2FA.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2827330c6adacd9a67940621b5f05b589527c550
      repository: https://github.com/tailscale/tailscale
      tag: v${{package.version}}

  - runs: |
      ./build_dist.sh tailscale.com/cmd/tailscale
      ./build_dist.sh tailscale.com/cmd/tailscaled

  - runs: |
      install -Dm755 ${{package.name}} ${{targets.destdir}}/usr/bin/tailscale
      install -Dm755 ${{package.name}}d ${{targets.destdir}}/usr/sbin/tailscaled

  - uses: strip

update:
  enabled: true
  github:
    identifier: tailscale/tailscale
    strip-prefix: v
