package:
  name: task
  version: 3.35.1
  epoch: 2
  description: A task runner / simpler Make alternative written in Go
  copyright:
    - license: MIT
      paths:
        - "*"

pipeline:
  - uses: go/install
    with:
      package: github.com/go-task/task/v3/cmd/task@v${{package.version}}

update:
  enabled: true
  github:
    identifier: go-task/task
    strip-prefix: v
