package:
  name: tctl
  version: 1.18.0
  epoch: 14
  description: Temporal CLI
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/tctl
      tag: v${{package.version}}
      expected-commit: aed2d9e1cb8bba6f69d5463fa286eb0389149ee4

  - uses: go/bump
    with:
      deps: go.temporal.io/server@v1.20.0 golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 google.golang.org/protobuf@v1.33.0

  - runs: |
      make build
      install -Dm755 tctl ${{targets.destdir}}/usr/bin/tctl

  - uses: strip

subpackages:
  - name: tctl-compat
    description: Compat package for tctl
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/tctl "${{targets.subpkgdir}}"/usr/local/bin

  - name: tctl-authorization-plugin
    description: "sub package for tctl-authorization-plugin"
    pipeline:
      - runs: |
          # CVE-2023-3485
          go get go.temporal.io/server@v1.20.0

          # CVE-2023-3978, CVE-2023-39325, CVE-2023-44487
          go get golang.org/x/net@v0.17.0

          # GHSA-m425-mq94-257g
          go get google.golang.org/grpc@v1.56.3

          go mod tidy

          make build

          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          install -Dm755 tctl-authorization-plugin ${{targets.contextdir}}/usr/bin/tctl-authorization-plugin
      - uses: strip

  - name: tctl-authorization-plugin-compat
    description: "Compat package for tctl-authorization-plugin"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/tctl-authorization-plugin "${{targets.subpkgdir}}"/usr/local/bin
      - uses: strip

update:
  enabled: true
  github:
    identifier: temporalio/tctl
    strip-prefix: v
