package:
  name: telegraf-1.30
  version: 1.30.1
  epoch: 1
  description: Telegraf is an agent for collecting, processing, aggregating, and writing metric
  copyright:
    - license: MIT
  dependencies:
    provides:
      - telegraf=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gnutar
      - go

pipeline:
  - uses: git-checkout
    with:
      tag: v${{package.version}}
      expected-commit: fb76952e1ed35eb833f67909164cb99f5e98d7fa
      repository: https://github.com/influxdata/telegraf

  - if: ${{build.arch}} == 'x86_64'
    runs: |
      make package include_packages="linux_amd64.tar.gz"

  - if: ${{build.arch}} == 'aarch64'
    runs: |
      make package include_packages="linux_arm64.tar.gz"

  - runs: |
      tar -xf build/dist/telegraf-${{package.version}}*.tar.gz
      mkdir -p ${{targets.destdir}}/etc/
      mv telegraf-${{package.version}}/etc/* ${{targets.destdir}}/etc/

      mkdir -p ${{targets.destdir}}/usr/
      mv telegraf-${{package.version}}/usr/* ${{targets.destdir}}/usr

      mkdir -p ${{targets.destdir}}/var
      mv telegraf-${{package.version}}/var/* ${{targets.destdir}}/var

  - uses: strip

update:
  enabled: true
  github:
    identifier: influxdata/telegraf
    strip-prefix: v
    tag-filter: v1.30.
    use-tag: true
