package:
  name: temporal
  version: 0.11.0
  epoch: 3
  description: Command-line interface for running Temporal Server and interacting with Workflows, Activities, Namespaces, and other parts of Temporal
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/temporalio/cli
      tag: v${{package.version}}
      expected-commit: 7267df668277a9b43c50d454af50ff5e2b9f8e90

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0 github.com/golang/protobuf@v1.5.4

  - uses: go/build
    with:
      packages: ./cmd/temporal
      output: temporal
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: temporal-docgen
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/docgen
          output: temporal-docgen
          ldflags: -s -w
      - uses: strip

  - name: temporal-compat
    description: "Compat package for temporal"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/temporal "${{targets.contextdir}}"/usr/local/bin

update:
  enabled: true
  github:
    identifier: temporalio/cli
    strip-prefix: v
