package:
  name: tensorflow-core
  description: Framework for data-graph oriented computing (core libraries, oneDNN build)
  version: 2.13.0
  epoch: 2
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - bazel-5
      - build-base
      - c-ares-dev
      - coreutils
      - curl-dev
      - cython~0
      - giflib-dev
      - icu-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - llvm16-dev
      - openjdk-11-default-jdk
      - openssl-dev
      - patchelf
      - perl
      - py3-gpep517
      - py3-installer
      - py3-keras-applications
      - py3-keras-preprocessing
      - py3-packaging
      - py3-pybind11
      - py3-pybind11-dev
      - py3-requests
      - py3-setuptools
      - py3-wheel
      - python-3-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tensorflow/tensorflow
      expected-commit: 1cb1a030a62b169d90d34c747ab9b09f332bf905
      tag: v${{package.version}}

  # Allow tensorflow to build with any version of Bazel we want.
  - runs: |
      echo "*" > .bazelversion

  - uses: patch
    with:
      series: series

  # Remove version constraints from the Python module setup script.
  - runs: |
      sed -i -E "s/'([0-9a-z_-]+) .= [0-9].+[0-9]'/'\1'/" tensorflow/tools/pip_package/setup.py

  - runs: |
      export PYTHON_BIN_PATH=/usr/bin/python
      export USE_DEFAULT_PYTHON_LIB_PATH=1
      export TF_NEED_JEMALLOC=1
      export TF_NEED_KAFKA=1
      export TF_NEED_OPENCL_SYCL=0
      export TF_NEED_AWS=1
      export TF_NEED_GCP=1
      export TF_NEED_HDFS=1
      export TF_NEED_S3=1
      export TF_ENABLE_XLA=1
      export TF_NEED_GDR=0
      export TF_NEED_VERBS=0
      export TF_NEED_OPENCL=0
      export TF_NEED_MPI=0
      export TF_NEED_TENSORRT=0
      export TF_NEED_NGRAPH=0
      export TF_NEED_IGNITE=0
      export TF_NEED_ROCM=0
      export TF_SYSTEM_LIBS="boringssl,curl,cython,gif,icu,libjpeg_turbo,nasm,png,pybind11,zlib"
      export TF_SET_ANDROID_WORKSPACE=0
      export TF_DOWNLOAD_CLANG=0
      export CC=gcc
      export CXX=g++
      export HOST_C_COMPILER=/usr/bin/${CC}
      export HOST_CXX_COMPILER=/usr/bin/${CXX}
      export TF_NEED_CUDA=0
      export TF_CUDA_CLANG=0
      export CLANG_CUDA_COMPILER_PATH=/usr/bin/clang
      export CC_OPT_FLAGS="$CFLAGS -O3"

      ./configure
      bazel \
        build \
        --config=mkl_threadpool -c opt \
        //tensorflow:libtensorflow.so \
        //tensorflow:libtensorflow_cc.so \
        //tensorflow:install_headers \
        //tensorflow/tools/pip_package:build_pip_package
      bazel-bin/tensorflow/tools/pip_package/build_pip_package /home/build/pip-pkg-tmp

  - runs: |
      install -d "${{targets.destdir}}"/usr/include/tensorflow
      cp -r bazel-bin/tensorflow/include/* "${{targets.destdir}}"/usr/include/tensorflow/

      WHEEL_PACKAGE=$(find /home/build/pip-pkg-tmp -name "tensor*.whl")
      python -m installer --destdir="${{targets.destdir}}" $WHEEL_PACKAGE

      _pyver=$(python -c 'import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))')
      _srch_path="${{targets.destdir}}/usr/lib/python"$_pyver"/site-packages/tensorflow/include"
      cp -rf "${_srch_path}"/* "${{targets.destdir}}"/usr/include/tensorflow/
      _pkgver=${{package.version}}

      tensorflow/c/generate-pc.sh --prefix=/usr --version=${_pkgver}
      sed -e 's@/include$@/include/tensorflow@' -i tensorflow.pc -i tensorflow_cc.pc
      install -Dm644 tensorflow.pc "${{targets.destdir}}"/usr/lib/pkgconfig/tensorflow.pc
      install -Dm644 tensorflow_cc.pc "${{targets.destdir}}"/usr/lib/pkgconfig/tensorflow_cc.pc

      install -Dm755 bazel-bin/tensorflow/libtensorflow.so "${{targets.destdir}}"/usr/lib/libtensorflow.so.${_pkgver}
      ln -s libtensorflow.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow.so.${_pkgver:0:1}
      ln -s libtensorflow.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow.so

      install -Dm755 bazel-bin/tensorflow/libtensorflow_cc.so "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so.${_pkgver}
      ln -s libtensorflow_cc.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so.${_pkgver:0:1}
      ln -s libtensorflow_cc.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow_cc.so

      install -Dm755 bazel-bin/tensorflow/libtensorflow_framework.so "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so.${_pkgver}
      ln -s libtensorflow_framework.so.${_pkgver} "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so.${_pkgver:0:1}
      ln -s libtensorflow_framework.so.${_pkgver:0:1} "${{targets.destdir}}"/usr/lib/libtensorflow_framework.so

      install -Dm644 tensorflow/c/c_api.h "${{targets.destdir}}"/usr/include/tensorflow/tensorflow/c/c_api.h
      install -Dm644 LICENSE "${{targets.destdir}}"/usr/share/licenses/${pkgname}/LICENSE

  - uses: strip

subpackages:
  - name: py3-tensorflow-core
    description: Tensorflow Python API
    dependencies:
      provides:
        - so:libbfloat16.so.so=0
    pipeline:
      - runs: |
          _pyver=$(python -c 'import sys; print(str(sys.version_info[0]) + "." + str(sys.version_info[1]))')
          _pypath="/usr/lib/python${_pyver}"
          mkdir -p "${{targets.contextdir}}"/usr/lib
          mkdir -p "${{targets.contextdir}}"/usr/bin
          mv "${{targets.destdir}}"${_pypath} "${{targets.contextdir}}"${_pypath}
          mv "${{targets.destdir}}"/usr/bin "${{targets.contextdir}}"/usr/bin
          find "${{targets.contextdir}}"${_pypath} -name "libtensorflow*.so*" -exec rm -rf '{}' +

  - name: tensorflow-dev
    description: Tensorflow development headers
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: tensorflow/tensorflow
    strip-prefix: v
    tag-filter: v
