package:
  name: terraform
  version: 1.5.7
  epoch: 6
  copyright:
    - license: MPL-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform
      tag: v${{package.version}}
      expected-commit: ee58ac1851c8a433005df9863ed47796a9f6b5e7

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/grpc@v1.56.3 golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: terraform
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: terraform-compat
    description: Compat package for terraform
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/terraform "${{targets.subpkgdir}}"/usr/local/bin

  - name: terraform-local-provider-config
    description: Configure Terraform to use local providers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/terraform/provider-mirror
          cat > "${{targets.subpkgdir}}"/terraform/.terraformrc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/terraform/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF

update:
  enabled: false
