package:
  name: terraform-docs
  version: 0.17.0
  epoch: 3
  description: Generate documentation from Terraform modules in various output formats
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/terraform-docs/terraform-docs
      tag: v${{package.version}}
      expected-commit: 795d369fdcfbadef3cfca311be03135f794998c5

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0

  - uses: go/build
    with:
      packages: .
      output: terraform-docs

test:
  pipeline:
    - runs: ls -lh /usr/bin && terraform-docs --help

update:
  enabled: true
  github:
    identifier: terraform-docs/terraform-docs
    strip-prefix: v
    tag-filter: v
