package:
  name: terraform-provider-google
  version: 5.23.0
  epoch: 1
  description: Terraform GCP provider
  copyright:
    - license: MPL-2.0
  dependencies:
    runtime:
      - terraform
      - terraform-compat
      - terraform-local-provider-config

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform-provider-google
      tag: v${{package.version}}
      expected-commit: 2fe5399a736c3badf67b223ed2765fbf8a715548

  - uses: go/build
    with:
      packages: .
      output: terraform-provider-google
      ldflags: -s -w

  - runs: |
      GOARCH=$(go env GOARCH)
      mkdir -p "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/google/${{package.version}}/linux_${GOARCH}/
      ln -s "${{targets.destdir}}"/usr/bin/terraform-provider-google \
          "${{targets.destdir}}"/terraform/provider-mirror/registry.terraform.io/hashicorp/google/${{package.version}}/linux_${GOARCH}/terraform-provider-google_v${{package.version}}_x5

update:
  enabled: true
  github:
    identifier: hashicorp/terraform-provider-google
    strip-prefix: v
