package:
  name: tflint
  version: 0.50.3
  epoch: 3
  description: A Pluggable Terraform Linter
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e34bda7f398c139d7bc528261ee96998c10e79c8
      repository: https://github.com/terraform-linters/tflint
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv dist/tflint ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: terraform-linters/tflint
    use-tag: true
    strip-prefix: v
