package:
  name: thanos
  version: 0.34.1
  epoch: 3
  description: Highly available Prometheus setup with long term storage capabilities.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - curl
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4cf1559998bf6d8db3f9ca0fde2a00d217d4e23e
      repository: https://github.com/thanos-io/thanos
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 google.golang.org/protobuf@v1.33.0

  - runs: |
      make build

  - runs: |
      install -Dm755 "$(go env GOPATH)"/bin/thanos "${{targets.destdir}}"/usr/bin/thanos

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - rc*
  github:
    identifier: thanos-io/thanos
    strip-prefix: v
    tag-filter: v
