package:
  name: tigerbeetle
  version: 0.15.3
  epoch: 0
  description: "The distributed financial accounting database designed for mission critical safety and performance."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - zig

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tigerbeetledb/tigerbeetle
      tag: ${{package.version}}
      expected-commit: 73bbc1a32ba2513e369764680350c099fe302285

  - runs: |
      # cpu values from here: https://github.com/tigerbeetle/tigerbeetle/blob/2ab9fd620e53a6d61cb119e48ece4008bedd777d/tools/docker/Dockerfile#L30C79-L30C92
      if [ ${{build.arch}} == 'aarch64' ]; then
        zig build -Drelease -Dcpu=baseline+aes+neon
      elif [ ${{build.arch}} == 'x86_64' ]; then
        zig build -Drelease -Dcpu=x86_64_v3+aes
      fi

      mkdir -p ${{targets.destdir}}/usr/bin
      mv zig-out/bin/tigerbeetle ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: tigerbeetledb/tigerbeetle
    strip-prefix: v
    use-tag: true
    # There are some prereleases with a weird WEEKLY format.
    tag-filter: 0.
