package:
  name: timoni
  version: 0.20.0
  epoch: 4
  description: Timoni is a package manager for Kubernetes, powered by CUE and inspired by Helm.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/stefanprodan/timoni
      tag: v${{package.version}}
      expected-commit: 7f033d917314b4c0fa27e010ab04e35637c8405f

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9

  - uses: go/build
    with:
      packages: ./cmd/timoni
      output: timoni
      ldflags: -s -w -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: stefanprodan/timoni
    strip-prefix: v
    use-tag: true
    tag-filter: v
