package:
  name: tini
  version: 0.19.0
  epoch: 0
  description: A tiny but valid init for containers
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - samurai
pipeline:
  - uses: fetch
    with:
      expected-sha256: 0fd35a7030052acd9f58948d1d900fe1e432ee37103c5561554408bdac6bbf0d
      uri: https://github.com/krallin/tini/archive/v${{package.version}}.tar.gz
  - runs: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=None
    with:
      opts: CFLAGS="$CFLAGS -DPR_SET_CHILD_SUBREAPER=36 -DPR_GET_CHILD_SUBREAPER=37"
  - runs: cmake --build build --target all tini-static
    with:
      opts: CFLAGS="$CFLAGS -DPR_SET_CHILD_SUBREAPER=36 -DPR_GET_CHILD_SUBREAPER=37"

  - runs: |
      install -Dm755 build/tini ${{targets.destdir}}/sbin/tini

subpackages:
  - name: tini-static
    pipeline:
      - runs: install -Dm755 build/tini-static ${{targets.subpkgdir}}/sbin/tini-static

    description: Static build of tini
