package:
  name: tomcat-10.1
  version: 10.1.20
  epoch: 0
  description: Apache Tomcat Web Server
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - tomcat=${{package.full-version}}

environment:
  contents:
    packages:
      - ant
      - build-base
      - busybox
      - ca-certificates-bundle
      - openjdk-17
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/tomcat
      tag: ${{package.version}}
      expected-commit: ab4d890c6fa7be3f910370f00fb5c7f10152e21c

  - runs: |
      cat <<EOF > build.properties
      skip.installer=true
      base.path=$PWD
      compile.debug=false
      EOF

  - runs: |
      ant

      mkdir -p ${{targets.destdir}}/usr/share/tomcat/bin
      cp output/build/bin/* ${{targets.destdir}}/usr/share/tomcat/bin

      mkdir -p ${{targets.destdir}}/usr/share/tomcat/conf
      cp output/build/conf/* ${{targets.destdir}}/usr/share/tomcat/conf

      mkdir -p ${{targets.destdir}}/usr/share/tomcat/lib
      cp output/build/lib/* ${{targets.destdir}}/usr/share/tomcat/lib

      mkdir -p ${{targets.destdir}}/usr/share/tomcat/logs
      mkdir -p ${{targets.destdir}}/usr/share/tomcat/temp
      mkdir -p ${{targets.destdir}}/usr/share/tomcat/webapps

update:
  enabled: true
  ignore-regex-patterns:
    - '-M\d+$'
  github:
    identifier: apache/tomcat
    use-tag: true
    tag-filter: 10.1.
