package:
  name: traefik
  version: 2.11.0
  epoch: 6
  description: The Cloud Native Application Proxy
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0c8778639a3cade0cf73aa26f56f822a4fb835e8
      repository: https://github.com/traefik/traefik
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9 github.com/quic-go/quic-go@v0.42.0

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      TAG_NAME=$(git tag -l --contains HEAD)
      SHA=$(git rev-parse HEAD)
      VERSION_GIT=$(if [ -n "$TAG_NAME" ]; then echo "$TAG_NAME"; else echo "$SHA"; fi)
      VERSION=$(if [ -n "$VERSION" ]; then echo "$VERSION"; else echo "$VERSION_GIT"; fi)

      GOOS=$(go env GOOS) GOARCH=$(go env GOARCH)
      DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')

      CGO_ENABLED=0 GOGC=off GOOS=${GOOS} GOARCH=${GOARCH} go build  -ldflags "-s -w \
      -X github.com/traefik/traefik/v2/pkg/version.Version=$VERSION \
      -X github.com/traefik/traefik/v2/pkg/version.Codename=$CODENAME \
      -X github.com/traefik/traefik/v2/pkg/version.BuildDate=$DATE" \
      -installsuffix nocgo -o "${{targets.destdir}}"/usr/bin/ ./cmd/traefik
      go version -m "${{targets.destdir}}"/usr/bin/traefik

update:
  enabled: true
  github:
    identifier: traefik/traefik
    strip-prefix: v

test:
  pipeline:
    - runs: |
        traefik version
