package:
  name: tree
  version: 2.1.1
  epoch: 1
  description: A recursive directory indented listing of files
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: bcd2a0327ad40592a9c43e09a4d2ef834e6f17aa9a59012a5fb1007950b5eced
      uri: https://gitlab.com/OldManProgrammer/unix-tree/-/archive/${{package.version}}/unix-tree-${{package.version}}.tar.gz

  - uses: autoconf/make

  - runs: |
      make PREFIX="${{targets.destdir}}/usr" \
        MANDIR="${{targets.destdir}}/usr/share/man" \
        install

  - uses: strip

subpackages:
  - name: tree-doc
    pipeline:
      - uses: split/manpages
    description: tree manpages

update:
  enabled: true
  release-monitor:
    identifier: 5006
