package:
  name: typescript
  version: 5.4.4
  epoch: 0
  description: "TypeScript is a superset of JavaScript that compiles to clean JavaScript output."
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - curl
      - git
      - nodejs-18
      - npm
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/TypeScript
      tag: v${{package.version}}
      expected-commit: 8eb3367164dd9cdc9c0b85424ed39ab28eff2312

  - runs: |
      # there's currently no arm based dprint prettier plugin available, for the future check https://github.com/dprint/dprint-plugin-prettier/releases
      # as this plugin is used to format the codebase, we can remove it from the .dprint.jsonc file
      sed -i '/https:\/\/plugins.dprint.dev\/prettier-0.27.0.json@3557a62b4507c55a47d8cde0683195b14d13c41dda66d0f0b0e111aed107e2fe/d' .dprint.jsonc

      npm ci
      npx hereby LKG

      mkdir -p "${{targets.destdir}}"/usr/lib/node_modules/typescript
      mv lib "${{targets.destdir}}"/usr/lib/node_modules/typescript/lib
      mv bin "${{targets.destdir}}"/usr/lib/node_modules/typescript/bin

      mkdir -p "${{targets.destdir}}"/usr/bin
      for f in "${{targets.destdir}}"/usr/lib/node_modules/typescript/bin/*; do
        ln -s "/usr/lib/node_modules/typescript/bin/$(basename $f)" "${{targets.destdir}}/usr/bin/$(basename $f)"
      done

update:
  enabled: true
  github:
    identifier: microsoft/TypeScript
    strip-prefix: v
    tag-filter: v
    use-tag: true
