package:
  name: unixodbc
  version: 2.3.12
  epoch: 2
  description: ODBC is an open specification to access Data Sources
  copyright:
    - license: LGPL-2.0-or-later
  # Require a config, basically /etc/odbc.ini and /etc/odbcinst.ini
  # By default they are empty
  dependencies:
    runtime:
      - ${{package.name}}-config

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: f210501445ce21bf607ba51ef8c125e10e22dffdffec377646462df5f01915ec
      uri: http://www.unixodbc.org/unixODBC-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --disable-nls \
        --enable-gui=no \
        --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

  # Remove files that come from the -config package.
  - runs: |
      rm ${{targets.destdir}}/etc/odbc.ini
      rm ${{targets.destdir}}/etc/odbcinst.ini

subpackages:
  - name: unixodbc-config
    description: Default config files, expected to be overwritten by drivers.
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php"
          touch ${{targets.subpkgdir}}/etc/odbc.ini
          touch ${{targets.subpkgdir}}/etc/odbcinst.ini

  - name: unixodbc-static
    pipeline:
      - uses: split/static
    description: unixodbc static

  - name: unixodbc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - unixodbc
    description: unixodbc dev

  - name: unixodbc-doc
    pipeline:
      - uses: split/manpages
    description: unixodbc manpages

update:
  enabled: true
  github:
    identifier: lurcher/unixODBC
