package:
  name: up
  version: 0.25.0
  epoch: 0
  description: The Upbound CLI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/upbound/up
      tag: v${{package.version}}
      expected-commit: 7dcb9c875efc65038a565facfe24fa56502f5aeb

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0 github.com/cyphar/filepath-securejoin@v0.2.4 github.com/containerd/containerd@v1.7.11 google.golang.org/grpc@v1.58.3 oras.land/oras-go@v1.2.5 github.com/google/go-containerregistry@v0.19.0 helm.sh/helm/v3@v3.14.2
      replaces: github.com/containerd/containerd=github.com/containerd/containerd@v1.7.11 github.com/docker/cli=github.com/docker/cli@v25.0.1+incompatible github.com/docker/docker=github.com/docker/docker@v25.0.1+incompatible oras.land/oras-go=oras.land/oras-go@v1.2.5 k8s.io/apiextensions-apiserver=k8s.io/apiextensions-apiserver@v0.28.2 k8s.io/apiserver=k8s.io/apiserver@v0.28.2 k8s.io/kubectl=k8s.io/kubectl@v0.28.2 k8s.io/api=k8s.io/api@v0.28.2 k8s.io/apimachinery=k8s.io/apimachinery@v0.28.2 k8s.io/client-go=k8s.io/client-go@v0.28.2 k8s.io/client-go=k8s.io/client-go@v0.28.2 k8s.io/cli-runtime=k8s.io/cli-runtime@v0.28.2
      show-diff: true

  - runs: |
      make submodules
      make install

      # This installs `up` into `$GOPATH/bin/up`, but we want it in `/usr/bin/up`.
      mkdir -p "${{targets.destdir}}"/usr/bin
      install -Dm755 $(go env GOPATH)/bin/up "${{targets.destdir}}"/usr/bin/up

  - uses: strip

update:
  enabled: true
  github:
    identifier: upbound/up
    strip-prefix: v
