package:
  name: uutils
  version: 0.0.25
  epoch: 0
  description: "Cross-platform Rust rewrite of the GNU coreutils."
  copyright:
    - license: MIT
  dependencies:
    provides:
      - coreutils

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/uutils/coreutils/archive/refs/tags/${{package.version}}.tar.gz
      expected-sha256: e6e4626e18eb5bd68480fc4860dc6203259a931d0357f8da900d8f5d6926c7ce

  - name: Configure and build
    runs: |
      cargo build --release --features unix
      mkdir -p ${{targets.destdir}}/usr
      make PREFIX=${{targets.destdir}}/usr MULTICALL=y install

      # Remove utilities provided by procps
      rm ${{targets.destdir}}/usr/bin/kill
      rm ${{targets.destdir}}/usr/bin/uptime

subpackages:
  - name: uutils-bash-completion
    description: bash completion for uutils
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/bash-completion"
          mv "${{targets.destdir}}/usr/share/bash-completion/completions" \
            "${{targets.subpkgdir}}/usr/share/bash-completion/completions"
    dependencies:
      runtime:
        - uutils

  - name: uutils-zsh-completion
    description: zsh completion for uutils
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/zsh"
          mv "${{targets.destdir}}/usr/share/zsh/site-functions" \
            "${{targets.subpkgdir}}/usr/share/zsh/site-functions"
    dependencies:
      runtime:
        - uutils

  - name: uutils-fish-completion
    description: fish completion for uutils
    pipeline:
      - runs: |
          set -x
          mkdir -p "${{targets.subpkgdir}}/usr/share/fish"
          mv "${{targets.destdir}}/usr/share/fish/vendor_completions.d" \
            "${{targets.subpkgdir}}/usr/share/fish/vendor_completions.d"
    dependencies:
      runtime:
        - uutils

update:
  enabled: true
  github:
    identifier: uutils/coreutils
