package:
  name: vala
  version: 0.56.16
  epoch: 0
  description: Compiler for the GObject type system
  copyright:
    - license: LGPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - glib-dev
      - gobject-introspection-dev
      - graphviz-dev
      - libxslt-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 05487b5600f5d2f09e66a753cccd8f39c1bff9f148aea1b7774d505b9c8bca9b
      uri: https://download.gnome.org/sources/vala/0.56/vala-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: vala-doc
    pipeline:
      - uses: split/manpages
    description: vala manpages

update:
  enabled: true
  release-monitor:
    identifier: 5065
