package:
  name: vault-k8s
  version: 1.4.0 # When updating, make sure to check that the license is still MPL!
  epoch: 3
  description: Tool for encryption as a service, secrets and privileged access management
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/vault-k8s
      tag: v${{package.version}}
      expected-commit: 1a8db92701b028327316380db6d634f7d3c5f944

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - runs: |
      # Our builtin LDFLAGS conflict with some makefile defined Go-specific ones.
      unset LDFLAGS
      make build GOARCH=$(go env GOARCH) VERSION=${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D dist/vault-k8s "${{targets.destdir}}/usr/bin/"

  - uses: strip

update:
  enabled: true
  github:
    identifier: hashicorp/vault-k8s
    strip-prefix: v
    use-tag: true
