package:
  name: vault-csi-provider
  version: 1.4.0
  epoch: 12
  description: CSI (Container Storage Interface) plugin for HashiCorp Vault
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/vault-csi-provider
      tag: v${{package.version}}
      expected-commit: db1021c1bc6564ae0aa0ce3d977d6de52886a232
      destination: vault-csi

  - uses: go/bump
    with:
      deps: golang.org/x/crypto@v0.17.0 sigs.k8s.io/secrets-store-csi-driver@v1.3.3 google.golang.org/grpc@v1.56.3 golang.org/x/net@v0.17.0 google.golang.org/protobuf@v1.33.0
      modroot: vault-csi

  - runs: |
      cd vault-csi
      # Our builtin LDFLAGS conflict with some makefile defined Go-specific ones.
      unset LDFLAGS

      make build GOARCH=$(go env GOARCH) VERSION=${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D vault-csi/dist/vault-csi-provider "${{targets.destdir}}/usr/bin/"

  - uses: strip

update:
  enabled: false
