package:
  name: vector
  version: 0.37.0
  epoch: 0
  description: End-to-end observability data pipeline
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - cyrus-sasl-dev
      - librdkafka
      - librdkafka-dev
      - openssl
      - openssl-dev
      - perl
      - pkgconf-dev
      - protobuf-dev
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vectordotdev/vector
      tag: v${{package.version}}
      expected-commit: c1da408b34fe29f8c949e18f08867066b080b2f5

  - runs: |
      sed -i '7s/deny/allow/' src/lib.rs
      make build

  - runs: |
      install -Dm755 target/release/vector "${{targets.destdir}}"/usr/bin/vector
      mkdir -p "${{targets.destdir}}"/etc/vector
      cp config/vector.yaml "${{targets.destdir}}"/etc/vector/vector.yaml

  - uses: strip

update:
  enabled: true
  github:
    identifier: vectordotdev/vector
    strip-prefix: v
