package:
  name: velero
  version: 1.13.1
  epoch: 2
  description: Backup and migrate Kubernetes applications and their persistent volumes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - restic
      - wolfi-base

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      tag: v${{package.version}}
      expected-commit: ea5a89f83b89b2cb7a27f54148683c1ee8d57a37
      repository: https://github.com/vmware-tanzu/velero

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: ./cmd/velero
      output: velero
      ldflags: "-s -w -X main.version=v${{package.version}} -X github.com/vmware-tanzu/velero/pkg/buildinfo.Version=v${{package.version}} -extldflags '-static'"

  - uses: go/build
    with:
      packages: ./cmd/velero-restore-helper
      output: velero-restore-helper
      ldflags: "-s -w -X main.version=v${{package.version}} -X github.com/vmware-tanzu/velero/pkg/buildinfo.Version=v${{package.version}} -extldflags '-static'"

  - uses: strip

subpackages:
  - name: "velero-restore-helper"
    description: Velero Restore Helper
    pipeline:
      - working-directory: ${{targets.subpkgdir}}/usr/bin
        runs: |
          mv ${{targets.destdir}}/usr/bin/velero-restore-helper velero-restore-helper

  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/velero ${{targets.subpkgdir}}/velero
          ln -sf /usr/bin/velero-restore-helper ${{targets.subpkgdir}}/velero-restore-helper

update:
  enabled: true
  github:
    identifier: vmware-tanzu/velero
    strip-prefix: v
    use-tag: true
