package:
  name: velero-plugin-for-csi
  version: 0.7.0
  epoch: 1
  description: Velero plugins for integrating with CSI snapshot API
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      tag: v${{package.version}}
      expected-commit: f6f3583c49009df7588183b71ee4847e67d96fb5
      repository: https://github.com/vmware-tanzu/velero-plugin-for-csi

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0

  - uses: go/build
    with:
      packages: .
      output: velero-plugin-for-csi
      ldflags: "-s -w"

  - uses: go/build
    with:
      packages: ./hack/cp-plugin
      output: cp-plugin
      ldflags: "-s -w"

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream Dockerfile"
    pipeline:
      - runs: |
          # The Dockerfile expects the binaries to be in /bin instead of /usr/bin
          # also the plugin binary is expected to be in /plugins directory
          # https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/36e5755ebeb6fa34ce72f6e4afa309d72b619469/Dockerfile#L33-L34
          mkdir -p "${{targets.subpkgdir}}"/bin
          mkdir -p "${{targets.subpkgdir}}"/plugins
          # /target directory is created to match the Dockerfile
          # https://github.com/vmware-tanzu/velero-plugin-for-csi/blob/36e5755ebeb6fa34ce72f6e4afa309d72b619469/Dockerfile#L36C66-L36C95
          mkdir -p "${{targets.subpkgdir}}"/target
          cp "${{targets.destdir}}"/usr/bin/velero-plugin-for-csi "${{targets.subpkgdir}}"/plugins/velero-plugin-for-csi
          ln -sf /usr/bin/cp-plugin "${{targets.subpkgdir}}"/bin/cp-plugin

update:
  enabled: true
  github:
    identifier: vmware-tanzu/velero-plugin-for-csi
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - velero-plugin-for-csi-compat
  pipeline:
    - runs: |
        /bin/cp-plugin /plugins/velero-plugin-for-csi /target/velero-plugin-for-csi
        # check the /target directory if there is velero-plugin-for-csi exist
        ls /target/velero-plugin-for-csi
        set +e
        /target/velero-plugin-for-csi -h
