package:
  name: vertical-pod-autoscaler
  version: 1.0.0
  epoch: 5
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: vertical-pod-autoscaler-${{package.version}}
      expected-commit: 276f1b8b4ba7bcd118bc59b987b47d79377fd561

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/protobuf@v1.33.0
      modroot: vertical-pod-autoscaler

  - uses: go/build
    with:
      modroot: vertical-pod-autoscaler
      packages: ./pkg/admission-controller
      ldflags: -w
      output: admission-controller

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.17.0 google.golang.org/protobuf@v1.33.0
      modroot: vertical-pod-autoscaler

  - uses: go/build
    with:
      modroot: vertical-pod-autoscaler
      packages: ./pkg/updater
      ldflags: -w
      output: updater

  - uses: go/build
    with:
      modroot: vertical-pod-autoscaler
      packages: ./pkg/recommender
      ldflags: -w
      output: recommender
      # Mitigate CVE-2023-39325 and CVE-2023-3978
      deps: golang.org/x/net@v0.17.0
      vendor: "true"

  - uses: strip

subpackages:
  - name: vertical-pod-autoscaler-updater
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/updater ${{targets.subpkgdir}}/usr/bin

  - name: vertical-pod-autoscaler-recommender
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/recommender ${{targets.subpkgdir}}/usr/bin

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: vertical-pod-autoscaler-
    use-tag: true
    tag-filter: vertical-pod-autoscaler-
