package:
  name: vexctl
  version: 0.2.6
  epoch: 2
  description: A tool to create, transform and attest VEX metadata
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: go/install
    with:
      package: github.com/openvex/vexctl
      version: v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: openvex/vexctl
    strip-prefix: v
