package:
  name: vulkan-loader
  version: 1.3.281
  epoch: 0
  description: Vulkan Installable Client Driver (ICD) Loader
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libx11-dev
      - libxrandr-dev
      - libxrender-dev
      - samurai
      - vulkan-headers
      - wayland-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/KhronosGroup/Vulkan-Loader
      tag: v${{package.version}}
      expected-commit: 0704d5a0e1f104f09b2dd639d0a159bcc205fd9c

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_DATADIR=share \
        -DCMAKE_SKIP_RPATH=True \
        -DVULKAN_HEADERS_INSTALL_DIR=/usr
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - ulkan-sdk
  github:
    identifier: KhronosGroup/Vulkan-Loader
    strip-prefix: v
    use-tag: true
    tag-filter: v
