package:
  name: vulkan-headers
  version: 1.3.281
  epoch: 0
  description: Vulkan header files and API registry
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/KhronosGroup/Vulkan-Headers
      tag: v${{package.version}}
      expected-commit: cfebfc96b2b0bce93da7d12f2c14cc01793ae25c

  - runs: |
      cmake -B build \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib
      make -C build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

update:
  enabled: true
  github:
    identifier: KhronosGroup/Vulkan-Headers
    strip-prefix: v
    use-tag: true
    tag-filter: v1
