package:
  name: wasmtime
  version: 18.0.3
  epoch: 0
  description: "A fast and secure runtime for WebAssembly"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libLLVM-15
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wasmtime
      tag: v${{package.version}}
      expected-commit: ff528a2ba15cb438e989538a22c84882e14c731e

  - name: Configure and build
    runs: |
      git submodule update --init
      cargo build --release -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasmtime ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: "libwasmtime"
    description: "c library for wasmtime"
    pipeline:
      - runs: |
          cargo build --release --manifest-path crates/c-api/artifact/Cargo.toml
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv target/release/libwasmtime.* ${{targets.subpkgdir}}/usr/lib/
      - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wasmtime
    strip-prefix: v
