package:
  name: weaviate
  version: 1.24.2
  epoch: 0
  description: Weaviate is an open source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering with the fault-tolerance and scalability of a cloud-native database, all accessible through GraphQL, REST, and various language clients.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: dcd8dc211ec979544e43f249cc0eb91d4f691ebe
      repository: https://github.com/weaviate/weaviate
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3

  - runs: |
      mkdir -p ${{targets.destdir}}/bin
      GITHASH=$(git rev-parse --short HEAD)
      go build \
        -ldflags '-w -extldflags "-static" -X github.com/weaviate/weaviate/usecases/config.GitHash='"$GITHASH"'' \
        -o ${{targets.destdir}}/bin/weaviate ./cmd/weaviate-server

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: weaviate/weaviate
    strip-prefix: v
    tag-filter: v
    use-tag: true
