package:
  name: wizer
  version: 5.0.0
  epoch: 0
  description: "The WebAssembly Pre-Initializer"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libLLVM-15
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wizer.git
      tag: v${{package.version}}
      expected-commit: 3c0d633fd0d74f0e706cdd4540a3648c0ff852a8

  - name: Configure and build
    runs: |
      cargo build --release -vv --all-features
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wizer ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wizer
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - runs: |
        wizer -V
