package:
  name: wolfictl
  version: 0.15.18
  epoch: 0
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: 4085650265307e2074f524aecd50b95ff032cd24
      destination: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
