package:
  name: xorg-server
  version: 21.1.12
  epoch: 0
  description: "X Server"
  copyright:
    - license: SGI-B-2.0
  dependencies:
    runtime:
      - dbus
      - dbus-x11
      - font-misc
      - systemd
      - ttf-dejavu
      - xkbcomp
      - xkeyboard-config

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - dbus-dev
      - eudev-dev
      - freetype-dev
      - libdrm
      - libdrm-dev
      - libepoxy-dev
      - libfontenc-dev
      - libgcrypt-dev
      - libpciaccess-dev
      - libx11-dev
      - libxcvt-dev
      - libxext-dev
      - libxfixes-dev
      - libxfont-dev
      - libxkbfile-dev
      - libxshmfence-dev
      - libxxf86vm-dev
      - mesa-dev
      - mesa-gbm
      - mesa-gl
      - pixman-dev
      - zlib-dev

data:
  - name: bins
    items:
      Xvfb: Virtual Framebuffer 'fake' X server
      Xnest: A nested Xorg server
      gtf: Generate mode timings using the GTF Timing Standard

pipeline:
  - uses: fetch
    with:
      uri: https://www.x.org/releases/individual/xserver/xorg-server-${{package.version}}.tar.xz
      expected-sha256: 1e016e2be1b5ccdd65eac3ea08e54bd13ce8f4f6c3fb32ad6fdac4e71729a90f

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --with-default-font-path=/usr/share/fonts/misc \
        --with-xkb-path=/usr/share/X11/xkb \
        --enable-xorg \
        --enable-glamor \
        --enable-xnest \
        --enable-xvfb \
        --enable-xcsecurity \
        --enable-suid-wrapper \
        --enable-pciaccess \
        --enable-config-udev \
        --disable-config-hal \
        --enable-systemd-logind \
        --enable-dri \
        --enable-dri2 \
        --enable-dri3 \
        --mandir=/usr/share/man

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: ${{package.name}} dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - xorg-server

  - range: bins
    name: ${{range.key}}
    description: ${{range.value}}
    pipeline:
      - runs: |
          install -Dm755 "${{targets.destdir}}"/usr/bin/${{range.key}} "${{targets.subpkgdir}}"/usr/bin/${{range.key}}

  - name: xvfb-run
    description: imlib2 dev
    dependencies:
      runtime:
        - coreutils
        - xauth
        - mcookie
    pipeline:
      - uses: git-checkout
        with:
          repository: https://salsa.debian.org/xorg-team/xserver/xorg-server
          branch: debian-unstable
          expected-commit: d9661596751d3c472f6dabf5db6e1e1188c89885
      - working-directory: debian/local
        pipeline:
          - runs: |
              install -Dm755 xvfb-run "${{targets.subpkgdir}}"/usr/bin/xvfb-run
              install -D xvfb-run.1 "${{targets.subpkgdir}}"/usr/share/man/man1/xvfb-run.1

  - name: ${{package.name}}-common
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/xorg
          mv ${{targets.destdir}}/usr/lib/xorg/protocol.txt ${{targets.subpkgdir}}/usr/lib/xorg/

update:
  enabled: true
  release-monitor:
    identifier: 5250
