package:
  name: yamllint
  version: 1.35.1
  epoch: 1
  description: "A linter for YAML"
  copyright:
    - license: GPL-3.0-or-later
  dependencies:
    runtime:
      - py3-pathspec
      - py3-pyyaml

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/adrienverge/yamllint
      tag: v${{package.version}}
      expected-commit: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6

  - uses: python/build

  - uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: adrienverge/yamllint
    use-tag: true
    strip-prefix: v
