package:
  name: ytt
  version: 0.48.0
  epoch: 2
  description: YAML templating tool that works on YAML structure instead of text
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3ad1c61f11c0d16b6668d90aa416559f29f03433cb5053f7aefa64fa445f5054
      uri: https://github.com/carvel-dev/ytt/archive/refs/tags/v${{package.version}}.tar.gz

  - uses: go/build
    with:
      packages: ./cmd/ytt
      output: ytt
      ldflags: -w -X github.com/vmware-tanzu/carvel-ytt/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/ytt
    strip-prefix: v
