package:
  name: zarf
  version: 0.32.6
  epoch: 1
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 06890072b956dc693aab2a1962aa9f74398fe99a
      repository: https://github.com/defenseunicorns/zarf
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
