package:
  name: zstd-cmake
  version: 1.5.6
  epoch: 0
  description: "cmake files for the Zstandard compression algorithm"
  copyright:
    - license: BSD-2-Clause AND GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - grep
      - samurai
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/facebook/zstd
      expected-commit: 794ea1b0afca0f020f4e57b6732332231fb23c70
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -S build/cmake \
        -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      rm -rf ${{targets.destdir}}/usr/bin
      rm -rf ${{targets.destdir}}/usr/share
      rm -rf ${{targets.destdir}}/usr/lib/lib*
      rm -rf ${{targets.destdir}}/usr/lib/pkgconfig
      rm -rf ${{targets.destdir}}/usr/include

update:
  enabled: true
  github:
    identifier: facebook/zstd
    strip-prefix: v
    tag-filter: v
