name: Run a command in Docker
description: Wraps the given `cmd` in a `docker run`
inputs:
  run:
    description: "The command/script to run"
    required: true
  image:
    description: "The image to use"
    default: "ghcr.io/wolfi-dev/sdk:latest@sha256:b013f8bd16a19f1514d51b32d0c15970e83afe6c0c4845dc9c9a5083997b4965"
    required: false
  workdir:
    description: "The images working directory"
    default: "/github/home"
    required: false
  opts:
    description: "Extra options to pass to docker run"
    default: ""
    required: false

runs:
  using: composite
  steps:
    - name: Run in Docker
      shell: bash
      run: |
        docker run \
          --privileged \
          --security-opt "seccomp=unconfined" \
          --security-opt "apparmor:unconfined" \
          -v "$PWD":"${{ inputs.workdir }}" \
          -v /home/runner:/home/runner \
          --workdir "${{ inputs.workdir }}" \
          --entrypoint "bash" \
          -e "HOME=${{ inputs.workdir }}" \
          -e "GITHUB_ACTIONS=true" \
          -e "CI=true" \
          -e CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=${CLOUDSDK_AUTH_CREDENTIAL_FILE} \
          -e GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS} \
          -e GOOGLE_GHA_CREDS_PATH=${GOOGLE_GHA_CREDS_PATH} \
          -i \
          ${{ inputs.opts }} \
          ${{ inputs.image }} <<EOF
        set -e
        ${{ inputs.run }}
        EOF
