name: Image digest update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read # To clone the repo
      id-token: write # To gitsign and federate

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: digestabot

    - uses: chainguard-dev/digestabot@4298e530896fb4164f9c89030c561b75b9321149 # v1.0.2
      with:
        token: ${{ steps.octo-sts.outputs.token }}
        author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
        committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
