name: 'Close stale'

on:
  schedule:
  - cron: '0 1 * * *'

permissions:
  contents: read

jobs:
  stale:
    # These are the permissions recommended by github.
    permissions:
      issues: write
      pull-requests: write

    runs-on: 'ubuntu-latest'
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        stale-pr-message: |-
          This Pull Request is stale because it has been open for 90 days with
          no activity. It will automatically close after 30 more days of
          inactivity. Keep fresh with the 'lifecycle/frozen' label.
        stale-pr-label: 'lifecycle/stale'
        exempt-pr-labels: 'lifecycle/frozen'

        days-before-stale: 90
        days-before-close: 30
