name: Wolfictl Lint

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

permissions:
  contents: read

jobs:
  lint:
    name: Wolfictl Lint
    runs-on: ubuntu-latest

    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    # this need to point to main to always get the latest action
    - uses: wolfi-dev/actions/wolfictl-lint@main # main
